server {
  listen 3000;
  large_client_header_buffers 16 64k;
  client_max_body_size 50m;

  location /rest/v1/ {
    proxy_pass http://supabase_rest_browser-perf:3000/;
    proxy_set_header Host $host;
    proxy_buffers 16 64k;
    proxy_buffer_size 64k;
  }
  location /auth/v1/ {
    proxy_pass http://supabase_auth_browser-perf:9999/;
    proxy_set_header Host $host;
  }
  location /storage/v1/ {
    proxy_pass http://supabase_storage_browser-perf:5000/;
    proxy_set_header Host $host;
  }
  location / {
    proxy_pass http://supabase_kong_browser-perf:8000;
    proxy_set_header Host $host;
  }
}
