-- Xenios Care PR 6: private messaging, laboratory metadata, and
-- adverse-event/quality-issue foundation.
-- Additive and idempotent. This migration creates no patient, clinician,
-- provider, laboratory, message, result, event, notification, or seed record
-- and cannot enable the canonical Care capability.

create extension if not exists pgcrypto;

create table if not exists public.care_message_threads (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  appointment_id uuid not null references public.care_appointments(id),
  assigned_clinician_user_id uuid not null references auth.users(id),
  status text not null default 'open' check (status in ('open','closed')),
  subject_category text not null
    check (length(subject_category) between 3 and 120),
  version integer not null default 0 check (version >= 0),
  create_idempotency_key text not null
    check (length(create_idempotency_key) between 8 and 128),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (patient_id, create_idempotency_key),
  unique (id, patient_id)
);

create unique index if not exists care_message_thread_open_appointment_idx
  on public.care_message_threads (appointment_id, patient_id)
  where status='open';

create table if not exists public.care_messages (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.care_message_threads(id)
    on delete cascade,
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  sender_user_id uuid not null references auth.users(id),
  sender_kind text not null
    check (sender_kind in ('care_patient','human_clinician')),
  body text not null check (length(body) between 1 and 10000),
  idempotency_key text not null check (length(idempotency_key) between 8 and 128),
  created_at timestamptz not null,
  unique (thread_id, idempotency_key)
);

create index if not exists care_messages_thread_time_idx
  on public.care_messages (thread_id, created_at);

create table if not exists public.care_message_events (
  id bigint generated by default as identity primary key,
  thread_id uuid not null references public.care_message_threads(id)
    on delete cascade,
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id),
  actor_kind text not null
    check (actor_kind in ('care_patient','human_clinician')),
  action text not null check (action in ('thread_created','message_posted')),
  idempotency_key text not null check (length(idempotency_key) between 8 and 128),
  occurred_at timestamptz not null,
  unique (thread_id, action, idempotency_key)
);

create table if not exists public.care_lab_cases (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  appointment_id uuid null references public.care_appointments(id),
  status text not null default 'awaiting_order_reference'
    check (status in (
      'awaiting_order_reference','order_reference_recorded',
      'result_reference_recorded','reviewed','closed'
    )),
  provider_reference text null,
  order_reference text null,
  result_reference text null,
  secure_object_reference text null,
  reviewed_by uuid null references auth.users(id),
  reviewed_at timestamptz null,
  version integer not null default 0 check (version >= 0),
  create_idempotency_key text not null
    check (length(create_idempotency_key) between 8 and 128),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (patient_id, create_idempotency_key),
  unique (id, patient_id),
  check (
    status='awaiting_order_reference'
    or (
      nullif(trim(provider_reference),'') is not null
      and nullif(trim(order_reference),'') is not null
    )
  ),
  check (
    status not in ('result_reference_recorded','reviewed','closed')
    or (
      nullif(trim(result_reference),'') is not null
      and nullif(trim(secure_object_reference),'') is not null
    )
  ),
  check (
    status not in ('reviewed','closed')
    or (reviewed_by is not null and reviewed_at is not null)
  )
);

create table if not exists public.care_lab_assignments (
  id uuid primary key default gen_random_uuid(),
  lab_case_id uuid not null references public.care_lab_cases(id) on delete cascade,
  reviewer_user_id uuid not null references auth.users(id),
  assigned_by uuid not null references auth.users(id),
  assigned_at timestamptz not null,
  revoked_at timestamptz null,
  check (revoked_at is null or revoked_at >= assigned_at)
);

create unique index if not exists care_lab_assignment_active_idx
  on public.care_lab_assignments (lab_case_id)
  where revoked_at is null;

create table if not exists public.care_lab_events (
  id bigint generated by default as identity primary key,
  lab_case_id uuid not null references public.care_lab_cases(id) on delete cascade,
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id),
  actor_kind text not null check (actor_kind in ('clinical_admin','lab_reviewer')),
  action text not null check (action in (
    'created','reviewer_assigned','record_order_reference',
    'record_result_reference','review','close'
  )),
  from_status text null,
  to_status text not null,
  idempotency_key text not null check (length(idempotency_key) between 8 and 128),
  occurred_at timestamptz not null,
  unique (lab_case_id, action, idempotency_key)
);

create table if not exists public.care_adverse_events (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  reporter_user_id uuid not null references auth.users(id),
  category text not null check (category in (
    'adverse_event','quality_concern','device_issue','other_issue'
  )),
  urgency text not null check (urgency in (
    'routine','urgent','possible_emergency'
  )),
  summary text not null check (length(summary) between 1 and 10000),
  emergency_guidance_acknowledged_at timestamptz not null,
  status text not null default 'reported'
    check (status in ('reported','acknowledged','escalated','closed')),
  acknowledged_at timestamptz null,
  escalated_at timestamptz null,
  closed_at timestamptz null,
  version integer not null default 0 check (version >= 0),
  report_idempotency_key text not null
    check (length(report_idempotency_key) between 8 and 128),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (patient_id, report_idempotency_key),
  unique (id, patient_id),
  check (status <> 'acknowledged' or acknowledged_at is not null),
  check (status <> 'escalated' or escalated_at is not null),
  check (status <> 'closed' or closed_at is not null)
);

create table if not exists public.care_adverse_event_assignments (
  id uuid primary key default gen_random_uuid(),
  adverse_event_id uuid not null references public.care_adverse_events(id)
    on delete cascade,
  owner_user_id uuid not null references auth.users(id),
  owner_role text not null check (owner_role in ('clinician','clinical_support')),
  assigned_by uuid not null references auth.users(id),
  assigned_at timestamptz not null,
  revoked_at timestamptz null,
  check (revoked_at is null or revoked_at >= assigned_at)
);

create unique index if not exists care_adverse_assignment_active_idx
  on public.care_adverse_event_assignments (adverse_event_id)
  where revoked_at is null;

create table if not exists public.care_adverse_event_history (
  id bigint generated by default as identity primary key,
  adverse_event_id uuid not null references public.care_adverse_events(id)
    on delete cascade,
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id),
  actor_kind text not null check (actor_kind in (
    'care_patient','clinical_admin','clinician','clinical_support'
  )),
  action text not null check (action in (
    'reported','owner_assigned','acknowledge','escalate','close'
  )),
  from_status text null,
  to_status text not null,
  idempotency_key text not null check (length(idempotency_key) between 8 and 128),
  occurred_at timestamptz not null,
  unique (adverse_event_id, action, idempotency_key)
);

do $$
declare table_name text; trigger_name text;
begin
  foreach table_name in array array[
    'care_messages','care_message_events','care_lab_events',
    'care_adverse_event_history'
  ]
  loop
    trigger_name := table_name || '_append_only';
    execute format('drop trigger if exists %I on public.%I',trigger_name,table_name);
    execute format(
      'create trigger %I before update or delete on public.%I
       for each row execute function public.care_reject_immutable_mutation()',
      trigger_name,table_name
    );
  end loop;
end;
$$;

create or replace function public.care_create_message_thread(
  p_patient_id uuid,
  p_appointment_id uuid,
  p_subject_category text,
  p_patient_user_id uuid,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_message_threads
language plpgsql
security definer
set search_path=''
as $$
declare thread_row public.care_message_threads%rowtype;
declare appointment_row public.care_appointments%rowtype;
begin
  if not exists (
    select 1 from public.care_patients patient
    join public.care_role_assignments assignment
      on assignment.user_id=patient.user_id
      and assignment.role='care_patient' and assignment.revoked_at is null
    where patient.id=p_patient_id and patient.user_id=p_patient_user_id
  ) then raise exception 'care_patient_ownership_required' using errcode='42501'; end if;
  select * into appointment_row from public.care_appointments
    where id=p_appointment_id and patient_id=p_patient_id
      and assigned_clinician_user_id is not null;
  if not found or not exists (
    select 1 from public.care_role_assignments
    where user_id=appointment_row.assigned_clinician_user_id
      and role='clinician' and revoked_at is null
  ) then raise exception 'care_assigned_clinician_required' using errcode='23514'; end if;
  select * into thread_row from public.care_message_threads
    where patient_id=p_patient_id and create_idempotency_key=p_idempotency_key;
  if found then return thread_row; end if;
  insert into public.care_message_threads (
    patient_id,appointment_id,assigned_clinician_user_id,subject_category,
    create_idempotency_key,created_at,updated_at
  ) values (
    p_patient_id,p_appointment_id,appointment_row.assigned_clinician_user_id,
    p_subject_category,p_idempotency_key,p_occurred_at,p_occurred_at
  ) returning * into thread_row;
  insert into public.care_message_events (
    thread_id,patient_id,actor_user_id,actor_kind,action,idempotency_key,occurred_at
  ) values (
    thread_row.id,p_patient_id,p_patient_user_id,'care_patient',
    'thread_created',p_idempotency_key,p_occurred_at
  );
  return thread_row;
end;
$$;

create or replace function public.care_post_message(
  p_thread_id uuid,
  p_actor_user_id uuid,
  p_body text,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_messages
language plpgsql
security definer
set search_path=''
as $$
declare thread_row public.care_message_threads%rowtype;
declare message_row public.care_messages%rowtype;
declare sender_kind text;
begin
  select * into message_row from public.care_messages
    where thread_id=p_thread_id and idempotency_key=p_idempotency_key;
  if found then return message_row; end if;
  select * into thread_row from public.care_message_threads
    where id=p_thread_id and status='open';
  if not found then raise exception 'care_open_message_thread_required' using errcode='23514'; end if;
  if exists (
    select 1 from public.care_patients patient
    join public.care_role_assignments assignment
      on assignment.user_id=patient.user_id
      and assignment.role='care_patient' and assignment.revoked_at is null
    where patient.id=thread_row.patient_id and patient.user_id=p_actor_user_id
  ) then sender_kind := 'care_patient';
  elsif p_actor_user_id=thread_row.assigned_clinician_user_id and exists (
    select 1 from public.care_appointments appointment
    join public.care_role_assignments assignment
      on assignment.user_id=appointment.assigned_clinician_user_id
      and assignment.role='clinician' and assignment.revoked_at is null
    where appointment.id=thread_row.appointment_id
      and appointment.patient_id=thread_row.patient_id
      and appointment.assigned_clinician_user_id=p_actor_user_id
  ) then sender_kind := 'human_clinician';
  else raise exception 'care_message_participant_required' using errcode='42501'; end if;
  insert into public.care_messages (
    thread_id,patient_id,sender_user_id,sender_kind,body,idempotency_key,created_at
  ) values (
    thread_row.id,thread_row.patient_id,p_actor_user_id,sender_kind,
    p_body,p_idempotency_key,p_occurred_at
  ) returning * into message_row;
  insert into public.care_message_events (
    thread_id,patient_id,actor_user_id,actor_kind,action,idempotency_key,occurred_at
  ) values (
    thread_row.id,thread_row.patient_id,p_actor_user_id,sender_kind,
    'message_posted',p_idempotency_key,p_occurred_at
  );
  return message_row;
end;
$$;

create or replace function public.care_create_lab_case(
  p_patient_id uuid,
  p_appointment_id uuid,
  p_admin_user_id uuid,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_lab_cases
language plpgsql
security definer
set search_path=''
as $$
declare lab_row public.care_lab_cases%rowtype;
begin
  if not exists (
    select 1 from public.care_role_assignments
    where user_id=p_admin_user_id and role='clinical_admin' and revoked_at is null
  ) then raise exception 'care_clinical_admin_required' using errcode='42501'; end if;
  if not exists (select 1 from public.care_patients where id=p_patient_id)
    or (p_appointment_id is not null and not exists (
      select 1 from public.care_appointments
      where id=p_appointment_id and patient_id=p_patient_id
    ))
  then raise exception 'care_lab_patient_context_required' using errcode='23514'; end if;
  select * into lab_row from public.care_lab_cases
    where patient_id=p_patient_id and create_idempotency_key=p_idempotency_key;
  if found then return lab_row; end if;
  insert into public.care_lab_cases (
    patient_id,appointment_id,create_idempotency_key,created_at,updated_at
  ) values (
    p_patient_id,p_appointment_id,p_idempotency_key,p_occurred_at,p_occurred_at
  ) returning * into lab_row;
  insert into public.care_lab_events (
    lab_case_id,patient_id,actor_user_id,actor_kind,action,to_status,
    idempotency_key,occurred_at
  ) values (
    lab_row.id,p_patient_id,p_admin_user_id,'clinical_admin','created',
    lab_row.status,p_idempotency_key,p_occurred_at
  );
  return lab_row;
end;
$$;

create or replace function public.care_assign_lab_reviewer(
  p_lab_case_id uuid,
  p_reviewer_user_id uuid,
  p_admin_user_id uuid,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_lab_assignments
language plpgsql
security definer
set search_path=''
as $$
declare assignment_row public.care_lab_assignments%rowtype;
declare lab_row public.care_lab_cases%rowtype;
begin
  if not exists (
    select 1 from public.care_role_assignments
    where user_id=p_admin_user_id and role='clinical_admin' and revoked_at is null
  ) then raise exception 'care_clinical_admin_required' using errcode='42501'; end if;
  if not exists (
    select 1 from public.care_role_assignments
    where user_id=p_reviewer_user_id and role='lab_reviewer' and revoked_at is null
  ) then raise exception 'care_lab_reviewer_required' using errcode='23514'; end if;
  select * into lab_row from public.care_lab_cases where id=p_lab_case_id;
  if not found then raise exception 'care_lab_case_required' using errcode='23503'; end if;
  select * into assignment_row from public.care_lab_assignments
    where lab_case_id=p_lab_case_id and reviewer_user_id=p_reviewer_user_id
      and revoked_at is null;
  if found then return assignment_row; end if;
  insert into public.care_lab_assignments (
    lab_case_id,reviewer_user_id,assigned_by,assigned_at
  ) values (
    p_lab_case_id,p_reviewer_user_id,p_admin_user_id,p_occurred_at
  ) returning * into assignment_row;
  insert into public.care_lab_events (
    lab_case_id,patient_id,actor_user_id,actor_kind,action,to_status,
    idempotency_key,occurred_at
  ) values (
    p_lab_case_id,lab_row.patient_id,p_admin_user_id,'clinical_admin',
    'reviewer_assigned',lab_row.status,p_idempotency_key,p_occurred_at
  );
  return assignment_row;
end;
$$;

create or replace function public.care_apply_lab_action(
  p_lab_case_id uuid,
  p_reviewer_user_id uuid,
  p_expected_version integer,
  p_action text,
  p_provider_reference text,
  p_order_reference text,
  p_result_reference text,
  p_secure_object_reference text,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_lab_cases
language plpgsql
security definer
set search_path=''
as $$
declare lab_row public.care_lab_cases%rowtype;
declare next_status text;
declare previous_status text;
begin
  if exists (
    select 1 from public.care_lab_events
    where lab_case_id=p_lab_case_id and action=p_action
      and idempotency_key=p_idempotency_key
  ) then
    select * into lab_row from public.care_lab_cases where id=p_lab_case_id;
    return lab_row;
  end if;
  if not exists (
    select 1 from public.care_lab_assignments assignment
    join public.care_role_assignments role_assignment
      on role_assignment.user_id=assignment.reviewer_user_id
      and role_assignment.role='lab_reviewer'
      and role_assignment.revoked_at is null
    where assignment.lab_case_id=p_lab_case_id
      and assignment.reviewer_user_id=p_reviewer_user_id
      and assignment.revoked_at is null
  ) then raise exception 'care_assigned_lab_reviewer_required' using errcode='42501'; end if;
  select * into lab_row from public.care_lab_cases
    where id=p_lab_case_id and version=p_expected_version;
  if not found then raise exception 'care_current_lab_case_required' using errcode='23514'; end if;
  previous_status := lab_row.status;
  next_status := case p_action
    when 'record_order_reference' then 'order_reference_recorded'
    when 'record_result_reference' then 'result_reference_recorded'
    when 'review' then 'reviewed'
    when 'close' then 'closed'
    else null end;
  if next_status is null or not (
    (lab_row.status='awaiting_order_reference' and p_action='record_order_reference'
      and nullif(trim(p_provider_reference),'') is not null
      and nullif(trim(p_order_reference),'') is not null)
    or (lab_row.status='order_reference_recorded' and p_action='record_result_reference'
      and nullif(trim(p_result_reference),'') is not null
      and nullif(trim(p_secure_object_reference),'') is not null)
    or (lab_row.status='result_reference_recorded' and p_action='review')
    or (lab_row.status='reviewed' and p_action='close')
  ) then raise exception 'care_invalid_lab_transition' using errcode='23514'; end if;
  update public.care_lab_cases set
    status=next_status,
    provider_reference=case when p_action='record_order_reference'
      then p_provider_reference else provider_reference end,
    order_reference=case when p_action='record_order_reference'
      then p_order_reference else order_reference end,
    result_reference=case when p_action='record_result_reference'
      then p_result_reference else result_reference end,
    secure_object_reference=case when p_action='record_result_reference'
      then p_secure_object_reference else secure_object_reference end,
    reviewed_by=case when p_action='review' then p_reviewer_user_id else reviewed_by end,
    reviewed_at=case when p_action='review' then p_occurred_at else reviewed_at end,
    version=version+1,updated_at=p_occurred_at
    where id=p_lab_case_id returning * into lab_row;
  insert into public.care_lab_events (
    lab_case_id,patient_id,actor_user_id,actor_kind,action,from_status,to_status,
    idempotency_key,occurred_at
  ) values (
    lab_row.id,lab_row.patient_id,p_reviewer_user_id,'lab_reviewer',p_action,
    previous_status,next_status,p_idempotency_key,p_occurred_at
  );
  return lab_row;
end;
$$;

create or replace function public.care_report_adverse_event(
  p_patient_id uuid,
  p_patient_user_id uuid,
  p_category text,
  p_urgency text,
  p_summary text,
  p_emergency_guidance_acknowledged boolean,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_adverse_events
language plpgsql
security definer
set search_path=''
as $$
declare event_row public.care_adverse_events%rowtype;
begin
  if not p_emergency_guidance_acknowledged then
    raise exception 'care_emergency_guidance_acknowledgment_required' using errcode='23514';
  end if;
  if not exists (
    select 1 from public.care_patients patient
    join public.care_role_assignments assignment
      on assignment.user_id=patient.user_id and assignment.role='care_patient'
      and assignment.revoked_at is null
    where patient.id=p_patient_id and patient.user_id=p_patient_user_id
  ) then raise exception 'care_patient_ownership_required' using errcode='42501'; end if;
  select * into event_row from public.care_adverse_events
    where patient_id=p_patient_id and report_idempotency_key=p_idempotency_key;
  if found then return event_row; end if;
  insert into public.care_adverse_events (
    patient_id,reporter_user_id,category,urgency,summary,
    emergency_guidance_acknowledged_at,report_idempotency_key,
    created_at,updated_at
  ) values (
    p_patient_id,p_patient_user_id,p_category,p_urgency,p_summary,
    p_occurred_at,p_idempotency_key,p_occurred_at,p_occurred_at
  ) returning * into event_row;
  insert into public.care_adverse_event_history (
    adverse_event_id,patient_id,actor_user_id,actor_kind,action,to_status,
    idempotency_key,occurred_at
  ) values (
    event_row.id,p_patient_id,p_patient_user_id,'care_patient','reported',
    'reported',p_idempotency_key,p_occurred_at
  );
  return event_row;
end;
$$;

create or replace function public.care_assign_adverse_event_owner(
  p_adverse_event_id uuid,
  p_owner_user_id uuid,
  p_owner_role text,
  p_admin_user_id uuid,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_adverse_event_assignments
language plpgsql
security definer
set search_path=''
as $$
declare assignment_row public.care_adverse_event_assignments%rowtype;
declare event_row public.care_adverse_events%rowtype;
begin
  if not exists (
    select 1 from public.care_role_assignments
    where user_id=p_admin_user_id and role='clinical_admin' and revoked_at is null
  ) then raise exception 'care_clinical_admin_required' using errcode='42501'; end if;
  if p_owner_role not in ('clinician','clinical_support') or not exists (
    select 1 from public.care_role_assignments
    where user_id=p_owner_user_id and role=p_owner_role and revoked_at is null
  ) then raise exception 'care_adverse_owner_role_required' using errcode='23514'; end if;
  select * into event_row from public.care_adverse_events
    where id=p_adverse_event_id;
  if not found then raise exception 'care_adverse_event_required' using errcode='23503'; end if;
  select * into assignment_row from public.care_adverse_event_assignments
    where adverse_event_id=p_adverse_event_id and owner_user_id=p_owner_user_id
      and owner_role=p_owner_role and revoked_at is null;
  if found then return assignment_row; end if;
  insert into public.care_adverse_event_assignments (
    adverse_event_id,owner_user_id,owner_role,assigned_by,assigned_at
  ) values (
    p_adverse_event_id,p_owner_user_id,p_owner_role,p_admin_user_id,p_occurred_at
  ) returning * into assignment_row;
  insert into public.care_adverse_event_history (
    adverse_event_id,patient_id,actor_user_id,actor_kind,action,to_status,
    idempotency_key,occurred_at
  ) values (
    event_row.id,event_row.patient_id,p_admin_user_id,'clinical_admin',
    'owner_assigned',event_row.status,p_idempotency_key,p_occurred_at
  );
  return assignment_row;
end;
$$;

create or replace function public.care_apply_adverse_event_action(
  p_adverse_event_id uuid,
  p_actor_user_id uuid,
  p_expected_version integer,
  p_action text,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_adverse_events
language plpgsql
security definer
set search_path=''
as $$
declare event_row public.care_adverse_events%rowtype;
declare owner_role text;
declare next_status text;
declare previous_status text;
begin
  if exists (
    select 1 from public.care_adverse_event_history
    where adverse_event_id=p_adverse_event_id and action=p_action
      and idempotency_key=p_idempotency_key
  ) then
    select * into event_row from public.care_adverse_events where id=p_adverse_event_id;
    return event_row;
  end if;
  select assignment.owner_role into owner_role
    from public.care_adverse_event_assignments assignment
    join public.care_role_assignments role_assignment
      on role_assignment.user_id=assignment.owner_user_id
      and role_assignment.role=assignment.owner_role
      and role_assignment.revoked_at is null
    where assignment.adverse_event_id=p_adverse_event_id
      and assignment.owner_user_id=p_actor_user_id
      and assignment.revoked_at is null;
  if owner_role is null then
    raise exception 'care_assigned_adverse_owner_required' using errcode='42501';
  end if;
  select * into event_row from public.care_adverse_events
    where id=p_adverse_event_id and version=p_expected_version;
  if not found then raise exception 'care_current_adverse_event_required' using errcode='23514'; end if;
  previous_status := event_row.status;
  next_status := case p_action
    when 'acknowledge' then 'acknowledged'
    when 'escalate' then 'escalated'
    when 'close' then 'closed'
    else null end;
  if next_status is null or not (
    (event_row.status='reported' and p_action='acknowledge')
    or (event_row.status in ('reported','acknowledged') and p_action='escalate')
    or (event_row.status in ('acknowledged','escalated') and p_action='close'
      and (event_row.urgency <> 'possible_emergency'
        or event_row.status='escalated'))
  ) then raise exception 'care_invalid_adverse_event_transition' using errcode='23514'; end if;
  update public.care_adverse_events set
    status=next_status,
    acknowledged_at=case when p_action='acknowledge'
      then p_occurred_at else acknowledged_at end,
    escalated_at=case when p_action='escalate'
      then p_occurred_at else escalated_at end,
    closed_at=case when p_action='close'
      then p_occurred_at else closed_at end,
    version=version+1,updated_at=p_occurred_at
    where id=p_adverse_event_id returning * into event_row;
  insert into public.care_adverse_event_history (
    adverse_event_id,patient_id,actor_user_id,actor_kind,action,
    from_status,to_status,idempotency_key,occurred_at
  ) values (
    event_row.id,event_row.patient_id,p_actor_user_id,owner_role,p_action,
    previous_status,next_status,p_idempotency_key,p_occurred_at
  );
  return event_row;
end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'care_message_threads','care_messages','care_message_events',
    'care_lab_cases','care_lab_assignments','care_lab_events',
    'care_adverse_events','care_adverse_event_assignments',
    'care_adverse_event_history'
  ]
  loop
    execute format('alter table public.%I enable row level security',table_name);
    execute format('alter table public.%I force row level security',table_name);
    execute format('revoke all on table public.%I from public,anon,authenticated',table_name);
  end loop;
end;
$$;

revoke all on function public.care_create_message_thread(uuid,uuid,text,uuid,text,timestamptz) from public,anon,authenticated;
revoke all on function public.care_post_message(uuid,uuid,text,text,timestamptz) from public,anon,authenticated;
revoke all on function public.care_create_lab_case(uuid,uuid,uuid,text,timestamptz) from public,anon,authenticated;
revoke all on function public.care_assign_lab_reviewer(uuid,uuid,uuid,text,timestamptz) from public,anon,authenticated;
revoke all on function public.care_apply_lab_action(uuid,uuid,integer,text,text,text,text,text,text,timestamptz) from public,anon,authenticated;
revoke all on function public.care_report_adverse_event(uuid,uuid,text,text,text,boolean,text,timestamptz) from public,anon,authenticated;
revoke all on function public.care_assign_adverse_event_owner(uuid,uuid,text,uuid,text,timestamptz) from public,anon,authenticated;
revoke all on function public.care_apply_adverse_event_action(uuid,uuid,integer,text,text,timestamptz) from public,anon,authenticated;

grant execute on function public.care_create_message_thread(uuid,uuid,text,uuid,text,timestamptz) to service_role;
grant execute on function public.care_post_message(uuid,uuid,text,text,timestamptz) to service_role;
grant execute on function public.care_create_lab_case(uuid,uuid,uuid,text,timestamptz) to service_role;
grant execute on function public.care_assign_lab_reviewer(uuid,uuid,uuid,text,timestamptz) to service_role;
grant execute on function public.care_apply_lab_action(uuid,uuid,integer,text,text,text,text,text,text,timestamptz) to service_role;
grant execute on function public.care_report_adverse_event(uuid,uuid,text,text,text,boolean,text,timestamptz) to service_role;
grant execute on function public.care_assign_adverse_event_owner(uuid,uuid,text,uuid,text,timestamptz) to service_role;
grant execute on function public.care_apply_adverse_event_action(uuid,uuid,integer,text,text,timestamptz) to service_role;

insert into public.care_capabilities (capability_key,state)
values ('care','disabled')
on conflict (capability_key) do update set
  state='disabled',approved_by=null,approved_at=null,updated_at=now();

-- Rollback posture:
-- 1. Keep Care disabled and remove PR6 route registration.
-- 2. Preserve messages, lab metadata, adverse-event records, and histories
--    until privacy/clinical/legal retention owners approve disposition.
-- 3. Revoke service-role RPC execution before any later table removal.
-- 4. Never cascade into auth, Research, or earlier Care tables.
