-- Xenios Care PR 4: prescription and pharmacy foundation.
--
-- Additive and idempotent. This migration seeds no pharmacy, license,
-- operator, prescription, instruction, medication, order, price, product,
-- shipment, or patient fact. Care remains disabled.

create extension if not exists pgcrypto;

create table if not exists public.care_pharmacies (
  id uuid primary key default gen_random_uuid(),
  legal_name text null,
  legal_address text null,
  agreement_reference text null,
  integration_reference text null,
  support_contact_reference text null,
  verification_state text not null default 'missing'
    check (verification_state in (
      'missing', 'entered', 'under_review', 'verified', 'rejected',
      'expired', 'superseded'
    )),
  verified_by uuid null references auth.users(id),
  verified_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    verification_state <> 'verified'
    or (
      nullif(trim(legal_name), '') is not null
      and nullif(trim(legal_address), '') is not null
      and nullif(trim(agreement_reference), '') is not null
      and nullif(trim(integration_reference), '') is not null
      and nullif(trim(support_contact_reference), '') is not null
      and verified_by is not null
      and verified_at is not null
    )
  )
);

create table if not exists public.care_pharmacy_licenses (
  id uuid primary key default gen_random_uuid(),
  pharmacy_id uuid not null references public.care_pharmacies(id) on delete cascade,
  state_code text not null check (state_code ~ '^[A-Z]{2}$'),
  license_number text null,
  expires_at timestamptz null,
  evidence_reference text null,
  verification_state text not null default 'missing'
    check (verification_state in (
      'missing', 'entered', 'under_review', 'verified', 'rejected',
      'expired', 'superseded'
    )),
  verified_by uuid null references auth.users(id),
  verified_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    verification_state <> 'verified'
    or (
      nullif(trim(license_number), '') is not null
      and expires_at is not null
      and nullif(trim(evidence_reference), '') is not null
      and verified_by is not null
      and verified_at is not null
    )
  )
);

create unique index if not exists care_pharmacy_license_verified_state_idx
  on public.care_pharmacy_licenses (pharmacy_id, state_code)
  where verification_state = 'verified';

create table if not exists public.care_pharmacy_state_coverage (
  id uuid primary key default gen_random_uuid(),
  pharmacy_id uuid not null references public.care_pharmacies(id) on delete cascade,
  state_code text not null check (state_code ~ '^[A-Z]{2}$'),
  dispensing_scope_reference text null,
  shipping_coverage_reference text null,
  instruction_source_reference text null,
  supply_source_reference text null,
  active boolean not null default false,
  verified_by uuid null references auth.users(id),
  verified_at timestamptz null,
  expires_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    not active
    or (
      nullif(trim(dispensing_scope_reference), '') is not null
      and nullif(trim(shipping_coverage_reference), '') is not null
      and nullif(trim(instruction_source_reference), '') is not null
      and nullif(trim(supply_source_reference), '') is not null
      and verified_by is not null
      and verified_at is not null
    )
  )
);

create unique index if not exists care_pharmacy_state_coverage_active_idx
  on public.care_pharmacy_state_coverage (pharmacy_id, state_code)
  where active;

create table if not exists public.care_pharmacy_operators (
  id uuid primary key default gen_random_uuid(),
  pharmacy_id uuid not null references public.care_pharmacies(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  active boolean not null default false,
  verified_by uuid null references auth.users(id),
  verified_at timestamptz null,
  revoked_at timestamptz null,
  created_at timestamptz not null default now(),
  check (
    not active
    or (
      verified_by is not null
      and verified_at is not null
      and revoked_at is null
    )
  )
);

create unique index if not exists care_pharmacy_operator_active_idx
  on public.care_pharmacy_operators (pharmacy_id, user_id)
  where active and revoked_at is null;

create table if not exists public.care_pharmacy_configuration_audit (
  id bigint generated by default as identity primary key,
  record_type text not null check (record_type in (
    'pharmacy', 'pharmacy_license', 'pharmacy_state_coverage', 'pharmacy_operator'
  )),
  record_key text not null,
  action text not null check (action in ('insert', 'update', 'delete')),
  old_record jsonb null,
  new_record jsonb null,
  occurred_at timestamptz not null default now()
);

create table if not exists public.care_prescription_content_sources (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  appointment_id uuid not null references public.care_appointments(id),
  clinician_review_id uuid not null references public.care_clinician_reviews(id),
  clinician_user_id uuid not null references auth.users(id),
  source_kind text not null default 'clinician_direction'
    check (source_kind = 'clinician_direction'),
  formulation text not null check (nullif(trim(formulation), '') is not null),
  concentration text not null check (nullif(trim(concentration), '') is not null),
  route text not null check (nullif(trim(route), '') is not null),
  quantity text not null check (nullif(trim(quantity), '') is not null),
  directions text not null check (nullif(trim(directions), '') is not null),
  refills integer not null check (refills between 0 and 99),
  verified_by uuid not null references auth.users(id),
  verified_at timestamptz not null,
  idempotency_key text not null check (length(idempotency_key) between 8 and 128),
  created_at timestamptz not null default now(),
  unique (clinician_user_id, idempotency_key)
);

create table if not exists public.care_prescriptions (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  appointment_id uuid not null references public.care_appointments(id),
  clinician_review_id uuid not null references public.care_clinician_reviews(id),
  prescribing_clinician_user_id uuid not null references auth.users(id),
  verified_content_source_id uuid not null
    references public.care_prescription_content_sources(id),
  status text not null default 'draft'
    check (status in ('draft', 'signed', 'superseded', 'cancelled')),
  version integer not null default 0 check (version >= 0),
  signed_at timestamptz null,
  supersedes_prescription_id uuid null references public.care_prescriptions(id),
  create_idempotency_key text not null check (length(create_idempotency_key) between 8 and 128),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (prescribing_clinician_user_id, create_idempotency_key),
  check (
    (status = 'draft' and signed_at is null)
    or (status in ('signed', 'superseded', 'cancelled') and signed_at is not null)
  ),
  check (supersedes_prescription_id is null or supersedes_prescription_id <> id)
);

create unique index if not exists care_prescription_one_active_signed_patient_idx
  on public.care_prescriptions (patient_id)
  where status = 'signed';

create table if not exists public.care_prescription_events (
  id bigint generated by default as identity primary key,
  prescription_id uuid not null references public.care_prescriptions(id) on delete cascade,
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id),
  actor_kind text not null check (actor_kind = 'human_clinician'),
  action text not null check (action in ('drafted', 'signed', 'superseded', 'cancelled')),
  from_status text null,
  to_status text not null,
  expected_version integer not null default 0 check (expected_version >= 0),
  idempotency_key text not null check (length(idempotency_key) between 8 and 128),
  occurred_at timestamptz not null,
  unique (prescription_id, idempotency_key)
);

create table if not exists public.care_pharmacy_orders (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  prescription_id uuid not null references public.care_prescriptions(id),
  assigned_pharmacy_id uuid not null references public.care_pharmacies(id),
  patient_state_code text not null check (patient_state_code ~ '^[A-Z]{2}$'),
  status text not null default 'pending_pharmacy'
    check (status in (
      'pending_pharmacy', 'received', 'clarification_requested', 'accepted',
      'rejected', 'dispensed', 'shipped', 'delivered', 'cancelled'
    )),
  clarification_open boolean not null default false,
  tracking_reference text null,
  version integer not null default 0 check (version >= 0),
  assignment_idempotency_key text not null check (length(assignment_idempotency_key) between 8 and 128),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (prescription_id),
  unique (assigned_pharmacy_id, assignment_idempotency_key),
  check (status <> 'shipped' or nullif(trim(tracking_reference), '') is not null)
);

create table if not exists public.care_pharmacy_order_events (
  id bigint generated by default as identity primary key,
  pharmacy_order_id uuid not null references public.care_pharmacy_orders(id) on delete cascade,
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id),
  actor_kind text not null check (actor_kind in (
    'clinical_admin', 'human_clinician', 'pharmacy_operator'
  )),
  action text not null,
  from_status text null,
  to_status text not null,
  clarification_reference text null,
  tracking_reference text null,
  expected_version integer not null default 0 check (expected_version >= 0),
  idempotency_key text not null check (length(idempotency_key) between 8 and 128),
  occurred_at timestamptz not null,
  unique (pharmacy_order_id, idempotency_key)
);

alter table public.care_pharmacy_order_events
  drop constraint if exists care_pharmacy_order_events_actor_kind_check;
alter table public.care_pharmacy_order_events
  add constraint care_pharmacy_order_events_actor_kind_check
  check (actor_kind in (
    'clinical_admin', 'human_clinician', 'pharmacy_operator'
  ));

alter table public.care_prescription_events
  add column if not exists expected_version integer not null default 0
  check (expected_version >= 0);
alter table public.care_pharmacy_order_events
  add column if not exists expected_version integer not null default 0
  check (expected_version >= 0);

create or replace function public.care_audit_pharmacy_configuration()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.care_pharmacy_configuration_audit (
    record_type, record_key, action, old_record, new_record
  ) values (
    case tg_table_name
      when 'care_pharmacies' then 'pharmacy'
      when 'care_pharmacy_licenses' then 'pharmacy_license'
      when 'care_pharmacy_state_coverage' then 'pharmacy_state_coverage'
      else 'pharmacy_operator'
    end,
    coalesce((to_jsonb(new)->>'id'), (to_jsonb(old)->>'id')),
    lower(tg_op),
    case when tg_op <> 'INSERT' then to_jsonb(old) end,
    case when tg_op <> 'DELETE' then to_jsonb(new) end
  );
  return coalesce(new, old);
end;
$$;

do $$
declare
  table_name text;
  trigger_name text;
begin
  foreach table_name in array array[
    'care_pharmacies', 'care_pharmacy_licenses',
    'care_pharmacy_state_coverage', 'care_pharmacy_operators'
  ]
  loop
    trigger_name := table_name || '_audit_write';
    execute format('drop trigger if exists %I on public.%I', trigger_name, table_name);
    execute format(
      'create trigger %I after insert or update or delete on public.%I
       for each row execute function public.care_audit_pharmacy_configuration()',
      trigger_name, table_name
    );
  end loop;
end;
$$;

do $$
declare
  table_name text;
  trigger_name text;
begin
  foreach table_name in array array[
    'care_pharmacy_configuration_audit',
    'care_prescription_content_sources',
    'care_prescription_events',
    'care_pharmacy_order_events'
  ]
  loop
    trigger_name := table_name || '_append_only';
    execute format('drop trigger if exists %I on public.%I', trigger_name, table_name);
    execute format(
      'create trigger %I before update or delete on public.%I
       for each row execute function public.care_reject_immutable_mutation()',
      trigger_name, table_name
    );
  end loop;
end;
$$;

create or replace function public.care_pharmacy_ready(
  p_pharmacy_id uuid,
  p_state_code text,
  p_as_of timestamptz default now()
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.care_pharmacies pharmacy
    join public.care_pharmacy_licenses license
      on license.pharmacy_id = pharmacy.id
      and license.state_code = p_state_code
      and license.verification_state = 'verified'
      and license.expires_at > p_as_of
    join public.care_pharmacy_state_coverage coverage
      on coverage.pharmacy_id = pharmacy.id
      and coverage.state_code = p_state_code
      and coverage.active
      and (coverage.expires_at is null or coverage.expires_at > p_as_of)
    where pharmacy.id = p_pharmacy_id
      and pharmacy.verification_state = 'verified'
  );
$$;

create or replace function public.care_prescription_context_current(
  p_patient_id uuid,
  p_appointment_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  appointment_row public.care_appointments%rowtype;
begin
  select * into appointment_row
  from public.care_appointments
  where id = p_appointment_id
    and patient_id = p_patient_id
  for share;
  if not found then return false; end if;

  return public.care_appointment_consents_current(
    appointment_row.intake_id,
    p_patient_id
  ) and public.care_supported_state_current(
    appointment_row.patient_state_code
  );
end;
$$;

create or replace function public.care_prescription_readiness(
  p_clinician_user_id uuid,
  p_pharmacy_id uuid,
  p_state_code text,
  p_prescription_id uuid,
  p_as_of timestamptz default now()
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'medical_group_verified',
    p_clinician_user_id is not null and exists (
      select 1
      from public.care_clinician_profiles profile
      join public.care_medical_groups medical_group
        on medical_group.id = profile.medical_group_id
       and medical_group.verification_state = 'verified'
      where profile.clinician_user_id = p_clinician_user_id
        and profile.verification_state = 'verified'
    ),
    'clinician_coverage_verified',
    p_clinician_user_id is not null
      and p_state_code is not null
      and public.care_clinician_ready(
        p_clinician_user_id,
        p_state_code,
        p_as_of
      ),
    'patient_specific_content_verified',
    p_prescription_id is not null
      and p_clinician_user_id is not null
      and exists (
        select 1
        from public.care_prescriptions prescription
        join public.care_prescription_content_sources source
          on source.id = prescription.verified_content_source_id
         and source.patient_id = prescription.patient_id
         and source.appointment_id = prescription.appointment_id
         and source.clinician_review_id = prescription.clinician_review_id
         and source.clinician_user_id = prescription.prescribing_clinician_user_id
        where prescription.id = p_prescription_id
          and prescription.prescribing_clinician_user_id = p_clinician_user_id
      ),
    'pharmacy_partner_verified',
    p_pharmacy_id is not null and exists (
      select 1 from public.care_pharmacies pharmacy
      where pharmacy.id = p_pharmacy_id
        and pharmacy.verification_state = 'verified'
    ),
    'pharmacy_identity_verified',
    p_pharmacy_id is not null and exists (
      select 1 from public.care_pharmacies pharmacy
      where pharmacy.id = p_pharmacy_id
        and pharmacy.verification_state = 'verified'
        and nullif(trim(pharmacy.legal_name), '') is not null
        and nullif(trim(pharmacy.legal_address), '') is not null
    ),
    'pharmacy_license_verified',
    p_pharmacy_id is not null
      and p_state_code is not null
      and exists (
        select 1 from public.care_pharmacy_licenses license
        where license.pharmacy_id = p_pharmacy_id
          and license.state_code = p_state_code
          and license.verification_state = 'verified'
          and license.expires_at > p_as_of
      ),
    'pharmacy_state_coverage_verified',
    p_pharmacy_id is not null
      and p_state_code is not null
      and exists (
        select 1 from public.care_pharmacy_state_coverage coverage
        where coverage.pharmacy_id = p_pharmacy_id
          and coverage.state_code = p_state_code
          and coverage.active
          and (coverage.expires_at is null or coverage.expires_at > p_as_of)
      ),
    'pharmacy_agreement_verified',
    p_pharmacy_id is not null and exists (
      select 1 from public.care_pharmacies pharmacy
      where pharmacy.id = p_pharmacy_id
        and pharmacy.verification_state = 'verified'
        and nullif(trim(pharmacy.agreement_reference), '') is not null
    ),
    'pharmacy_integration_verified',
    p_pharmacy_id is not null and exists (
      select 1 from public.care_pharmacies pharmacy
      where pharmacy.id = p_pharmacy_id
        and pharmacy.verification_state = 'verified'
        and nullif(trim(pharmacy.integration_reference), '') is not null
    ),
    'pharmacy_support_verified',
    p_pharmacy_id is not null and exists (
      select 1 from public.care_pharmacies pharmacy
      where pharmacy.id = p_pharmacy_id
        and pharmacy.verification_state = 'verified'
        and nullif(trim(pharmacy.support_contact_reference), '') is not null
    )
  );
$$;

create or replace function public.care_create_prescription_draft(
  p_patient_id uuid,
  p_review_id uuid,
  p_clinician_user_id uuid,
  p_formulation text,
  p_concentration text,
  p_route text,
  p_quantity text,
  p_directions text,
  p_refills integer,
  p_supersedes_prescription_id uuid,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_prescriptions
language plpgsql
security definer
set search_path = ''
as $$
declare
  review_row public.care_clinician_reviews%rowtype;
  appointment_row public.care_appointments%rowtype;
  source_row public.care_prescription_content_sources%rowtype;
  prescription_row public.care_prescriptions%rowtype;
begin
  select * into review_row from public.care_clinician_reviews
  where id = p_review_id and patient_id = p_patient_id
    and assigned_clinician_user_id = p_clinician_user_id
    and status = 'decided' and final_decision = 'approved'
    and final_decision_source = 'human_clinician'
  for share;
  if not found then raise exception 'care_approved_human_review_required' using errcode = '23514'; end if;

  select * into appointment_row
  from public.care_appointments
  where id = review_row.appointment_id
    and patient_id = p_patient_id
    and assigned_clinician_user_id = p_clinician_user_id
    and status = 'completed'
  for share;
  if not found then raise exception 'care_completed_assigned_appointment_required' using errcode = '23514'; end if;
  if not public.care_prescription_context_current(
    p_patient_id,
    appointment_row.id
  ) then raise exception 'care_current_consent_and_state_required' using errcode = '23514'; end if;
  if not public.care_clinician_ready(p_clinician_user_id, review_row.patient_state_code, p_occurred_at)
  then raise exception 'care_current_clinician_coverage_required' using errcode = '23514'; end if;
  if exists (
    select 1 from unnest(array[p_formulation,p_concentration,p_route,p_quantity,p_directions]) value
    where nullif(trim(value), '') is null
  ) or p_refills is null or p_refills not between 0 and 99
  then raise exception 'care_patient_specific_content_required' using errcode = '23514'; end if;
  if p_supersedes_prescription_id is not null and not exists (
    select 1 from public.care_prescriptions prior
    where prior.id = p_supersedes_prescription_id
      and prior.patient_id = p_patient_id
      and prior.prescribing_clinician_user_id = p_clinician_user_id
      and prior.status = 'signed'
  ) then raise exception 'care_valid_supersession_target_required' using errcode = '23514'; end if;

  select * into prescription_row
  from public.care_prescriptions
  where prescribing_clinician_user_id = p_clinician_user_id
    and create_idempotency_key = p_idempotency_key
  for update;
  if found then
    select * into source_row
    from public.care_prescription_content_sources
    where id = prescription_row.verified_content_source_id
      and patient_id = p_patient_id
      and appointment_id = appointment_row.id
      and clinician_review_id = p_review_id
      and clinician_user_id = p_clinician_user_id
    for share;
    if not found
      or prescription_row.patient_id <> p_patient_id
      or prescription_row.appointment_id <> appointment_row.id
      or prescription_row.clinician_review_id <> p_review_id
      or prescription_row.supersedes_prescription_id is distinct from p_supersedes_prescription_id
      or source_row.formulation <> trim(p_formulation)
      or source_row.concentration <> trim(p_concentration)
      or source_row.route <> trim(p_route)
      or source_row.quantity <> trim(p_quantity)
      or source_row.directions <> trim(p_directions)
      or source_row.refills <> p_refills
    then raise exception 'care_prescription_replay_mismatch' using errcode = '23514'; end if;
    return prescription_row;
  end if;

  insert into public.care_prescription_content_sources (
    patient_id, appointment_id, clinician_review_id, clinician_user_id,
    formulation, concentration, route, quantity, directions, refills,
    verified_by, verified_at, idempotency_key, created_at
  ) values (
    p_patient_id, review_row.appointment_id, p_review_id, p_clinician_user_id,
    trim(p_formulation), trim(p_concentration), trim(p_route), trim(p_quantity),
    trim(p_directions), p_refills, p_clinician_user_id, p_occurred_at,
    p_idempotency_key, p_occurred_at
  ) returning * into source_row;

  insert into public.care_prescriptions (
    patient_id, appointment_id, clinician_review_id,
    prescribing_clinician_user_id, verified_content_source_id,
    supersedes_prescription_id, create_idempotency_key, created_at, updated_at
  ) values (
    p_patient_id, review_row.appointment_id, p_review_id,
    p_clinician_user_id, source_row.id, p_supersedes_prescription_id,
    p_idempotency_key, p_occurred_at, p_occurred_at
  ) returning * into prescription_row;

  insert into public.care_prescription_events (
    prescription_id, patient_id, actor_user_id, actor_kind, action,
    to_status, expected_version, idempotency_key, occurred_at
  ) values (
    prescription_row.id, p_patient_id, p_clinician_user_id,
    'human_clinician', 'drafted', 'draft', 0, p_idempotency_key, p_occurred_at
  );
  return prescription_row;
end;
$$;

create or replace function public.care_sign_prescription(
  p_prescription_id uuid,
  p_clinician_user_id uuid,
  p_expected_version integer,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_prescriptions
language plpgsql
security definer
set search_path = ''
as $$
declare
  prescription_row public.care_prescriptions%rowtype;
  appointment_row public.care_appointments%rowtype;
  replay_event public.care_prescription_events%rowtype;
  state_code text;
begin
  select prescription.*
    into prescription_row
  from public.care_prescriptions prescription
  join public.care_prescription_content_sources source
    on source.id = prescription.verified_content_source_id
    and source.patient_id = prescription.patient_id
    and source.appointment_id = prescription.appointment_id
    and source.clinician_review_id = prescription.clinician_review_id
    and source.clinician_user_id = prescription.prescribing_clinician_user_id
  where prescription.id = p_prescription_id
  for update of prescription;
  if not found then raise exception 'care_signable_assigned_prescription_required' using errcode = '23514'; end if;
  if prescription_row.prescribing_clinician_user_id <> p_clinician_user_id
  then raise exception 'care_signable_assigned_prescription_required' using errcode = '23514'; end if;

  select * into appointment_row
  from public.care_appointments
  where id = prescription_row.appointment_id
    and patient_id = prescription_row.patient_id
    and assigned_clinician_user_id = p_clinician_user_id
    and status = 'completed'
  for share;
  if not found then raise exception 'care_completed_assigned_appointment_required' using errcode = '23514'; end if;
  if not public.care_prescription_context_current(
    prescription_row.patient_id,
    appointment_row.id
  ) then raise exception 'care_current_consent_and_state_required' using errcode = '23514'; end if;
  state_code := appointment_row.patient_state_code;
  if not public.care_clinician_ready(p_clinician_user_id, state_code, p_occurred_at)
  then raise exception 'care_current_clinician_coverage_required' using errcode = '23514'; end if;

  select * into replay_event
  from public.care_prescription_events
  where prescription_id = p_prescription_id
    and idempotency_key = p_idempotency_key
  for share;
  if found then
    if replay_event.actor_user_id <> p_clinician_user_id
      or replay_event.actor_kind <> 'human_clinician'
      or replay_event.action <> 'signed'
      or replay_event.from_status <> 'draft'
      or replay_event.to_status <> 'signed'
      or replay_event.expected_version <> p_expected_version
      or prescription_row.status <> 'signed'
    then raise exception 'care_prescription_replay_mismatch' using errcode = '23514'; end if;
    return prescription_row;
  end if;

  if prescription_row.status <> 'draft'
    or prescription_row.version <> p_expected_version
  then raise exception 'care_signable_assigned_prescription_required' using errcode = '23514'; end if;

  if prescription_row.supersedes_prescription_id is not null then
    update public.care_prescriptions
      set status = 'superseded', version = version + 1, updated_at = p_occurred_at
      where id = prescription_row.supersedes_prescription_id and status = 'signed';
    insert into public.care_prescription_events (
      prescription_id, patient_id, actor_user_id, actor_kind, action,
      from_status, to_status, expected_version, idempotency_key, occurred_at
    ) values (
      prescription_row.supersedes_prescription_id, prescription_row.patient_id,
      p_clinician_user_id, 'human_clinician', 'superseded', 'signed',
      'superseded', p_expected_version, p_idempotency_key || ':prior', p_occurred_at
    );
  end if;
  update public.care_prescriptions
    set status = 'signed', signed_at = p_occurred_at,
        version = version + 1, updated_at = p_occurred_at
    where id = p_prescription_id
    returning * into prescription_row;
  insert into public.care_prescription_events (
    prescription_id, patient_id, actor_user_id, actor_kind, action,
    from_status, to_status, expected_version, idempotency_key, occurred_at
  ) values (
    prescription_row.id, prescription_row.patient_id, p_clinician_user_id,
    'human_clinician', 'signed', 'draft', 'signed', p_expected_version,
    p_idempotency_key, p_occurred_at
  );
  return prescription_row;
end;
$$;

create or replace function public.care_assign_pharmacy_order(
  p_prescription_id uuid,
  p_pharmacy_id uuid,
  p_admin_user_id uuid,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_pharmacy_orders
language plpgsql
security definer
set search_path = ''
as $$
declare
  prescription_row public.care_prescriptions%rowtype;
  appointment_row public.care_appointments%rowtype;
  order_row public.care_pharmacy_orders%rowtype;
  replay_event public.care_pharmacy_order_events%rowtype;
  state_code text;
begin
  if not exists (
    select 1 from public.care_role_assignments
    where user_id = p_admin_user_id and role = 'clinical_admin' and revoked_at is null
  ) then raise exception 'care_clinical_admin_required' using errcode = '42501'; end if;
  select prescription.*
    into prescription_row
  from public.care_prescriptions prescription
  join public.care_appointments appointment on appointment.id = prescription.appointment_id
  where prescription.id = p_prescription_id
  for update of prescription;
  if not found then raise exception 'care_signed_prescription_required' using errcode = '23514'; end if;
  if prescription_row.status <> 'signed'
  then raise exception 'care_signed_prescription_required' using errcode = '23514'; end if;

  select * into appointment_row
  from public.care_appointments
  where id = prescription_row.appointment_id
    and patient_id = prescription_row.patient_id
  for share;
  if not found then raise exception 'care_prescription_appointment_required' using errcode = '23514'; end if;
  if not public.care_prescription_context_current(
    prescription_row.patient_id,
    appointment_row.id
  ) then raise exception 'care_current_consent_and_state_required' using errcode = '23514'; end if;
  state_code := appointment_row.patient_state_code;
  if not public.care_pharmacy_ready(p_pharmacy_id, state_code, p_occurred_at)
  then raise exception 'care_verified_pharmacy_coverage_required' using errcode = '23514'; end if;

  select * into order_row
  from public.care_pharmacy_orders
  where prescription_id = p_prescription_id
  for update;
  if found then
    select * into replay_event
    from public.care_pharmacy_order_events
    where pharmacy_order_id = order_row.id
      and idempotency_key = p_idempotency_key
    for share;
    if not found
      or order_row.patient_id <> prescription_row.patient_id
      or order_row.assigned_pharmacy_id <> p_pharmacy_id
      or order_row.patient_state_code <> state_code
      or order_row.assignment_idempotency_key <> p_idempotency_key
      or replay_event.actor_user_id <> p_admin_user_id
      or replay_event.actor_kind <> 'clinical_admin'
      or replay_event.action <> 'assigned'
      or replay_event.to_status <> 'pending_pharmacy'
    then raise exception 'care_pharmacy_assignment_replay_mismatch' using errcode = '23514'; end if;
    return order_row;
  end if;

  insert into public.care_pharmacy_orders (
    patient_id, prescription_id, assigned_pharmacy_id, patient_state_code,
    assignment_idempotency_key, created_at, updated_at
  ) values (
    prescription_row.patient_id, p_prescription_id, p_pharmacy_id, state_code,
    p_idempotency_key, p_occurred_at, p_occurred_at
  ) returning * into order_row;
  insert into public.care_pharmacy_order_events (
    pharmacy_order_id, patient_id, actor_user_id, actor_kind, action,
    to_status, expected_version, idempotency_key, occurred_at
  ) values (
    order_row.id, order_row.patient_id, p_admin_user_id, 'clinical_admin',
    'assigned', 'pending_pharmacy', 0, p_idempotency_key, p_occurred_at
  );
  return order_row;
end;
$$;

create or replace function public.care_apply_pharmacy_order_action(
  p_order_id uuid,
  p_operator_user_id uuid,
  p_expected_version integer,
  p_action text,
  p_clarification_reference text,
  p_tracking_reference text,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_pharmacy_orders
language plpgsql
security definer
set search_path = ''
as $$
declare
  order_row public.care_pharmacy_orders%rowtype;
  prescription_row public.care_prescriptions%rowtype;
  appointment_row public.care_appointments%rowtype;
  replay_event public.care_pharmacy_order_events%rowtype;
  next_status text;
  prior_status text;
begin
  select * into order_row
  from public.care_pharmacy_orders
  where id = p_order_id
  for update;
  if not found then raise exception 'care_current_pharmacy_order_required' using errcode = '23514'; end if;

  select * into prescription_row
  from public.care_prescriptions
  where id = order_row.prescription_id
    and patient_id = order_row.patient_id
  for share;
  if not found then raise exception 'care_signed_prescription_required' using errcode = '23514'; end if;

  select * into appointment_row
  from public.care_appointments
  where id = prescription_row.appointment_id
    and patient_id = order_row.patient_id
    and patient_state_code = order_row.patient_state_code
  for share;
  if not found then raise exception 'care_prescription_appointment_required' using errcode = '23514'; end if;
  if not public.care_prescription_context_current(
    order_row.patient_id,
    appointment_row.id
  ) then raise exception 'care_current_consent_and_state_required' using errcode = '23514'; end if;

  if not exists (
    select 1
    from public.care_pharmacy_operators operator
    join public.care_role_assignments assignment
      on assignment.user_id = operator.user_id
      and assignment.role = 'pharmacy_operations'
      and assignment.revoked_at is null
    where operator.pharmacy_id = order_row.assigned_pharmacy_id
      and operator.user_id = p_operator_user_id
      and operator.active and operator.revoked_at is null
  ) then raise exception 'care_assigned_pharmacy_operator_required' using errcode = '42501'; end if;
  if not public.care_pharmacy_ready(order_row.assigned_pharmacy_id, order_row.patient_state_code, p_occurred_at)
  then raise exception 'care_current_pharmacy_coverage_required' using errcode = '23514'; end if;
  if prescription_row.status <> 'signed'
    and p_action not in ('cancel', 'reject')
    and not (p_action = 'deliver' and order_row.status = 'shipped')
  then raise exception 'care_current_signed_prescription_required' using errcode = '23514'; end if;

  select * into replay_event
  from public.care_pharmacy_order_events
  where pharmacy_order_id = p_order_id
    and idempotency_key = p_idempotency_key
  for share;
  if found then
    if replay_event.actor_user_id <> p_operator_user_id
      or replay_event.actor_kind <> 'pharmacy_operator'
      or replay_event.action <> p_action
      or replay_event.clarification_reference is distinct from nullif(trim(p_clarification_reference), '')
      or replay_event.tracking_reference is distinct from nullif(trim(p_tracking_reference), '')
      or replay_event.expected_version <> p_expected_version
    then raise exception 'care_pharmacy_action_replay_mismatch' using errcode = '23514'; end if;
    return order_row;
  end if;

  if order_row.version <> p_expected_version
  then raise exception 'care_current_pharmacy_order_required' using errcode = '23514'; end if;

  prior_status := order_row.status;
  next_status := case p_action
    when 'receive' then 'received'
    when 'request_clarification' then 'clarification_requested'
    when 'accept' then 'accepted'
    when 'reject' then 'rejected'
    when 'dispense' then 'dispensed'
    when 'ship' then 'shipped'
    when 'deliver' then 'delivered'
    when 'cancel' then 'cancelled'
    else null end;
  if next_status is null or not (
    (order_row.status = 'pending_pharmacy' and next_status in ('received','rejected','cancelled'))
    or (order_row.status = 'received' and next_status in ('clarification_requested','accepted','rejected','cancelled'))
    or (order_row.status = 'clarification_requested' and next_status = 'cancelled')
    or (order_row.status = 'accepted' and next_status in ('clarification_requested','dispensed','cancelled'))
    or (order_row.status = 'dispensed' and next_status in ('shipped','cancelled'))
    or (order_row.status = 'shipped' and next_status = 'delivered')
  ) then raise exception 'care_invalid_pharmacy_transition' using errcode = '23514'; end if;
  if p_action = 'request_clarification' and nullif(trim(p_clarification_reference), '') is null
  then raise exception 'care_clarification_reference_required' using errcode = '23514'; end if;
  if p_action = 'dispense' and order_row.clarification_open
  then raise exception 'care_clarification_resolution_required' using errcode = '23514'; end if;
  if p_action = 'ship' and nullif(trim(p_tracking_reference), '') is null
  then raise exception 'care_tracking_reference_required' using errcode = '23514'; end if;

  update public.care_pharmacy_orders set
    status = next_status,
    clarification_open = case
      when next_status = 'clarification_requested' then true
      else clarification_open
    end,
    tracking_reference = case when next_status = 'shipped' then trim(p_tracking_reference) else tracking_reference end,
    version = version + 1,
    updated_at = p_occurred_at
  where id = p_order_id returning * into order_row;
  insert into public.care_pharmacy_order_events (
    pharmacy_order_id, patient_id, actor_user_id, actor_kind, action,
    from_status, to_status, clarification_reference, tracking_reference,
    expected_version, idempotency_key, occurred_at
  ) values (
    order_row.id, order_row.patient_id, p_operator_user_id, 'pharmacy_operator',
    p_action, prior_status,
    next_status, nullif(trim(p_clarification_reference), ''),
    nullif(trim(p_tracking_reference), ''), p_expected_version,
    p_idempotency_key, p_occurred_at
  );
  return order_row;
end;
$$;

create or replace function public.care_resolve_pharmacy_clarification(
  p_order_id uuid,
  p_resolver_user_id uuid,
  p_expected_version integer,
  p_resolution_reference text,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_pharmacy_orders
language plpgsql
security definer
set search_path = ''
as $$
declare
  order_row public.care_pharmacy_orders%rowtype;
  prescription_row public.care_prescriptions%rowtype;
  appointment_row public.care_appointments%rowtype;
  replay_event public.care_pharmacy_order_events%rowtype;
  resolver_kind text;
begin
  select * into order_row
  from public.care_pharmacy_orders
  where id = p_order_id
  for update;
  if not found then raise exception 'care_current_pharmacy_order_required' using errcode = '23514'; end if;

  select * into prescription_row
  from public.care_prescriptions
  where id = order_row.prescription_id
    and patient_id = order_row.patient_id
    and status = 'signed'
  for share;
  if not found then raise exception 'care_signed_prescription_required' using errcode = '23514'; end if;

  select * into appointment_row
  from public.care_appointments
  where id = prescription_row.appointment_id
    and patient_id = order_row.patient_id
    and patient_state_code = order_row.patient_state_code
  for share;
  if not found then raise exception 'care_prescription_appointment_required' using errcode = '23514'; end if;
  if not public.care_prescription_context_current(
    order_row.patient_id,
    appointment_row.id
  ) then raise exception 'care_current_consent_and_state_required' using errcode = '23514'; end if;

  if p_resolver_user_id = prescription_row.prescribing_clinician_user_id
    and public.care_clinician_ready(
      p_resolver_user_id,
      order_row.patient_state_code,
      p_occurred_at
    )
  then
    resolver_kind := 'human_clinician';
  elsif exists (
    select 1
    from public.care_role_assignments assignment
    where assignment.user_id = p_resolver_user_id
      and assignment.role = 'clinical_admin'
      and assignment.revoked_at is null
  ) then
    resolver_kind := 'clinical_admin';
  else
    raise exception 'care_clarification_resolver_required' using errcode = '42501';
  end if;

  select * into replay_event
  from public.care_pharmacy_order_events
  where pharmacy_order_id = p_order_id
    and idempotency_key = p_idempotency_key
  for share;
  if found then
    if replay_event.actor_user_id <> p_resolver_user_id
      or replay_event.actor_kind <> resolver_kind
      or replay_event.action <> 'clarification_resolved'
      or replay_event.from_status <> 'clarification_requested'
      or replay_event.to_status <> 'received'
      or replay_event.clarification_reference is distinct from nullif(trim(p_resolution_reference), '')
      or replay_event.expected_version <> p_expected_version
      or order_row.status <> 'received'
      or order_row.clarification_open
    then raise exception 'care_clarification_replay_mismatch' using errcode = '23514'; end if;
    return order_row;
  end if;

  if order_row.status <> 'clarification_requested'
    or not order_row.clarification_open
    or order_row.version <> p_expected_version
  then raise exception 'care_open_clarification_required' using errcode = '23514'; end if;
  if nullif(trim(p_resolution_reference), '') is null
  then raise exception 'care_clarification_resolution_reference_required' using errcode = '23514'; end if;

  update public.care_pharmacy_orders
  set status = 'received',
      clarification_open = false,
      version = version + 1,
      updated_at = p_occurred_at
  where id = p_order_id
  returning * into order_row;

  insert into public.care_pharmacy_order_events (
    pharmacy_order_id, patient_id, actor_user_id, actor_kind, action,
    from_status, to_status, clarification_reference, expected_version,
    idempotency_key,
    occurred_at
  ) values (
    order_row.id, order_row.patient_id, p_resolver_user_id, resolver_kind,
    'clarification_resolved', 'clarification_requested', 'received',
    trim(p_resolution_reference), p_expected_version, p_idempotency_key,
    p_occurred_at
  );
  return order_row;
end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'care_pharmacies', 'care_pharmacy_licenses', 'care_pharmacy_state_coverage',
    'care_pharmacy_operators', 'care_pharmacy_configuration_audit',
    'care_prescription_content_sources', 'care_prescriptions',
    'care_prescription_events', 'care_pharmacy_orders', 'care_pharmacy_order_events'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('alter table public.%I force row level security', table_name);
    execute format('revoke all on table public.%I from public, anon, authenticated', table_name);
    execute format('grant all on table public.%I to service_role', table_name);
  end loop;
end;
$$;

revoke all on function public.care_audit_pharmacy_configuration() from public, anon, authenticated;
revoke all on function public.care_pharmacy_ready(uuid, text, timestamptz) from public, anon, authenticated;
revoke all on function public.care_prescription_context_current(uuid, uuid) from public, anon, authenticated;
revoke all on function public.care_prescription_readiness(uuid, uuid, text, uuid, timestamptz) from public, anon, authenticated;
revoke all on function public.care_create_prescription_draft(uuid, uuid, uuid, text, text, text, text, text, integer, uuid, text, timestamptz) from public, anon, authenticated;
revoke all on function public.care_sign_prescription(uuid, uuid, integer, text, timestamptz) from public, anon, authenticated;
revoke all on function public.care_assign_pharmacy_order(uuid, uuid, uuid, text, timestamptz) from public, anon, authenticated;
revoke all on function public.care_apply_pharmacy_order_action(uuid, uuid, integer, text, text, text, text, timestamptz) from public, anon, authenticated;
revoke all on function public.care_resolve_pharmacy_clarification(uuid, uuid, integer, text, text, timestamptz) from public, anon, authenticated;

grant execute on function public.care_pharmacy_ready(uuid, text, timestamptz) to service_role;
grant execute on function public.care_prescription_readiness(uuid, uuid, text, uuid, timestamptz) to service_role;
grant execute on function public.care_create_prescription_draft(uuid, uuid, uuid, text, text, text, text, text, integer, uuid, text, timestamptz) to service_role;
grant execute on function public.care_sign_prescription(uuid, uuid, integer, text, timestamptz) to service_role;
grant execute on function public.care_assign_pharmacy_order(uuid, uuid, uuid, text, timestamptz) to service_role;
grant execute on function public.care_apply_pharmacy_order_action(uuid, uuid, integer, text, text, text, text, timestamptz) to service_role;
grant execute on function public.care_resolve_pharmacy_clarification(uuid, uuid, integer, text, text, timestamptz) to service_role;

insert into public.care_capabilities (capability_key, state)
values ('care', 'disabled')
on conflict (capability_key) do update
set state = 'disabled',
    approved_by = null,
    approved_at = null,
    updated_at = now();
