-- Xenios Care PR 1: capability, role, and access-audit foundation.
-- Additive and idempotent. This migration creates no patient, clinician,
-- prescription, pharmacy, instruction, supply, product, or Research records.

create extension if not exists pgcrypto;

create table if not exists public.care_capabilities (
  capability_key text primary key,
  state text not null default 'disabled'
    check (state in (
      'disabled',
      'pending_contract',
      'pending_coverage',
      'pending_credentials',
      'pending_content',
      'pending_pharmacy',
      'pending_clinicians',
      'pending_qa',
      'enabled'
    )),
  approved_by uuid null references auth.users(id),
  approved_at timestamptz null,
  updated_at timestamptz not null default now(),
  check (
    state <> 'enabled'
    or (approved_by is not null and approved_at is not null)
  )
);

insert into public.care_capabilities (capability_key, state)
values ('care', 'disabled')
on conflict (capability_key) do nothing;

create table if not exists public.care_role_assignments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in (
    'care_patient',
    'clinician',
    'clinical_admin',
    'pharmacy_operations',
    'lab_reviewer',
    'clinical_support',
    'care_security_admin'
  )),
  granted_by uuid not null references auth.users(id),
  granted_at timestamptz not null default now(),
  revoked_at timestamptz null,
  check (revoked_at is null or revoked_at >= granted_at)
);

-- Authentication/authorization metadata only. No request body, token,
-- clinical content, or patient record is permitted in this table.
create table if not exists public.care_access_audit (
  id bigint generated by default as identity primary key,
  actor_user_id uuid null references auth.users(id) on delete set null,
  permission text not null check (permission in (
    'care:read_self',
    'care:intake_self',
    'care:appointments_self',
    'care:message_self',
    'care:review_assigned',
    'care:prescribe_assigned',
    'care:administer',
    'care:pharmacy_assigned',
    'care:labs_assigned',
    'care:support_assigned',
    'care:security_audit'
  )),
  outcome text not null check (outcome in (
    'allowed',
    'unauthenticated',
    'forbidden'
  )),
  occurred_at timestamptz not null default now()
);

create unique index if not exists care_roles_user_active_idx
  on public.care_role_assignments (user_id, role)
  where revoked_at is null;

create index if not exists care_access_audit_time_idx
  on public.care_access_audit (occurred_at desc);

create or replace function public.care_has_role(required_roles text[])
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.care_role_assignments assignment
    where assignment.user_id = auth.uid()
      and assignment.revoked_at is null
      and assignment.role = any(required_roles)
  );
$$;

revoke all on function public.care_has_role(text[]) from public;
revoke all on function public.care_has_role(text[]) from anon;
grant execute on function public.care_has_role(text[]) to authenticated;

alter table public.care_capabilities enable row level security;
alter table public.care_capabilities force row level security;
alter table public.care_role_assignments enable row level security;
alter table public.care_role_assignments force row level security;
alter table public.care_access_audit enable row level security;
alter table public.care_access_audit force row level security;

revoke all on table public.care_capabilities from public, anon, authenticated;
revoke all on table public.care_role_assignments from public, anon, authenticated;
revoke all on table public.care_access_audit from public, anon, authenticated;

-- The application server uses the service role for capability, role, and
-- audit operations. Authenticated clients receive only the narrow,
-- security-admin read surfaces below.
grant select on table public.care_role_assignments to authenticated;
grant select on table public.care_access_audit to authenticated;

drop policy if exists care_security_roles_read on public.care_role_assignments;
create policy care_security_roles_read
  on public.care_role_assignments for select to authenticated
  using (public.care_has_role(array['care_security_admin']));

drop policy if exists care_security_access_audit_read on public.care_access_audit;
create policy care_security_access_audit_read
  on public.care_access_audit for select to authenticated
  using (public.care_has_role(array['care_security_admin']));

-- No browser policy is intentionally added for care_capabilities. No client
-- can insert, update, or delete any of these tables.
--
-- Rollback (manual and intentionally not executed):
-- 1. Set public.care_capabilities.state to 'disabled' and remove Care wiring.
-- 2. Preserve care_access_audit under the approved retention process.
-- 3. Drop the two read policies, then public.care_has_role(text[]).
-- 4. Drop care_access_audit, care_role_assignments, and care_capabilities.
-- 5. Do not cascade into auth or research objects.
