-- Xenios Care PR 2: location, state/clinician coverage, consent, waitlist,
-- and independently versioned clinical-intake foundation.
--
-- Additive and idempotent. This migration seeds no supported state, clinician,
-- consent document, intake definition, medical question, or patient record.
-- All browser roles are denied; production access is through the authorized
-- Care server boundary and Supabase service role.

create extension if not exists pgcrypto;

create table if not exists public.care_patients (
  id uuid primary key default gen_random_uuid(),
  user_id uuid null unique references auth.users(id) on delete set null,
  identity_state text not null default 'unverified'
    check (identity_state in ('unverified', 'pending', 'verified', 'rejected')),
  identity_verified_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    identity_state <> 'verified'
    or identity_verified_at is not null
  )
);

create table if not exists public.care_patient_locations (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  state_code text not null check (state_code ~ '^[A-Z]{2}$'),
  source text not null
    check (source in ('patient_attestation', 'approved_identity_provider')),
  attested_at timestamptz not null default now(),
  supersedes_location_id uuid null
    references public.care_patient_locations(id),
  idempotency_key text not null check (length(idempotency_key) between 8 and 128),
  unique (patient_id, idempotency_key),
  check (supersedes_location_id is null or supersedes_location_id <> id)
);

create table if not exists public.care_supported_states (
  state_code text primary key check (state_code ~ '^[A-Z]{2}$'),
  supported_state_active boolean not null default false,
  service_coverage_active boolean not null default false,
  waitlist_enabled boolean not null default false,
  approved_by uuid null references auth.users(id),
  approved_at timestamptz null,
  updated_at timestamptz not null default now(),
  check (
    not (supported_state_active or service_coverage_active or waitlist_enabled)
    or (approved_by is not null and approved_at is not null)
  ),
  check (not service_coverage_active or supported_state_active)
);

create table if not exists public.care_supported_state_audit (
  id bigint generated by default as identity primary key,
  state_code text not null check (state_code ~ '^[A-Z]{2}$'),
  action text not null check (action in ('insert', 'update', 'delete')),
  old_record jsonb null,
  new_record jsonb null,
  changed_by uuid null,
  occurred_at timestamptz not null default now()
);

create table if not exists public.care_clinician_state_coverage (
  id uuid primary key default gen_random_uuid(),
  clinician_user_id uuid not null references auth.users(id) on delete cascade,
  state_code text not null references public.care_supported_states(state_code),
  active boolean not null default false,
  verified_by uuid null references auth.users(id),
  verified_at timestamptz null,
  expires_at timestamptz null,
  created_at timestamptz not null default now(),
  check (
    not active
    or (verified_by is not null and verified_at is not null)
  ),
  check (expires_at is null or verified_at is null or expires_at > verified_at)
);

create unique index if not exists care_clinician_state_active_idx
  on public.care_clinician_state_coverage (clinician_user_id, state_code)
  where active;

create table if not exists public.care_clinician_coverage_audit (
  id bigint generated by default as identity primary key,
  coverage_id uuid not null,
  clinician_user_id uuid null,
  state_code text not null check (state_code ~ '^[A-Z]{2}$'),
  action text not null check (action in ('insert', 'update', 'delete')),
  old_record jsonb null,
  new_record jsonb null,
  changed_by uuid null,
  occurred_at timestamptz not null default now()
);

create or replace function public.care_validate_clinician_coverage()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.active and not exists (
    select 1
    from public.care_role_assignments assignment
    where assignment.user_id = new.clinician_user_id
      and assignment.role = 'clinician'
      and assignment.revoked_at is null
  ) then
    raise exception 'care_active_clinician_role_required'
      using errcode = '23514';
  end if;
  return new;
end;
$$;

revoke all on function public.care_validate_clinician_coverage()
  from public, anon, authenticated;

drop trigger if exists care_clinician_coverage_role_guard
  on public.care_clinician_state_coverage;
create trigger care_clinician_coverage_role_guard
before insert or update of clinician_user_id, active
on public.care_clinician_state_coverage
for each row execute function public.care_validate_clinician_coverage();

create or replace function public.care_active_clinician_count(
  p_state_code text,
  p_as_of timestamptz default now()
)
returns integer
language sql
stable
set search_path = ''
as $$
  select count(distinct coverage.clinician_user_id)::integer
  from public.care_clinician_state_coverage coverage
  join public.care_role_assignments assignment
    on assignment.user_id = coverage.clinician_user_id
    and assignment.role = 'clinician'
    and assignment.revoked_at is null
  where coverage.state_code = p_state_code
    and coverage.active
    and (coverage.expires_at is null or coverage.expires_at > p_as_of);
$$;

revoke all on function public.care_active_clinician_count(text, timestamptz)
  from public, anon, authenticated;
grant execute on function public.care_active_clinician_count(text, timestamptz)
  to service_role;

create or replace function public.care_audit_clinician_coverage_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  insert into public.care_clinician_coverage_audit (
    coverage_id,
    clinician_user_id,
    state_code,
    action,
    old_record,
    new_record,
    changed_by
  )
  values (
    coalesce(new.id, old.id),
    coalesce(new.clinician_user_id, old.clinician_user_id),
    coalesce(new.state_code, old.state_code),
    lower(tg_op),
    case when tg_op = 'INSERT' then null else to_jsonb(old) end,
    case when tg_op = 'DELETE' then null else to_jsonb(new) end,
    coalesce(new.verified_by, old.verified_by)
  );
  return coalesce(new, old);
end;
$$;

revoke all on function public.care_audit_clinician_coverage_change()
  from public, anon, authenticated;

drop trigger if exists care_clinician_coverage_audit_write
  on public.care_clinician_state_coverage;
create trigger care_clinician_coverage_audit_write
after insert or update or delete on public.care_clinician_state_coverage
for each row execute function public.care_audit_clinician_coverage_change();

create table if not exists public.care_consent_documents (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('telehealth', 'privacy_notice')),
  version text not null check (length(version) between 1 and 120),
  content_hash text not null check (length(content_hash) between 8 and 200),
  status text not null default 'draft'
    check (status in ('draft', 'approved', 'superseded')),
  approved_by uuid null references auth.users(id),
  approved_at timestamptz null,
  effective_at timestamptz null,
  superseded_at timestamptz null,
  created_at timestamptz not null default now(),
  unique (kind, version),
  unique (id, kind, version),
  check (
    status <> 'approved'
    or (
      approved_by is not null
      and approved_at is not null
      and effective_at is not null
    )
  ),
  check (
    status <> 'superseded'
    or superseded_at is not null
  )
);

create unique index if not exists care_consent_one_approved_kind_idx
  on public.care_consent_documents (kind)
  where status = 'approved';

create table if not exists public.care_consent_events (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  document_id uuid not null,
  kind text not null check (kind in ('telehealth', 'privacy_notice')),
  document_version text not null,
  action text not null check (action in ('granted', 'revoked')),
  idempotency_key text not null check (length(idempotency_key) between 8 and 128),
  occurred_at timestamptz not null default now(),
  foreign key (document_id, kind, document_version)
    references public.care_consent_documents(id, kind, version),
  unique (patient_id, idempotency_key)
);

create table if not exists public.care_eligibility_checks (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  location_id uuid null references public.care_patient_locations(id),
  outcome text not null check (outcome in (
    'unavailable',
    'waitlist_available',
    'consent_required',
    'intake_available'
  )),
  reason text not null check (reason in (
    'care_disabled',
    'location_required',
    'invalid_state',
    'unsupported_state',
    'service_unavailable',
    'clinician_coverage_unavailable',
    'identity_unverified',
    'telehealth_consent_required',
    'privacy_notice_required',
    'intake_foundation_ready'
  )),
  state_code text null check (state_code is null or state_code ~ '^[A-Z]{2}$'),
  care_eligibility_cleared boolean not null default false
    check (care_eligibility_cleared = false),
  evaluated_at timestamptz not null default now()
);

create table if not exists public.care_waitlist_events (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  state_code text not null check (state_code ~ '^[A-Z]{2}$'),
  action text not null check (action in ('joined', 'withdrawn')),
  idempotency_key text not null check (length(idempotency_key) between 8 and 128),
  occurred_at timestamptz not null default now(),
  unique (patient_id, idempotency_key)
);

create table if not exists public.care_intake_definitions (
  id uuid primary key default gen_random_uuid(),
  version text not null unique check (length(version) between 1 and 120),
  status text not null default 'draft'
    check (status in ('draft', 'approved', 'superseded')),
  schema_hash text not null check (length(schema_hash) between 8 and 200),
  fields jsonb not null default '[]'::jsonb
    check (jsonb_typeof(fields) = 'array'),
  approved_by uuid null references auth.users(id),
  approved_at timestamptz null,
  superseded_at timestamptz null,
  created_at timestamptz not null default now(),
  check (
    status <> 'approved'
    or (approved_by is not null and approved_at is not null)
  ),
  check (
    status <> 'superseded'
    or superseded_at is not null
  )
);

create unique index if not exists care_intake_one_approved_definition_idx
  on public.care_intake_definitions ((status))
  where status = 'approved';

create table if not exists public.care_intakes (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  definition_id uuid not null references public.care_intake_definitions(id),
  definition_version text not null,
  telehealth_consent_event_id uuid not null
    references public.care_consent_events(id),
  privacy_consent_event_id uuid not null
    references public.care_consent_events(id),
  status text not null default 'draft'
    check (status in ('draft', 'submitted')),
  version integer not null default 0 check (version >= 0),
  start_idempotency_key text not null
    check (length(start_idempotency_key) between 8 and 128),
  submit_idempotency_key text null
    check (
      submit_idempotency_key is null
      or length(submit_idempotency_key) between 8 and 128
    ),
  created_at timestamptz not null default now(),
  submitted_at timestamptz null,
  unique (id, patient_id),
  unique (patient_id, start_idempotency_key),
  check (
    (status = 'draft' and submitted_at is null and submit_idempotency_key is null)
    or
    (status = 'submitted' and submitted_at is not null and submit_idempotency_key is not null)
  )
);

create unique index if not exists care_intakes_one_draft_patient_idx
  on public.care_intakes (patient_id)
  where status = 'draft';

create unique index if not exists care_intakes_submit_idempotency_idx
  on public.care_intakes (patient_id, submit_idempotency_key)
  where submit_idempotency_key is not null;

create table if not exists public.care_intake_revisions (
  id uuid primary key default gen_random_uuid(),
  intake_id uuid not null,
  patient_id uuid not null,
  version integer not null check (version > 0),
  responses jsonb not null check (jsonb_typeof(responses) = 'object'),
  idempotency_key text not null check (length(idempotency_key) between 8 and 128),
  created_at timestamptz not null default now(),
  foreign key (intake_id, patient_id)
    references public.care_intakes(id, patient_id) on delete cascade,
  unique (intake_id, version),
  unique (patient_id, idempotency_key)
);

create index if not exists care_locations_patient_time_idx
  on public.care_patient_locations (patient_id, attested_at desc);
create index if not exists care_eligibility_patient_time_idx
  on public.care_eligibility_checks (patient_id, evaluated_at desc);
create index if not exists care_waitlist_patient_time_idx
  on public.care_waitlist_events (patient_id, occurred_at desc);
create index if not exists care_consent_patient_kind_time_idx
  on public.care_consent_events (patient_id, kind, occurred_at desc);
create index if not exists care_intake_revision_time_idx
  on public.care_intake_revisions (intake_id, version desc);

create or replace function public.care_reject_immutable_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'care_record_append_only'
    using errcode = '55000';
end;
$$;

revoke all on function public.care_reject_immutable_mutation()
  from public, anon, authenticated;

create or replace function public.care_audit_supported_state_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  insert into public.care_supported_state_audit (
    state_code,
    action,
    old_record,
    new_record,
    changed_by
  )
  values (
    coalesce(new.state_code, old.state_code),
    lower(tg_op),
    case when tg_op = 'INSERT' then null else to_jsonb(old) end,
    case when tg_op = 'DELETE' then null else to_jsonb(new) end,
    coalesce(new.approved_by, old.approved_by)
  );
  return coalesce(new, old);
end;
$$;

revoke all on function public.care_audit_supported_state_change()
  from public, anon, authenticated;

drop trigger if exists care_supported_state_audit_write
  on public.care_supported_states;
create trigger care_supported_state_audit_write
after insert or update or delete on public.care_supported_states
for each row execute function public.care_audit_supported_state_change();

drop trigger if exists care_supported_state_audit_append_only
  on public.care_supported_state_audit;
create trigger care_supported_state_audit_append_only
before update or delete on public.care_supported_state_audit
for each row execute function public.care_reject_immutable_mutation();

drop trigger if exists care_clinician_coverage_audit_append_only
  on public.care_clinician_coverage_audit;
create trigger care_clinician_coverage_audit_append_only
before update or delete on public.care_clinician_coverage_audit
for each row execute function public.care_reject_immutable_mutation();

drop trigger if exists care_locations_append_only
  on public.care_patient_locations;
create trigger care_locations_append_only
before update or delete on public.care_patient_locations
for each row execute function public.care_reject_immutable_mutation();

drop trigger if exists care_consent_events_append_only
  on public.care_consent_events;
create trigger care_consent_events_append_only
before update or delete on public.care_consent_events
for each row execute function public.care_reject_immutable_mutation();

drop trigger if exists care_eligibility_checks_append_only
  on public.care_eligibility_checks;
create trigger care_eligibility_checks_append_only
before update or delete on public.care_eligibility_checks
for each row execute function public.care_reject_immutable_mutation();

drop trigger if exists care_waitlist_events_append_only
  on public.care_waitlist_events;
create trigger care_waitlist_events_append_only
before update or delete on public.care_waitlist_events
for each row execute function public.care_reject_immutable_mutation();

drop trigger if exists care_intake_revisions_append_only
  on public.care_intake_revisions;
create trigger care_intake_revisions_append_only
before update or delete on public.care_intake_revisions
for each row execute function public.care_reject_immutable_mutation();

create or replace function public.care_guard_consent_document_version()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    if old.status <> 'draft' then
      raise exception 'care_approved_consent_document_immutable'
        using errcode = '55000';
    end if;
    return old;
  end if;

  if old.status = 'superseded' then
    if to_jsonb(new) is distinct from to_jsonb(old) then
      raise exception 'care_superseded_consent_document_immutable'
        using errcode = '55000';
    end if;
  elsif old.status = 'approved' then
    if new.status = 'superseded'
      and new.superseded_at is not null
      and new.id = old.id
      and new.kind = old.kind
      and new.version = old.version
      and new.content_hash = old.content_hash
      and new.approved_by is not distinct from old.approved_by
      and new.approved_at is not distinct from old.approved_at
      and new.effective_at is not distinct from old.effective_at
      and new.created_at = old.created_at then
      return new;
    end if;
    if to_jsonb(new) is distinct from to_jsonb(old) then
      raise exception 'care_approved_consent_document_immutable'
        using errcode = '55000';
    end if;
  end if;
  return new;
end;
$$;

revoke all on function public.care_guard_consent_document_version()
  from public, anon, authenticated;

drop trigger if exists care_consent_document_version_guard
  on public.care_consent_documents;
create trigger care_consent_document_version_guard
before update or delete on public.care_consent_documents
for each row execute function public.care_guard_consent_document_version();

create or replace function public.care_guard_intake_definition_version()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    if old.status <> 'draft' then
      raise exception 'care_approved_intake_definition_immutable'
        using errcode = '55000';
    end if;
    return old;
  end if;

  if old.status = 'superseded' then
    if to_jsonb(new) is distinct from to_jsonb(old) then
      raise exception 'care_superseded_intake_definition_immutable'
        using errcode = '55000';
    end if;
  elsif old.status = 'approved' then
    if new.status = 'superseded'
      and new.superseded_at is not null
      and new.id = old.id
      and new.version = old.version
      and new.schema_hash = old.schema_hash
      and new.fields = old.fields
      and new.approved_by is not distinct from old.approved_by
      and new.approved_at is not distinct from old.approved_at
      and new.created_at = old.created_at then
      return new;
    end if;
    if to_jsonb(new) is distinct from to_jsonb(old) then
      raise exception 'care_approved_intake_definition_immutable'
        using errcode = '55000';
    end if;
  end if;
  return new;
end;
$$;

revoke all on function public.care_guard_intake_definition_version()
  from public, anon, authenticated;

drop trigger if exists care_intake_definition_version_guard
  on public.care_intake_definitions;
create trigger care_intake_definition_version_guard
before update or delete on public.care_intake_definitions
for each row execute function public.care_guard_intake_definition_version();

create or replace function public.care_validate_intake_bindings()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  definition_row public.care_intake_definitions%rowtype;
  telehealth_event public.care_consent_events%rowtype;
  privacy_event public.care_consent_events%rowtype;
begin
  select * into definition_row
  from public.care_intake_definitions
  where id = new.definition_id;

  if definition_row.status <> 'approved'
    or definition_row.approved_at is null
    or definition_row.version <> new.definition_version then
    raise exception 'care_intake_definition_unavailable'
      using errcode = '23514';
  end if;

  select * into telehealth_event
  from public.care_consent_events
  where id = new.telehealth_consent_event_id;
  select * into privacy_event
  from public.care_consent_events
  where id = new.privacy_consent_event_id;

  if telehealth_event.patient_id <> new.patient_id
    or telehealth_event.kind <> 'telehealth'
    or telehealth_event.action <> 'granted' then
    raise exception 'care_telehealth_consent_mismatch'
      using errcode = '23514';
  end if;
  if privacy_event.patient_id <> new.patient_id
    or privacy_event.kind <> 'privacy_notice'
    or privacy_event.action <> 'granted' then
    raise exception 'care_privacy_consent_mismatch'
      using errcode = '23514';
  end if;
  return new;
end;
$$;

revoke all on function public.care_validate_intake_bindings()
  from public, anon, authenticated;

drop trigger if exists care_intake_binding_guard on public.care_intakes;
create trigger care_intake_binding_guard
before insert or update of definition_id, definition_version,
  telehealth_consent_event_id, privacy_consent_event_id
on public.care_intakes
for each row execute function public.care_validate_intake_bindings();

create or replace function public.care_intake_autosave(
  p_intake_id uuid,
  p_patient_id uuid,
  p_expected_version integer,
  p_responses jsonb,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_intake_revisions
language plpgsql
set search_path = ''
as $$
declare
  intake_row public.care_intakes%rowtype;
  revision_row public.care_intake_revisions%rowtype;
begin
  select * into intake_row
  from public.care_intakes
  where id = p_intake_id
  for update;

  if not found
    or intake_row.patient_id <> p_patient_id
    or intake_row.status <> 'draft' then
    raise exception 'care_intake_not_editable'
      using errcode = '42501';
  end if;
  if not exists (
    select 1
    from public.care_consent_events event
    join public.care_consent_documents document
      on document.id = event.document_id
     and document.kind = event.kind
     and document.version = event.document_version
    where event.id = intake_row.telehealth_consent_event_id
      and event.patient_id = p_patient_id
      and event.kind = 'telehealth'
      and event.action = 'granted'
      and document.status = 'approved'
      and document.approved_at is not null
      and document.effective_at is not null
      and event.id = (
        select latest.id
        from public.care_consent_events latest
        where latest.patient_id = p_patient_id
          and latest.kind = 'telehealth'
        order by latest.occurred_at desc, latest.id desc
        limit 1
      )
  ) then
    raise exception 'care_intake_consent_required'
      using errcode = '23514';
  end if;
  if not exists (
    select 1
    from public.care_consent_events event
    join public.care_consent_documents document
      on document.id = event.document_id
     and document.kind = event.kind
     and document.version = event.document_version
    where event.id = intake_row.privacy_consent_event_id
      and event.patient_id = p_patient_id
      and event.kind = 'privacy_notice'
      and event.action = 'granted'
      and document.status = 'approved'
      and document.approved_at is not null
      and document.effective_at is not null
      and event.id = (
        select latest.id
        from public.care_consent_events latest
        where latest.patient_id = p_patient_id
          and latest.kind = 'privacy_notice'
        order by latest.occurred_at desc, latest.id desc
        limit 1
      )
  ) then
    raise exception 'care_intake_consent_required'
      using errcode = '23514';
  end if;

  select * into revision_row
  from public.care_intake_revisions
  where patient_id = p_patient_id
    and idempotency_key = p_idempotency_key;
  if found then
    return revision_row;
  end if;

  if intake_row.version <> p_expected_version then
    raise exception 'care_intake_version_conflict'
      using errcode = '40001';
  end if;
  if not exists (
    select 1
    from public.care_intake_definitions definition
    where definition.id = intake_row.definition_id
      and definition.version = intake_row.definition_version
      and definition.status = 'approved'
      and definition.approved_at is not null
  ) then
    raise exception 'care_intake_definition_unavailable'
      using errcode = '23514';
  end if;
  if jsonb_typeof(p_responses) <> 'object' then
    raise exception 'care_intake_invalid_responses'
      using errcode = '22023';
  end if;

  insert into public.care_intake_revisions (
    intake_id,
    patient_id,
    version,
    responses,
    idempotency_key,
    created_at
  )
  values (
    p_intake_id,
    p_patient_id,
    intake_row.version + 1,
    p_responses,
    p_idempotency_key,
    p_occurred_at
  )
  returning * into revision_row;

  update public.care_intakes
  set version = revision_row.version
  where id = p_intake_id;

  return revision_row;
end;
$$;

create or replace function public.care_intake_submit(
  p_intake_id uuid,
  p_patient_id uuid,
  p_expected_version integer,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_intakes
language plpgsql
set search_path = ''
as $$
declare
  intake_row public.care_intakes%rowtype;
begin
  select * into intake_row
  from public.care_intakes
  where id = p_intake_id
  for update;

  if not found or intake_row.patient_id <> p_patient_id then
    raise exception 'care_intake_not_found'
      using errcode = '42501';
  end if;
  if not exists (
    select 1
    from public.care_consent_events event
    join public.care_consent_documents document
      on document.id = event.document_id
     and document.kind = event.kind
     and document.version = event.document_version
    where event.id = intake_row.telehealth_consent_event_id
      and event.patient_id = p_patient_id
      and event.kind = 'telehealth'
      and event.action = 'granted'
      and document.status = 'approved'
      and document.approved_at is not null
      and document.effective_at is not null
      and event.id = (
        select latest.id
        from public.care_consent_events latest
        where latest.patient_id = p_patient_id
          and latest.kind = 'telehealth'
        order by latest.occurred_at desc, latest.id desc
        limit 1
      )
  ) then
    raise exception 'care_intake_consent_required'
      using errcode = '23514';
  end if;
  if not exists (
    select 1
    from public.care_consent_events event
    join public.care_consent_documents document
      on document.id = event.document_id
     and document.kind = event.kind
     and document.version = event.document_version
    where event.id = intake_row.privacy_consent_event_id
      and event.patient_id = p_patient_id
      and event.kind = 'privacy_notice'
      and event.action = 'granted'
      and document.status = 'approved'
      and document.approved_at is not null
      and document.effective_at is not null
      and event.id = (
        select latest.id
        from public.care_consent_events latest
        where latest.patient_id = p_patient_id
          and latest.kind = 'privacy_notice'
        order by latest.occurred_at desc, latest.id desc
        limit 1
      )
  ) then
    raise exception 'care_intake_consent_required'
      using errcode = '23514';
  end if;
  if intake_row.status = 'submitted'
    and intake_row.submit_idempotency_key = p_idempotency_key then
    return intake_row;
  end if;
  if intake_row.status <> 'draft' then
    raise exception 'care_intake_not_submittable'
      using errcode = '55000';
  end if;
  if intake_row.version <> p_expected_version then
    raise exception 'care_intake_version_conflict'
      using errcode = '40001';
  end if;
  if not exists (
    select 1
    from public.care_intake_definitions definition
    where definition.id = intake_row.definition_id
      and definition.version = intake_row.definition_version
      and definition.status = 'approved'
      and definition.approved_at is not null
  ) then
    raise exception 'care_intake_definition_unavailable'
      using errcode = '23514';
  end if;
  if not exists (
    select 1
    from public.care_intake_revisions revision
    where revision.intake_id = p_intake_id
      and revision.patient_id = p_patient_id
      and revision.version = intake_row.version
  ) then
    raise exception 'care_intake_has_no_current_revision'
      using errcode = '23514';
  end if;

  update public.care_intakes
  set
    status = 'submitted',
    submit_idempotency_key = p_idempotency_key,
    submitted_at = p_occurred_at
  where id = p_intake_id
  returning * into intake_row;

  return intake_row;
end;
$$;

revoke all on function public.care_intake_autosave(
  uuid, uuid, integer, jsonb, text, timestamptz
) from public, anon, authenticated;
revoke all on function public.care_intake_submit(
  uuid, uuid, integer, text, timestamptz
) from public, anon, authenticated;
grant execute on function public.care_intake_autosave(
  uuid, uuid, integer, jsonb, text, timestamptz
) to service_role;
grant execute on function public.care_intake_submit(
  uuid, uuid, integer, text, timestamptz
) to service_role;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'care_patients',
    'care_patient_locations',
    'care_supported_states',
    'care_supported_state_audit',
    'care_clinician_state_coverage',
    'care_clinician_coverage_audit',
    'care_consent_documents',
    'care_consent_events',
    'care_eligibility_checks',
    'care_waitlist_events',
    'care_intake_definitions',
    'care_intakes',
    'care_intake_revisions'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('alter table public.%I force row level security', table_name);
    execute format(
      'revoke all on table public.%I from public, anon, authenticated',
      table_name
    );
  end loop;
end;
$$;

-- Rollback (manual and intentionally not executed):
-- 1. Keep public.care_capabilities.state = 'disabled' and remove PR 2 wiring.
-- 2. Preserve consent, eligibility, intake, and audit records under the
--    approved clinical retention/correction process.
-- 3. Revoke service_role execute on the clinician-count and two intake
--    functions.
-- 4. Drop PR 2 triggers and functions.
-- 5. Drop PR 2 tables in reverse dependency order only after verified export.
-- 6. Never cascade into auth, PR 1 Care objects, or Research objects.
