-- Xenios Care PR 5: patient instruction and supply-kit foundation.
--
-- Additive and idempotent. Seeds no instruction, source, device, supplier,
-- replacement, patient, prescription, pharmacy, or clinical fact. It invokes
-- no external action and leaves Care disabled.

create extension if not exists pgcrypto;

create table if not exists public.care_instruction_sources (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid null references public.care_patients(id) on delete cascade,
  prescription_id uuid null references public.care_prescriptions(id),
  kind text not null check (kind in (
    'pharmacy_label', 'pharmacy_information', 'clinician_direction',
    'manufacturer_material', 'general_education'
  )),
  version integer not null check (version > 0),
  source_reference text not null check (nullif(trim(source_reference), '') is not null),
  content_hash text not null check (nullif(trim(content_hash), '') is not null),
  content text not null check (nullif(trim(content), '') is not null),
  verification_state text not null default 'verified'
    check (verification_state in ('verified', 'rejected', 'expired', 'superseded')),
  verified_by uuid not null references auth.users(id),
  verified_at timestamptz not null,
  supersedes_source_id uuid null references public.care_instruction_sources(id),
  idempotency_key text not null check (length(idempotency_key) between 8 and 128),
  created_at timestamptz not null default now(),
  unique (verified_by, idempotency_key),
  check (
    (kind = 'general_education' and patient_id is null and prescription_id is null)
    or
    (kind <> 'general_education' and patient_id is not null and prescription_id is not null)
  ),
  check (supersedes_source_id is null or supersedes_source_id <> id)
);

create index if not exists care_instruction_sources_prescription_idx
  on public.care_instruction_sources (prescription_id, kind, created_at desc)
  where prescription_id is not null;

create table if not exists public.care_patient_instructions (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  prescription_id uuid not null references public.care_prescriptions(id),
  prescribing_clinician_user_id uuid not null references auth.users(id),
  status text not null default 'draft'
    check (status in ('draft', 'released', 'superseded', 'withdrawn')),
  instruction_content text not null
    check (nullif(trim(instruction_content), '') is not null),
  version integer not null default 0 check (version >= 0),
  acknowledged_version integer null check (acknowledged_version is null or acknowledged_version >= 0),
  supersedes_instruction_id uuid null references public.care_patient_instructions(id),
  create_idempotency_key text not null check (length(create_idempotency_key) between 8 and 128),
  released_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (prescribing_clinician_user_id, create_idempotency_key),
  check (
    (status = 'draft' and released_at is null)
    or (status in ('released', 'superseded', 'withdrawn') and released_at is not null)
  ),
  check (supersedes_instruction_id is null or supersedes_instruction_id <> id)
);

create unique index if not exists care_patient_instruction_active_idx
  on public.care_patient_instructions (patient_id, prescription_id)
  where status = 'released';

create table if not exists public.care_instruction_source_links (
  instruction_id uuid not null references public.care_patient_instructions(id) on delete cascade,
  source_id uuid not null references public.care_instruction_sources(id),
  source_kind text not null check (source_kind in (
    'pharmacy_label', 'pharmacy_information', 'clinician_direction',
    'manufacturer_material'
  )),
  created_at timestamptz not null default now(),
  primary key (instruction_id, source_id),
  unique (instruction_id, source_kind)
);

create table if not exists public.care_instruction_events (
  id bigint generated by default as identity primary key,
  instruction_id uuid not null references public.care_patient_instructions(id) on delete cascade,
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id),
  actor_kind text not null check (actor_kind in ('human_clinician', 'clinical_admin')),
  action text not null check (action in ('drafted', 'released', 'superseded', 'withdrawn')),
  from_status text null,
  to_status text not null,
  idempotency_key text not null check (length(idempotency_key) between 8 and 128),
  occurred_at timestamptz not null,
  unique (instruction_id, idempotency_key)
);

create table if not exists public.care_instruction_acknowledgments (
  id bigint generated by default as identity primary key,
  instruction_id uuid not null references public.care_patient_instructions(id) on delete cascade,
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  instruction_version integer not null check (instruction_version > 0),
  idempotency_key text not null check (length(idempotency_key) between 8 and 128),
  acknowledged_at timestamptz not null,
  unique (patient_id, idempotency_key),
  unique (instruction_id, patient_id, instruction_version)
);

create table if not exists public.care_supply_sources (
  id uuid primary key default gen_random_uuid(),
  legal_name text null,
  relationship_reference text null,
  support_reference text null,
  verification_state text not null default 'missing'
    check (verification_state in (
      'missing', 'entered', 'under_review', 'verified', 'rejected',
      'expired', 'superseded'
    )),
  verified_by uuid null references auth.users(id),
  verified_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    verification_state <> 'verified'
    or (
      nullif(trim(legal_name), '') is not null
      and nullif(trim(relationship_reference), '') is not null
      and nullif(trim(support_reference), '') is not null
      and verified_by is not null and verified_at is not null
    )
  )
);

create table if not exists public.care_supply_configuration_audit (
  id bigint generated by default as identity primary key,
  supply_source_id uuid not null,
  action text not null check (action in ('insert', 'update', 'delete')),
  old_record jsonb null,
  new_record jsonb null,
  occurred_at timestamptz not null default now()
);

create table if not exists public.care_supply_kits (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  prescription_id uuid not null references public.care_prescriptions(id),
  instruction_id uuid not null references public.care_patient_instructions(id),
  supply_source_id uuid not null references public.care_supply_sources(id),
  status text not null default 'verified'
    check (status in ('draft', 'verified', 'released', 'superseded', 'withdrawn')),
  product_specific_device text not null
    check (nullif(trim(product_specific_device), '') is not null),
  replacement_cadence text not null
    check (nullif(trim(replacement_cadence), '') is not null),
  version integer not null default 0 check (version >= 0),
  supersedes_supply_kit_id uuid null references public.care_supply_kits(id),
  create_idempotency_key text not null check (length(create_idempotency_key) between 8 and 128),
  released_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (prescription_id, create_idempotency_key),
  check (
    (status in ('draft', 'verified') and released_at is null)
    or (status in ('released', 'superseded', 'withdrawn') and released_at is not null)
  ),
  check (supersedes_supply_kit_id is null or supersedes_supply_kit_id <> id)
);

create unique index if not exists care_supply_kit_active_idx
  on public.care_supply_kits (patient_id, prescription_id)
  where status = 'released';

create table if not exists public.care_supply_kit_events (
  id bigint generated by default as identity primary key,
  supply_kit_id uuid not null references public.care_supply_kits(id) on delete cascade,
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id),
  actor_kind text not null check (actor_kind in ('clinical_admin', 'pharmacy_operator')),
  action text not null check (action in ('verified', 'released', 'superseded', 'withdrawn')),
  from_status text null,
  to_status text not null,
  idempotency_key text not null check (length(idempotency_key) between 8 and 128),
  occurred_at timestamptz not null,
  unique (supply_kit_id, idempotency_key)
);

create table if not exists public.care_supply_replacements (
  id uuid primary key default gen_random_uuid(),
  supply_kit_id uuid not null references public.care_supply_kits(id),
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  status text not null default 'requested'
    check (status in ('requested', 'approved', 'fulfilled', 'declined', 'cancelled')),
  version integer not null default 0 check (version >= 0),
  request_idempotency_key text not null check (length(request_idempotency_key) between 8 and 128),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (patient_id, request_idempotency_key)
);

create unique index if not exists care_supply_replacement_open_idx
  on public.care_supply_replacements (supply_kit_id, patient_id)
  where status in ('requested', 'approved');

create table if not exists public.care_supply_replacement_events (
  id bigint generated by default as identity primary key,
  replacement_id uuid not null references public.care_supply_replacements(id) on delete cascade,
  patient_id uuid not null references public.care_patients(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id),
  actor_kind text not null check (actor_kind in ('care_patient', 'clinical_admin', 'pharmacy_operator')),
  action text not null check (action in ('requested', 'approve', 'fulfill', 'decline', 'cancel')),
  from_status text null,
  to_status text not null,
  idempotency_key text not null check (length(idempotency_key) between 8 and 128),
  occurred_at timestamptz not null,
  unique (replacement_id, idempotency_key)
);

alter table public.care_supply_replacement_events
  drop constraint if exists care_supply_replacement_events_action_check;
alter table public.care_supply_replacement_events
  add constraint care_supply_replacement_events_action_check
  check (action in ('requested', 'approve', 'fulfill', 'decline', 'cancel'));

create or replace function public.care_audit_supply_source()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.care_supply_configuration_audit (
    supply_source_id, action, old_record, new_record
  ) values (
    coalesce(new.id, old.id), lower(tg_op),
    case when tg_op <> 'INSERT' then to_jsonb(old) end,
    case when tg_op <> 'DELETE' then to_jsonb(new) end
  );
  return coalesce(new, old);
end;
$$;

drop trigger if exists care_supply_sources_audit_write on public.care_supply_sources;
create trigger care_supply_sources_audit_write
after insert or update or delete on public.care_supply_sources
for each row execute function public.care_audit_supply_source();

do $$
declare table_name text; trigger_name text;
begin
  foreach table_name in array array[
    'care_instruction_sources', 'care_instruction_source_links',
    'care_instruction_events', 'care_instruction_acknowledgments',
    'care_supply_configuration_audit', 'care_supply_kit_events',
    'care_supply_replacement_events'
  ]
  loop
    trigger_name := table_name || '_append_only';
    execute format('drop trigger if exists %I on public.%I', trigger_name, table_name);
    execute format(
      'create trigger %I before update or delete on public.%I
       for each row execute function public.care_reject_immutable_mutation()',
      trigger_name, table_name
    );
  end loop;
end;
$$;

create or replace function public.care_create_instruction_source(
  p_patient_id uuid,
  p_prescription_id uuid,
  p_kind text,
  p_source_reference text,
  p_content_hash text,
  p_content text,
  p_actor_user_id uuid,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_instruction_sources
language plpgsql
security definer
set search_path = ''
as $$
declare
  source_row public.care_instruction_sources%rowtype;
  prescription_row public.care_prescriptions%rowtype;
  latest_source public.care_instruction_sources%rowtype;
begin
  select * into source_row from public.care_instruction_sources
  where verified_by = p_actor_user_id and idempotency_key = p_idempotency_key;
  if found then return source_row; end if;
  if p_kind not in (
    'pharmacy_label', 'pharmacy_information', 'clinician_direction',
    'manufacturer_material', 'general_education'
  ) then raise exception 'care_instruction_source_kind_invalid' using errcode='23514'; end if;
  if exists (
    select 1 from unnest(array[p_source_reference,p_content_hash,p_content]) value
    where nullif(trim(value), '') is null
  ) then raise exception 'care_instruction_source_content_required' using errcode='23514'; end if;

  if p_kind = 'general_education' then
    if p_patient_id is not null or p_prescription_id is not null then
      raise exception 'care_general_education_must_be_unbound' using errcode='23514';
    end if;
    if not exists (
      select 1 from public.care_role_assignments
      where user_id=p_actor_user_id and role='clinical_admin' and revoked_at is null
    ) then raise exception 'care_clinical_admin_required' using errcode='42501'; end if;
  else
    select * into prescription_row from public.care_prescriptions
    where id=p_prescription_id and patient_id=p_patient_id and status='signed';
    if not found then raise exception 'care_signed_patient_prescription_required' using errcode='23514'; end if;
    if p_kind = 'clinician_direction' then
      if prescription_row.prescribing_clinician_user_id <> p_actor_user_id
        or not public.care_clinician_ready(
          p_actor_user_id,
          (select patient_state_code from public.care_appointments where id=prescription_row.appointment_id),
          p_occurred_at
        )
      then raise exception 'care_assigned_human_clinician_required' using errcode='42501'; end if;
    elsif p_kind in ('pharmacy_label','pharmacy_information') then
      if not exists (
        select 1 from public.care_pharmacy_orders pharmacy_order
        join public.care_pharmacy_operators operator
          on operator.pharmacy_id=pharmacy_order.assigned_pharmacy_id
          and operator.user_id=p_actor_user_id
          and operator.active and operator.revoked_at is null
        join public.care_role_assignments assignment
          on assignment.user_id=operator.user_id
          and assignment.role='pharmacy_operations'
          and assignment.revoked_at is null
        where pharmacy_order.prescription_id=p_prescription_id
          and pharmacy_order.patient_id=p_patient_id
          and pharmacy_order.status in ('accepted','dispensed','shipped','delivered')
      ) then raise exception 'care_assigned_pharmacy_operator_required' using errcode='42501'; end if;
    elsif p_kind = 'manufacturer_material' and not exists (
      select 1 from public.care_role_assignments
      where user_id=p_actor_user_id and role='clinical_admin' and revoked_at is null
    ) then raise exception 'care_clinical_admin_required' using errcode='42501'; end if;
  end if;

  select * into latest_source from public.care_instruction_sources
  where kind=p_kind and patient_id is not distinct from p_patient_id
    and prescription_id is not distinct from p_prescription_id
    and verification_state='verified'
  order by version desc, created_at desc limit 1;

  insert into public.care_instruction_sources (
    patient_id,prescription_id,kind,version,source_reference,content_hash,content,
    verified_by,verified_at,supersedes_source_id,idempotency_key,created_at
  ) values (
    p_patient_id,p_prescription_id,p_kind,coalesce(latest_source.version,0)+1,
    trim(p_source_reference),trim(p_content_hash),trim(p_content),
    p_actor_user_id,p_occurred_at,latest_source.id,p_idempotency_key,p_occurred_at
  ) returning * into source_row;
  return source_row;
end;
$$;

create or replace function public.care_create_patient_instruction_draft(
  p_patient_id uuid,
  p_prescription_id uuid,
  p_clinician_user_id uuid,
  p_instruction_content text,
  p_pharmacy_label_source_id uuid,
  p_pharmacy_information_source_id uuid,
  p_clinician_direction_source_id uuid,
  p_manufacturer_material_source_id uuid,
  p_supersedes_instruction_id uuid,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_patient_instructions
language plpgsql
security definer
set search_path = ''
as $$
declare
  prescription_row public.care_prescriptions%rowtype;
  instruction_row public.care_patient_instructions%rowtype;
  source_record record;
begin
  select * into instruction_row from public.care_patient_instructions
  where prescribing_clinician_user_id=p_clinician_user_id
    and create_idempotency_key=p_idempotency_key;
  if found then return instruction_row; end if;
  select * into prescription_row from public.care_prescriptions
  where id=p_prescription_id and patient_id=p_patient_id and status='signed'
    and prescribing_clinician_user_id=p_clinician_user_id;
  if not found then raise exception 'care_signed_assigned_prescription_required' using errcode='23514'; end if;
  if not public.care_clinician_ready(
    p_clinician_user_id,
    (select patient_state_code from public.care_appointments where id=prescription_row.appointment_id),
    p_occurred_at
  ) then raise exception 'care_current_clinician_coverage_required' using errcode='42501'; end if;
  if nullif(trim(p_instruction_content), '') is null
  then raise exception 'care_patient_instruction_content_required' using errcode='23514'; end if;

  for source_record in
    select * from (values
      (p_pharmacy_label_source_id,'pharmacy_label'),
      (p_pharmacy_information_source_id,'pharmacy_information'),
      (p_clinician_direction_source_id,'clinician_direction'),
      (p_manufacturer_material_source_id,'manufacturer_material')
    ) expected(source_id,source_kind)
  loop
    if not exists (
      select 1 from public.care_instruction_sources source
      where source.id=source_record.source_id
        and source.kind=source_record.source_kind
        and source.patient_id=p_patient_id
        and source.prescription_id=p_prescription_id
        and source.verification_state='verified'
        and not exists (
          select 1 from public.care_instruction_sources newer
          where newer.supersedes_source_id=source.id
            and newer.verification_state='verified'
        )
    ) then raise exception 'care_current_verified_instruction_sources_required' using errcode='23514'; end if;
  end loop;

  if p_supersedes_instruction_id is not null and not exists (
    select 1 from public.care_patient_instructions prior
    where prior.id=p_supersedes_instruction_id and prior.patient_id=p_patient_id
      and prior.prescription_id=p_prescription_id and prior.status='released'
  ) then raise exception 'care_valid_instruction_supersession_required' using errcode='23514'; end if;

  insert into public.care_patient_instructions (
    patient_id,prescription_id,prescribing_clinician_user_id,instruction_content,
    supersedes_instruction_id,create_idempotency_key,created_at,updated_at
  ) values (
    p_patient_id,p_prescription_id,p_clinician_user_id,trim(p_instruction_content),
    p_supersedes_instruction_id,p_idempotency_key,p_occurred_at,p_occurred_at
  ) returning * into instruction_row;
  insert into public.care_instruction_source_links (instruction_id,source_id,source_kind)
  values
    (instruction_row.id,p_pharmacy_label_source_id,'pharmacy_label'),
    (instruction_row.id,p_pharmacy_information_source_id,'pharmacy_information'),
    (instruction_row.id,p_clinician_direction_source_id,'clinician_direction'),
    (instruction_row.id,p_manufacturer_material_source_id,'manufacturer_material');
  insert into public.care_instruction_events (
    instruction_id,patient_id,actor_user_id,actor_kind,action,to_status,
    idempotency_key,occurred_at
  ) values (
    instruction_row.id,p_patient_id,p_clinician_user_id,'human_clinician',
    'drafted','draft',p_idempotency_key,p_occurred_at
  );
  return instruction_row;
end;
$$;

create or replace function public.care_release_patient_instruction(
  p_instruction_id uuid,
  p_clinician_user_id uuid,
  p_expected_version integer,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_patient_instructions
language plpgsql
security definer
set search_path = ''
as $$
declare instruction_row public.care_patient_instructions%rowtype;
begin
  if exists (
    select 1 from public.care_instruction_events
    where instruction_id=p_instruction_id and idempotency_key=p_idempotency_key
  ) then
    select * into instruction_row from public.care_patient_instructions where id=p_instruction_id;
    return instruction_row;
  end if;
  select * into instruction_row from public.care_patient_instructions
  where id=p_instruction_id and prescribing_clinician_user_id=p_clinician_user_id
    and status='draft' and version=p_expected_version;
  if not found then raise exception 'care_releasable_assigned_instruction_required' using errcode='23514'; end if;
  if not exists (
    select 1 from public.care_prescriptions prescription
    where prescription.id=instruction_row.prescription_id
      and prescription.patient_id=instruction_row.patient_id
      and prescription.status='signed'
      and prescription.prescribing_clinician_user_id=p_clinician_user_id
      and public.care_clinician_ready(
        p_clinician_user_id,
        (select patient_state_code from public.care_appointments where id=prescription.appointment_id),
        p_occurred_at
      )
  ) then raise exception 'care_current_signed_assigned_prescription_required' using errcode='23514'; end if;
  if (
    select count(*) from public.care_instruction_source_links link
    join public.care_instruction_sources source on source.id=link.source_id
    where link.instruction_id=p_instruction_id
      and source.patient_id=instruction_row.patient_id
      and source.prescription_id=instruction_row.prescription_id
      and source.verification_state='verified'
      and not exists (
        select 1 from public.care_instruction_sources newer
        where newer.supersedes_source_id=source.id and newer.verification_state='verified'
      )
  ) <> 4 then raise exception 'care_current_verified_instruction_sources_required' using errcode='23514'; end if;

  if instruction_row.supersedes_instruction_id is not null then
    update public.care_patient_instructions set status='superseded',
      version=version+1,updated_at=p_occurred_at
    where id=instruction_row.supersedes_instruction_id and status='released';
    insert into public.care_instruction_events (
      instruction_id,patient_id,actor_user_id,actor_kind,action,from_status,
      to_status,idempotency_key,occurred_at
    ) values (
      instruction_row.supersedes_instruction_id,instruction_row.patient_id,
      p_clinician_user_id,'human_clinician','superseded','released','superseded',
      p_idempotency_key||':prior',p_occurred_at
    );
  end if;
  update public.care_patient_instructions set status='released',
    released_at=p_occurred_at,version=version+1,updated_at=p_occurred_at
  where id=p_instruction_id returning * into instruction_row;
  insert into public.care_instruction_events (
    instruction_id,patient_id,actor_user_id,actor_kind,action,from_status,
    to_status,idempotency_key,occurred_at
  ) values (
    instruction_row.id,instruction_row.patient_id,p_clinician_user_id,
    'human_clinician','released','draft','released',p_idempotency_key,p_occurred_at
  );
  return instruction_row;
end;
$$;

create or replace function public.care_acknowledge_patient_instruction(
  p_instruction_id uuid,
  p_patient_id uuid,
  p_instruction_version integer,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_patient_instructions
language plpgsql
security definer
set search_path = ''
as $$
declare instruction_row public.care_patient_instructions%rowtype;
begin
  if exists (
    select 1 from public.care_instruction_acknowledgments
    where patient_id=p_patient_id and idempotency_key=p_idempotency_key
  ) then
    select * into instruction_row from public.care_patient_instructions where id=p_instruction_id;
    return instruction_row;
  end if;
  select * into instruction_row from public.care_patient_instructions
  where id=p_instruction_id and patient_id=p_patient_id and status='released'
    and version=p_instruction_version;
  if not found then raise exception 'care_current_released_patient_instruction_required' using errcode='42501'; end if;
  insert into public.care_instruction_acknowledgments (
    instruction_id,patient_id,instruction_version,idempotency_key,acknowledged_at
  ) values (
    p_instruction_id,p_patient_id,p_instruction_version,p_idempotency_key,p_occurred_at
  );
  update public.care_patient_instructions
    set acknowledged_version=p_instruction_version,updated_at=p_occurred_at
    where id=p_instruction_id returning * into instruction_row;
  return instruction_row;
end;
$$;

create or replace function public.care_create_supply_kit(
  p_patient_id uuid,
  p_prescription_id uuid,
  p_instruction_id uuid,
  p_supply_source_id uuid,
  p_product_specific_device text,
  p_replacement_cadence text,
  p_admin_user_id uuid,
  p_supersedes_supply_kit_id uuid,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_supply_kits
language plpgsql
security definer
set search_path = ''
as $$
declare kit_row public.care_supply_kits%rowtype;
begin
  select * into kit_row from public.care_supply_kits
  where prescription_id=p_prescription_id and create_idempotency_key=p_idempotency_key;
  if found then return kit_row; end if;
  if not exists (
    select 1 from public.care_role_assignments
    where user_id=p_admin_user_id and role='clinical_admin' and revoked_at is null
  ) then raise exception 'care_clinical_admin_required' using errcode='42501'; end if;
  if not exists (
    select 1 from public.care_prescriptions prescription
    join public.care_patient_instructions instruction
      on instruction.id=p_instruction_id
      and instruction.patient_id=prescription.patient_id
      and instruction.prescription_id=prescription.id
      and instruction.status='released'
    join public.care_supply_sources source
      on source.id=p_supply_source_id and source.verification_state='verified'
    where prescription.id=p_prescription_id and prescription.patient_id=p_patient_id
      and prescription.status='signed'
  ) then raise exception 'care_released_instruction_and_verified_supply_source_required' using errcode='23514'; end if;
  if nullif(trim(p_product_specific_device),'') is null
    or nullif(trim(p_replacement_cadence),'') is null
  then raise exception 'care_product_specific_supply_details_required' using errcode='23514'; end if;
  if p_supersedes_supply_kit_id is not null and not exists (
    select 1 from public.care_supply_kits prior
    where prior.id=p_supersedes_supply_kit_id and prior.patient_id=p_patient_id
      and prior.prescription_id=p_prescription_id and prior.status='released'
  ) then raise exception 'care_valid_supply_supersession_required' using errcode='23514'; end if;
  insert into public.care_supply_kits (
    patient_id,prescription_id,instruction_id,supply_source_id,status,
    product_specific_device,replacement_cadence,supersedes_supply_kit_id,
    create_idempotency_key,created_at,updated_at
  ) values (
    p_patient_id,p_prescription_id,p_instruction_id,p_supply_source_id,'verified',
    trim(p_product_specific_device),trim(p_replacement_cadence),
    p_supersedes_supply_kit_id,p_idempotency_key,p_occurred_at,p_occurred_at
  ) returning * into kit_row;
  insert into public.care_supply_kit_events (
    supply_kit_id,patient_id,actor_user_id,actor_kind,action,to_status,
    idempotency_key,occurred_at
  ) values (
    kit_row.id,p_patient_id,p_admin_user_id,'clinical_admin','verified','verified',
    p_idempotency_key,p_occurred_at
  );
  return kit_row;
end;
$$;

create or replace function public.care_save_supply_source(
  p_supply_source_id uuid,
  p_legal_name text,
  p_relationship_reference text,
  p_support_reference text,
  p_verification_state text,
  p_admin_user_id uuid,
  p_occurred_at timestamptz
)
returns public.care_supply_sources
language plpgsql
security definer
set search_path = ''
as $$
declare source_row public.care_supply_sources%rowtype;
begin
  if not exists (
    select 1 from public.care_role_assignments
    where user_id=p_admin_user_id and role='clinical_admin' and revoked_at is null
  ) then raise exception 'care_clinical_admin_required' using errcode='42501'; end if;
  if p_verification_state not in (
    'missing','entered','under_review','verified','rejected','expired','superseded'
  ) then raise exception 'care_supply_source_state_invalid' using errcode='23514'; end if;
  if p_supply_source_id is null then
    insert into public.care_supply_sources (
      legal_name,relationship_reference,support_reference,verification_state,
      verified_by,verified_at,created_at,updated_at
    ) values (
      p_legal_name,p_relationship_reference,p_support_reference,p_verification_state,
      case when p_verification_state='verified' then p_admin_user_id end,
      case when p_verification_state='verified' then p_occurred_at end,
      p_occurred_at,p_occurred_at
    ) returning * into source_row;
  else
    update public.care_supply_sources set
      legal_name=p_legal_name,
      relationship_reference=p_relationship_reference,
      support_reference=p_support_reference,
      verification_state=p_verification_state,
      verified_by=case when p_verification_state='verified' then p_admin_user_id end,
      verified_at=case when p_verification_state='verified' then p_occurred_at end,
      updated_at=p_occurred_at
    where id=p_supply_source_id
    returning * into source_row;
    if not found then
      raise exception 'care_supply_source_required' using errcode='23503';
    end if;
  end if;
  return source_row;
end;
$$;

create or replace function public.care_release_supply_kit(
  p_supply_kit_id uuid,
  p_admin_user_id uuid,
  p_expected_version integer,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_supply_kits
language plpgsql
security definer
set search_path = ''
as $$
declare kit_row public.care_supply_kits%rowtype;
begin
  if exists (
    select 1 from public.care_supply_kit_events
    where supply_kit_id=p_supply_kit_id and idempotency_key=p_idempotency_key
  ) then
    select * into kit_row from public.care_supply_kits where id=p_supply_kit_id;
    return kit_row;
  end if;
  if not exists (
    select 1 from public.care_role_assignments
    where user_id=p_admin_user_id and role='clinical_admin' and revoked_at is null
  ) then raise exception 'care_clinical_admin_required' using errcode='42501'; end if;
  select * into kit_row from public.care_supply_kits
  where id=p_supply_kit_id and status='verified' and version=p_expected_version;
  if not found then raise exception 'care_releasable_verified_supply_kit_required' using errcode='23514'; end if;
  if not exists (
    select 1 from public.care_prescriptions prescription
    join public.care_patient_instructions instruction
      on instruction.id=kit_row.instruction_id and instruction.status='released'
    join public.care_supply_sources source
      on source.id=kit_row.supply_source_id and source.verification_state='verified'
    where prescription.id=kit_row.prescription_id
      and prescription.patient_id=kit_row.patient_id and prescription.status='signed'
  ) then raise exception 'care_current_supply_release_inputs_required' using errcode='23514'; end if;
  if kit_row.supersedes_supply_kit_id is not null then
    update public.care_supply_kits set status='superseded',version=version+1,updated_at=p_occurred_at
      where id=kit_row.supersedes_supply_kit_id and status='released';
    insert into public.care_supply_kit_events (
      supply_kit_id,patient_id,actor_user_id,actor_kind,action,from_status,
      to_status,idempotency_key,occurred_at
    ) values (
      kit_row.supersedes_supply_kit_id,kit_row.patient_id,p_admin_user_id,
      'clinical_admin','superseded','released','superseded',
      p_idempotency_key||':prior',p_occurred_at
    );
  end if;
  update public.care_supply_kits set status='released',released_at=p_occurred_at,
    version=version+1,updated_at=p_occurred_at
    where id=p_supply_kit_id returning * into kit_row;
  insert into public.care_supply_kit_events (
    supply_kit_id,patient_id,actor_user_id,actor_kind,action,from_status,
    to_status,idempotency_key,occurred_at
  ) values (
    kit_row.id,kit_row.patient_id,p_admin_user_id,'clinical_admin',
    'released','verified','released',p_idempotency_key,p_occurred_at
  );
  return kit_row;
end;
$$;

create or replace function public.care_request_supply_replacement(
  p_supply_kit_id uuid,
  p_patient_id uuid,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_supply_replacements
language plpgsql
security definer
set search_path = ''
as $$
declare replacement_row public.care_supply_replacements%rowtype;
begin
  select * into replacement_row from public.care_supply_replacements
    where patient_id=p_patient_id and request_idempotency_key=p_idempotency_key;
  if found then return replacement_row; end if;
  if not exists (
    select 1 from public.care_supply_kits
    where id=p_supply_kit_id and patient_id=p_patient_id and status='released'
  ) then raise exception 'care_released_patient_supply_kit_required' using errcode='42501'; end if;
  insert into public.care_supply_replacements (
    supply_kit_id,patient_id,request_idempotency_key,created_at,updated_at
  ) values (p_supply_kit_id,p_patient_id,p_idempotency_key,p_occurred_at,p_occurred_at)
  returning * into replacement_row;
  insert into public.care_supply_replacement_events (
    replacement_id,patient_id,actor_user_id,actor_kind,action,to_status,
    idempotency_key,occurred_at
  ) values (
    replacement_row.id,p_patient_id,
    (select user_id from public.care_patients where id=p_patient_id),
    'care_patient','requested','requested',p_idempotency_key,p_occurred_at
  );
  return replacement_row;
end;
$$;

create or replace function public.care_apply_supply_replacement_action(
  p_replacement_id uuid,
  p_actor_user_id uuid,
  p_expected_version integer,
  p_action text,
  p_idempotency_key text,
  p_occurred_at timestamptz
)
returns public.care_supply_replacements
language plpgsql
security definer
set search_path = ''
as $$
declare
  replacement_row public.care_supply_replacements%rowtype;
  kit_row public.care_supply_kits%rowtype;
  actor_kind text;
  next_status text;
begin
  if exists (
    select 1 from public.care_supply_replacement_events
    where replacement_id=p_replacement_id and idempotency_key=p_idempotency_key
  ) then
    select * into replacement_row from public.care_supply_replacements where id=p_replacement_id;
    return replacement_row;
  end if;
  select * into replacement_row from public.care_supply_replacements
    where id=p_replacement_id and version=p_expected_version;
  if not found then raise exception 'care_current_replacement_required' using errcode='23514'; end if;
  select * into kit_row from public.care_supply_kits where id=replacement_row.supply_kit_id;
  if exists (
    select 1 from public.care_role_assignments
    where user_id=p_actor_user_id and role='clinical_admin' and revoked_at is null
  ) then actor_kind := 'clinical_admin';
  elsif exists (
    select 1 from public.care_pharmacy_orders pharmacy_order
    join public.care_pharmacy_operators operator
      on operator.pharmacy_id=pharmacy_order.assigned_pharmacy_id
      and operator.user_id=p_actor_user_id and operator.active and operator.revoked_at is null
    join public.care_role_assignments assignment
      on assignment.user_id=operator.user_id and assignment.role='pharmacy_operations'
      and assignment.revoked_at is null
    where pharmacy_order.prescription_id=kit_row.prescription_id
  ) then actor_kind := 'pharmacy_operator';
  else raise exception 'care_replacement_operator_required' using errcode='42501'; end if;
  next_status := case p_action
    when 'approve' then 'approved'
    when 'fulfill' then 'fulfilled'
    when 'decline' then 'declined'
    when 'cancel' then 'cancelled'
    else null end;
  if next_status is null or not (
    (replacement_row.status='requested' and next_status in ('approved','declined','cancelled'))
    or (replacement_row.status='approved' and next_status in ('fulfilled','cancelled'))
  ) then raise exception 'care_invalid_replacement_transition' using errcode='23514'; end if;
  update public.care_supply_replacements set status=next_status,
    version=version+1,updated_at=p_occurred_at where id=p_replacement_id
    returning * into replacement_row;
  insert into public.care_supply_replacement_events (
    replacement_id,patient_id,actor_user_id,actor_kind,action,from_status,
    to_status,idempotency_key,occurred_at
  ) values (
    replacement_row.id,replacement_row.patient_id,p_actor_user_id,actor_kind,
    p_action,null,next_status,p_idempotency_key,p_occurred_at
  );
  return replacement_row;
end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'care_instruction_sources','care_patient_instructions',
    'care_instruction_source_links','care_instruction_events',
    'care_instruction_acknowledgments','care_supply_sources',
    'care_supply_configuration_audit','care_supply_kits',
    'care_supply_kit_events','care_supply_replacements',
    'care_supply_replacement_events'
  ]
  loop
    execute format('alter table public.%I enable row level security',table_name);
    execute format('alter table public.%I force row level security',table_name);
    execute format('revoke all on table public.%I from public,anon,authenticated',table_name);
    execute format('grant all on table public.%I to service_role',table_name);
  end loop;
end;
$$;

revoke all on function public.care_audit_supply_source() from public,anon,authenticated;
revoke all on function public.care_create_instruction_source(uuid,uuid,text,text,text,text,uuid,text,timestamptz) from public,anon,authenticated;
revoke all on function public.care_create_patient_instruction_draft(uuid,uuid,uuid,text,uuid,uuid,uuid,uuid,uuid,text,timestamptz) from public,anon,authenticated;
revoke all on function public.care_release_patient_instruction(uuid,uuid,integer,text,timestamptz) from public,anon,authenticated;
revoke all on function public.care_acknowledge_patient_instruction(uuid,uuid,integer,text,timestamptz) from public,anon,authenticated;
revoke all on function public.care_save_supply_source(uuid,text,text,text,text,uuid,timestamptz) from public,anon,authenticated;
revoke all on function public.care_create_supply_kit(uuid,uuid,uuid,uuid,text,text,uuid,uuid,text,timestamptz) from public,anon,authenticated;
revoke all on function public.care_release_supply_kit(uuid,uuid,integer,text,timestamptz) from public,anon,authenticated;
revoke all on function public.care_request_supply_replacement(uuid,uuid,text,timestamptz) from public,anon,authenticated;
revoke all on function public.care_apply_supply_replacement_action(uuid,uuid,integer,text,text,timestamptz) from public,anon,authenticated;

grant execute on function public.care_create_instruction_source(uuid,uuid,text,text,text,text,uuid,text,timestamptz) to service_role;
grant execute on function public.care_create_patient_instruction_draft(uuid,uuid,uuid,text,uuid,uuid,uuid,uuid,uuid,text,timestamptz) to service_role;
grant execute on function public.care_release_patient_instruction(uuid,uuid,integer,text,timestamptz) to service_role;
grant execute on function public.care_acknowledge_patient_instruction(uuid,uuid,integer,text,timestamptz) to service_role;
grant execute on function public.care_save_supply_source(uuid,text,text,text,text,uuid,timestamptz) to service_role;
grant execute on function public.care_create_supply_kit(uuid,uuid,uuid,uuid,text,text,uuid,uuid,text,timestamptz) to service_role;
grant execute on function public.care_release_supply_kit(uuid,uuid,integer,text,timestamptz) to service_role;
grant execute on function public.care_request_supply_replacement(uuid,uuid,text,timestamptz) to service_role;
grant execute on function public.care_apply_supply_replacement_action(uuid,uuid,integer,text,text,timestamptz) to service_role;

insert into public.care_capabilities (capability_key,state)
values ('care','disabled')
on conflict (capability_key) do update
set state='disabled',approved_by=null,approved_at=null,updated_at=now();
