import type { Product, ProductCategory } from "@shared/research/types";

const peptideDefaults = {
  category: "peptides" as const,
  lane: "research" as const,
  status: "hold" as const,
  tags: ["Research material", "Batch documentation", "Account required"],
  qualityNotes: [
    "Final availability depends on completed supplier documentation and batch release.",
    "A purity result does not establish sterility, potency, or suitability for human use.",
    "Research materials are not medicines, supplements, foods, cosmetics, or medical devices.",
  ],
};

export const products: Product[] = [
  {
    ...peptideDefaults,
    slug: "bpc-157-tb-500-15-15",
    name: "BPC-157 + TB-500 Research Blend",
    shortName: "BPC-157 + TB-500",
    size: "15 mg / 15 mg",
    priceCents: 33999,
    eyebrow: "Tissue signaling research",
    summary: "A dual-compound research blend presented with exact specifications, batch documentation, and evidence limitations.",
    description: [
      "This listing is structured for legitimate nonclinical laboratory research and analytical use.",
      "Current FDA compounding review and limited human evidence require careful, current classification before any commerce is enabled.",
    ],
    highlights: ["Dual-compound research format", "Batch-specific documentation", "Controlled account access"],
    specifications: { Format: "Lyophilized research material", Strength: "15 mg / 15 mg", Route: "No human or veterinary use", Storage: "Per released batch specification" },
    researchContext: ["Preclinical research has examined related compounds in tissue signaling models.", "The finished blend is not FDA approved."],
    sourceUrl: "https://www.fda.gov/advisory-committees/advisory-committee-calendar/july-23-24-2026-meeting-pharmacy-compounding-advisory-committee-07232026",
    featured: true,
    badge: "Research profile",
    sortOrder: 1,
  },
  {
    ...peptideDefaults,
    slug: "bpc-tb-ghk-cu",
    name: "BPC-157 + TB-500 + GHK-Cu Research Blend",
    shortName: "BPC + TB + GHK-Cu",
    size: "10 mg / 10 mg / 50 mg",
    priceCents: 34999,
    eyebrow: "Multi-pathway research",
    summary: "A three-component blend with form-specific status, exact identity, and testing requirements.",
    description: ["The regulatory and quality treatment of GHK-Cu depends on the exact form and route represented.", "This product remains in research review until supplier and counsel gates are complete."],
    highlights: ["Three-component format", "Form-specific documentation", "Independent lot review"],
    specifications: { Format: "Lyophilized research material", Strength: "10 mg / 10 mg / 50 mg", Route: "No human or veterinary use", Access: "Professional research review" },
    researchContext: ["BPC-157 and TB-500 are scheduled for FDA advisory review.", "Non-injectable GHK-Cu appears separately in FDA Category 1 materials."],
    sourceUrl: "https://www.fda.gov/media/94155/download",
    sortOrder: 2,
  },
  {
    ...peptideDefaults,
    slug: "klow-research-blend",
    name: "KLOW Research Blend",
    size: "5 mg / 5 mg / 10 mg / 5 mg",
    priceCents: 33999,
    eyebrow: "Four-component research",
    summary: "A four-component research blend requiring component-level identity, assay, uniformity, and stability documentation.",
    description: ["KLOW combines TB-500, BPC-157, GHK-Cu, and KPV in one research format.", "No clinical protocol, outcome, or synergy claim is made by this catalog."],
    highlights: ["Four exact components", "Blend uniformity review", "Lot-level traceability"],
    specifications: { Components: "TB-500, BPC-157, GHK-Cu, KPV", Format: "Research material", Route: "No human or veterinary use", Status: "Regulatory hold" },
    sourceUrl: "https://www.fda.gov/advisory-committees/advisory-committee-calendar/july-23-24-2026-meeting-pharmacy-compounding-advisory-committee-07232026",
    sortOrder: 3,
  },
  {
    ...peptideDefaults,
    slug: "ta1-kpv-ll37",
    name: "Thymosin Alpha-1 + KPV + LL-37 Research Blend",
    size: "5 mg / 5 mg / 5 mg",
    priceCents: 38999,
    eyebrow: "Immune pathway research",
    summary: "A premium three-component research format with elevated microbiology, identity, and quality review requirements.",
    description: ["The catalog presents exact compound information and current evidence limitations only.", "No disease, immune, antimicrobial, or treatment claim is made."],
    highlights: ["Three-component identity", "Microbiology review", "Controlled research access"],
    specifications: { Format: "Research material", Strength: "5 mg / 5 mg / 5 mg", Route: "No human or veterinary use", Status: "Regulatory hold" },
    sourceUrl: "https://www.fda.gov/drugs/human-drug-compounding/certain-bulk-drug-substances-use-compounding-may-present-significant-safety-risks",
    sortOrder: 4,
  },
  {
    ...peptideDefaults,
    slug: "cjc-1295-ipamorelin",
    name: "CJC-1295 + Ipamorelin Research Blend",
    size: "5 mg / 5 mg",
    priceCents: 15999,
    eyebrow: "Growth hormone signaling research",
    summary: "A two-component research blend with exact form, impurity profile, and advisory history displayed clearly.",
    description: ["This listing does not present anti-aging, body composition, recovery, sleep, or performance claims.", "Availability remains gated by legal and quality review."],
    highlights: ["Exact substance review", "Impurity profile", "Professional access"],
    specifications: { Format: "Research material", Strength: "5 mg / 5 mg", Route: "No human or veterinary use", Status: "Regulatory hold" },
    sourceUrl: "https://www.fda.gov/drugs/human-drug-compounding/certain-bulk-drug-substances-use-compounding-may-present-significant-safety-risks",
    sortOrder: 5,
  },
  {
    ...peptideDefaults,
    slug: "pt-141-bremelanotide",
    name: "PT-141 Research Material",
    size: "10 mg",
    priceCents: 11999,
    status: "professional-only",
    eyebrow: "Melanocortin research",
    summary: "A research listing that clearly distinguishes this material from the approved finished drug Vyleesi.",
    description: ["An approved product exists for a specific formulation, indication, route, and sponsor.", "This research material does not inherit that approval."],
    highlights: ["Approved-product distinction", "Exact identity", "Professional account review"],
    specifications: { CommonName: "PT-141", RelatedName: "Bremelanotide", Strength: "10 mg", Route: "No human or veterinary use" },
    sourceUrl: "https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/210557s000lbl.pdf",
    sortOrder: 6,
  },
  {
    ...peptideDefaults,
    slug: "tesamorelin-10mg",
    name: "Tesamorelin Research Material",
    size: "10 mg",
    priceCents: 20999,
    status: "professional-only",
    eyebrow: "GHRH analog research",
    summary: "A research material listing that separates the Quantum SKU from approved Egrifta products and their narrow labeling.",
    description: ["The existence of an approved finished drug does not approve this research vial.", "No general weight management or body composition claim is presented."],
    highlights: ["Label distinction", "Batch assay", "Professional account access"],
    specifications: { Compound: "Tesamorelin", Strength: "10 mg", Format: "Research material", Route: "No human or veterinary use" },
    sourceUrl: "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/022505s020lbl.pdf",
    sortOrder: 7,
  },
  {
    ...peptideDefaults,
    slug: "gonadorelin-5mg",
    name: "Gonadorelin Research Material",
    size: "5 mg",
    priceCents: 12999,
    eyebrow: "GnRH research",
    summary: "A research listing under current enforcement review with no fertility, TRT, dosing, or clinical positioning.",
    description: ["Current FDA enforcement activity makes exact intended-use controls important.", "This listing is not a prescription or treatment pathway."],
    highlights: ["Current enforcement review", "Exact form", "No clinical claims"],
    specifications: { Compound: "Gonadorelin", Strength: "5 mg", Format: "Research material", Route: "No human or veterinary use" },
    sourceUrl: "https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters/wholesale-peptide-729447-06172026",
    sortOrder: 8,
  },
  {
    ...peptideDefaults,
    slug: "nad-plus-500mg",
    name: "NAD+ Research Material",
    size: "500 mg",
    priceCents: 15999,
    status: "professional-only",
    eyebrow: "Cellular cofactor research",
    summary: "A correctly classified research compound. NAD+ is not a peptide and Category 1 is not FDA approval.",
    description: ["This listing is deliberately separated from peptide taxonomy.", "It presents product specifications, evidence context, and current nomination status only."],
    highlights: ["Correct compound class", "Category 1 explained", "Professional access"],
    specifications: { CompoundClass: "Nicotinamide adenine dinucleotide", Strength: "500 mg", Peptide: "No", Route: "No human or veterinary use" },
    sourceUrl: "https://www.fda.gov/media/94155/download",
    featured: true,
    sortOrder: 9,
  },
  {
    ...peptideDefaults,
    slug: "mots-c-10mg",
    name: "MOTS-C Research Material",
    size: "10 mg",
    priceCents: 13999,
    eyebrow: "Mitochondrial peptide research",
    summary: "An early-stage research material with current PCAC review and a clear preclinical evidence label.",
    description: ["The material is not approved for weight management, glucose control, longevity, or performance use.", "Access remains on hold pending review."],
    highlights: ["PCAC status", "Preclinical evidence label", "Batch documentation"],
    specifications: { Compound: "MOTS-C", Strength: "10 mg", Format: "Research material", Route: "No human or veterinary use" },
    sourceUrl: "https://www.fda.gov/advisory-committees/advisory-committee-calendar/july-23-24-2026-meeting-pharmacy-compounding-advisory-committee-07232026",
    sortOrder: 10,
  },
  {
    ...peptideDefaults,
    slug: "epitalon-10mg",
    name: "Epitalon Research Material",
    size: "10 mg",
    priceCents: 12999,
    eyebrow: "Longevity pathway research",
    summary: "A research listing with current PCAC status, limited evidence classification, and no anti-aging promise.",
    description: ["The catalog does not present telomere, epigenetic, skin, lifespan, or human outcome claims.", "Exact identity and spelling are part of release review."],
    highlights: ["Current review status", "Evidence limitations", "Independent lot report"],
    specifications: { Compound: "Epitalon / Epithalon", Strength: "10 mg", Format: "Research material", Route: "No human or veterinary use" },
    sourceUrl: "https://www.fda.gov/advisory-committees/advisory-committee-calendar/july-23-24-2026-meeting-pharmacy-compounding-advisory-committee-07232026",
    sortOrder: 11,
  },
  {
    ...peptideDefaults,
    slug: "ss-31-elamipretide",
    name: "SS-31 Research Material",
    size: "10 mg",
    priceCents: 22999,
    status: "professional-only",
    eyebrow: "Mitochondrial membrane research",
    summary: "A research listing that clearly distinguishes SS-31 material from the approved finished product Forzinity.",
    description: ["Forzinity has a specific approved product, indication, sponsor, and manufacturing context.", "This material does not inherit that approval."],
    highlights: ["Approved-product distinction", "Exact form review", "Professional access"],
    specifications: { Compound: "SS-31 / Elamipretide", Strength: "10 mg", Format: "Research material", Route: "No human or veterinary use" },
    sourceUrl: "https://www.fda.gov/news-events/press-announcements/fda-grants-accelerated-approval-first-treatment-barth-syndrome",
    sortOrder: 12,
  },
  {
    ...peptideDefaults,
    slug: "slu-pp-332-capsules",
    name: "SLU-PP-332 Research Capsules",
    size: "250 mcg x 100",
    priceCents: 25999,
    eyebrow: "ERR agonist research",
    summary: "A small-molecule research product that is not classified as a peptide or a GLP-1 alternative.",
    description: ["Published research has primarily involved preclinical models.", "No appetite, weight management, exercise replacement, or human dose claim is made."],
    highlights: ["Correct small-molecule class", "Capsule uniformity", "Preclinical label"],
    specifications: { CompoundClass: "Small molecule", Count: "100 capsules", Strength: "250 mcg", Route: "No human or veterinary use" },
    sourceUrl: "https://www.fda.gov/drugs/development-approval-process-drugs",
    sortOrder: 13,
  },
  {
    ...peptideDefaults,
    slug: "dihexa-capsules",
    name: "Dihexa Research Capsules",
    size: "10 mg x 60",
    priceCents: 29999,
    eyebrow: "Neurobiology research",
    summary: "A preclinical research product with exact capsule specifications and no cognitive or neurological outcome claim.",
    description: ["The product is not approved for dementia, TBI, cognition, or neuro-repair.", "Availability remains on hold pending complete review."],
    highlights: ["Preclinical evidence label", "Capsule uniformity", "Impurity review"],
    specifications: { Count: "60 capsules", Strength: "10 mg", Format: "Research capsules", Route: "No human or veterinary use" },
    sourceUrl: "https://www.fda.gov/drugs/development-approval-process-drugs",
    sortOrder: 14,
  },
  {
    ...peptideDefaults,
    slug: "semax-selank-dsip",
    name: "Semax + Selank + DSIP Research Blend",
    size: "10 mg / 10 mg / 2 mg",
    priceCents: 25999,
    eyebrow: "Neuropeptide research",
    summary: "A three-component research blend with current PCAC review and no cognition, anxiety, sleep, or neuroprotection claim.",
    description: ["Semax and DSIP are scheduled for PCAC review.", "The blend requires component identity, assay, uniformity, route, and stability documentation."],
    highlights: ["Three-component identity", "Current review status", "Controlled access"],
    specifications: { Components: "Semax, Selank, DSIP", Strength: "10 mg / 10 mg / 2 mg", Format: "Research material", Route: "No human or veterinary use" },
    sourceUrl: "https://www.fda.gov/advisory-committees/advisory-committee-calendar/july-23-24-2026-meeting-pharmacy-compounding-advisory-committee-07232026",
    sortOrder: 15,
  },
  {
    slug: "quantum-foundational-platform",
    name: "Quantum Foundational Research Platform",
    shortName: "Quantum",
    category: "quantum",
    lane: "research",
    status: "request-access",
    priceCents: null,
    eyebrow: "Foundational research",
    summary: "Quantum is presented as a standalone research product with its own specifications, documentation, access path, and quality review.",
    description: ["Quantum can be explored independently from peptides, supplements, and programs.", "Final public copy, product class, claims, testing, and commerce depend on the complete Quantum technical and regulatory file."],
    highlights: ["Standalone product page", "Independent quality file", "Separate research checkout"],
    tags: ["Quantum", "Research platform", "Request access"],
    specifications: { ProductClass: "Pending completed technical classification", Access: "Application required", CommerceLane: "Research", Fulfillment: "Quantum backend" },
    researchContext: ["The public page intentionally avoids treatment, disease, regenerative, or human-use claims.", "Technical claims remain placeholders until supported by original documentation."],
    qualityNotes: ["Obtain full origin, manufacturing, testing, stability, storage, and lot-release records.", "Approve every origin, purity, sterility, facility, and third-party-testing representation before publishing."],
    featured: true,
    badge: "Quantum",
    sortOrder: 1,
  },
  {
    slug: "foundational-protein",
    name: "Foundational Protein",
    category: "supplements",
    lane: "consumer",
    status: "coming-soon",
    priceCents: null,
    eyebrow: "Daily foundation",
    summary: "A clean protein option designed for practical daily nutrition. Final formula, source, testing, flavors, and price will come from the approved wholesale catalog.",
    description: ["This is a structured catalog placeholder, not a final product claim.", "Replace with the supplier-approved formula and label before launch."],
    highlights: ["Transparent formula", "Practical routine", "Supplier documentation"],
    tags: ["Protein", "Foundational nutrition", "Coming soon"],
    specifications: { Formula: "Pending wholesale catalog", Servings: "Pending", Testing: "Pending", Flavor: "Pending" },
    featured: true,
    badge: "Coming soon",
    sortOrder: 1,
  },
  {
    slug: "creatine-monohydrate",
    name: "Creatine Monohydrate",
    category: "supplements",
    lane: "consumer",
    status: "coming-soon",
    priceCents: null,
    eyebrow: "Performance foundation",
    summary: "A premium creatine placeholder built around transparent sourcing, exact label accuracy, and third-party verification.",
    description: ["Final claims must match the actual ingredient, dose, manufacturing, and testing file.", "The site architecture is ready for one-time and subscription purchase."],
    highlights: ["Ingredient traceability", "Label accuracy", "Subscription ready"],
    tags: ["Creatine", "Performance", "Coming soon"],
    specifications: { Ingredient: "Pending wholesale catalog", Servings: "Pending", Testing: "Pending", Subscription: "Supported" },
    featured: true,
    badge: "Coming soon",
    sortOrder: 2,
  },
  {
    slug: "omega-3",
    name: "Omega-3",
    category: "supplements",
    lane: "consumer",
    status: "coming-soon",
    priceCents: null,
    eyebrow: "Foundational nutrition",
    summary: "A premium omega-3 placeholder with sourcing, oxidation, contaminant, and label-accuracy fields ready for the final supplier file.",
    description: ["The final page must identify source, EPA and DHA content, testing, serving size, and storage.", "No unsupported health claim is included in the starter copy."],
    highlights: ["Source transparency", "Contaminant testing", "Exact label data"],
    tags: ["Omega-3", "Daily foundation", "Coming soon"],
    specifications: { Source: "Pending", EPA_DHA: "Pending", Testing: "Pending", Servings: "Pending" },
    sortOrder: 3,
  },
  {
    slug: "magnesium-complex",
    name: "Magnesium Complex",
    category: "supplements",
    lane: "consumer",
    status: "coming-soon",
    priceCents: null,
    eyebrow: "Daily mineral support",
    summary: "A magnesium placeholder designed for a clear ingredient panel, exact forms, practical timing, and transparent testing.",
    description: ["Replace the placeholder with supplier-approved forms and serving information.", "The site can support variants if multiple forms are offered."],
    highlights: ["Exact mineral forms", "Simple routine", "Variant ready"],
    tags: ["Magnesium", "Routine", "Coming soon"],
    specifications: { Forms: "Pending", Serving: "Pending", Testing: "Pending", Variants: "Supported" },
    sortOrder: 4,
  },
  {
    slug: "daily-multi",
    name: "Daily Multi",
    category: "supplements",
    lane: "consumer",
    status: "coming-soon",
    priceCents: null,
    eyebrow: "Foundational routine",
    summary: "A multinutrient placeholder with a full facts-panel layout ready for the final wholesale formula.",
    description: ["Use the approved label as the source of truth.", "Avoid broad wellness promises that exceed ingredient evidence."],
    highlights: ["Full label visibility", "Daily routine", "Supplier-approved copy"],
    tags: ["Multivitamin", "Foundational", "Coming soon"],
    specifications: { Formula: "Pending", Servings: "Pending", Allergens: "Pending", Testing: "Pending" },
    sortOrder: 5,
  },
  {
    slug: "electrolyte-complex",
    name: "Electrolyte Complex",
    category: "supplements",
    lane: "consumer",
    status: "coming-soon",
    priceCents: null,
    eyebrow: "Hydration routine",
    summary: "A hydration placeholder designed for exact mineral quantities, flavor variants, and transparent ingredient disclosure.",
    description: ["Final copy must match the supplier facts panel and substantiated claims.", "The product page supports flavor selection and subscription cadence."],
    highlights: ["Exact mineral profile", "Flavor variants", "Subscription ready"],
    tags: ["Electrolytes", "Hydration", "Coming soon"],
    specifications: { Minerals: "Pending", Flavors: "Pending", Sweeteners: "Pending", Servings: "Pending" },
    sortOrder: 6,
  },
  {
    slug: "foundational-performance-program",
    name: "Foundational Performance Program",
    category: "programs",
    lane: "consumer",
    status: "coming-soon",
    priceCents: null,
    eyebrow: "Human-led programming",
    summary: "A structured training, nutrition, education, and accountability program with a real standalone value proposition.",
    description: ["Programs are separate from research products and are never positioned as a protocol for research materials.", "A human professional remains in front of the relationship."],
    highlights: ["Training framework", "Nutrition structure", "Human accountability"],
    tags: ["Performance", "Training", "Nutrition"],
    specifications: { Duration: "Configurable", Delivery: "Human-led", ResearchProductsIncluded: "No", MedicalCare: "No" },
    featured: true,
    badge: "Program",
    sortOrder: 1,
  },
  {
    slug: "recovery-routine-program",
    name: "Recovery Routine Program",
    category: "programs",
    lane: "consumer",
    status: "coming-soon",
    priceCents: null,
    eyebrow: "Better weekly structure",
    summary: "A nonclinical program centered on training load, nutrition, sleep routines, mobility, and accountability.",
    description: ["The program does not diagnose, treat, prescribe, or recommend research compounds.", "It can be purchased independently from every other category."],
    highlights: ["Weekly planning", "Recovery habits", "Accountability"],
    tags: ["Recovery", "Sleep", "Mobility"],
    specifications: { Delivery: "Human-led", Format: "Digital and coaching", ResearchProductsIncluded: "No", MedicalCare: "No" },
    sortOrder: 2,
  },
  {
    slug: "body-composition-program",
    name: "Body Composition Program",
    category: "programs",
    lane: "consumer",
    status: "coming-soon",
    priceCents: null,
    eyebrow: "Training and nutrition",
    summary: "A human-led training and nutrition program built around measurement, adherence, and clear weekly actions.",
    description: ["This is a lifestyle program, not a medication, peptide, or clinical treatment pathway.", "Research products never appear inside the program checkout."],
    highlights: ["Progress measurement", "Nutrition plan", "Coach approval"],
    tags: ["Body composition", "Nutrition", "Training"],
    specifications: { Delivery: "Human-led", CheckIns: "Configurable", ResearchProductsIncluded: "No", MedicalCare: "No" },
    sortOrder: 3,
  },
  {
    slug: "precision-routine-program",
    name: "Precision Routine Program",
    category: "programs",
    lane: "consumer",
    status: "coming-soon",
    priceCents: null,
    eyebrow: "Personal operating system",
    summary: "A structured routine that brings training, nutrition, supplementation, and accountability into one practical weekly system.",
    description: ["The program can include approved supplements after the wholesale catalog is finalized.", "Research materials remain a separate research lane and separate checkout."],
    highlights: ["One weekly system", "Supplement routine", "Human approval"],
    tags: ["Routine", "Accountability", "Supplements"],
    specifications: { Delivery: "Human-led", SupplementSupport: "Optional and separate", ResearchProductsIncluded: "No", MedicalCare: "No" },
    sortOrder: 4,
  },
];

export function getProduct(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug);
}

export function getProductsByCategory(category: ProductCategory): Product[] {
  return products
    .filter((product) => product.category === category)
    .sort((a, b) => (a.sortOrder ?? 99) - (b.sortOrder ?? 99));
}

export function getFeaturedProducts(): Product[] {
  return products.filter((product) => product.featured);
}
