// xenios neuroscience: the imported opportunity map.
//
// SERVER SIDE. This module holds a DISCOVERY list, classified but not verified.
//
// ---------------------------------------------------------------------------
// Where the data comes from
// ---------------------------------------------------------------------------
//
//   - `XENIOS_RESEARCH_COMPLETE_MASTER_2026-08-01_V3.xlsx`, sheet
//     "44 Neuroscience Map". 123 sheet rows: a title banner, a scope sentence, a
//     header row, and 120 item rows, NEU-0001 to NEU-0120.
//   - The same rows appear in
//     `14_SCIENTIFICSEAN_NEUROSCIENCE_AND_COMPOUND_CLASSIFICATION_2026-08-01_v2.xlsx`,
//     sheet "Opportunity Map". That workbook also carries "ScientificSean Categories"
//     (19 rows) and "ScientificSean Vendors" (11 rows), transcribed below as
//     discovery provenance.
//
// ---------------------------------------------------------------------------
// The discovery source rule
// ---------------------------------------------------------------------------
//
// Scientific Sean is a DISCOVERY SOURCE. It tells us what categories and items
// exist in this space and where our coverage has gaps. It is not a supplier, not
// a price list, and not a source of truth about legality, rights, or safety.
// Nothing here copies its images, labels, certificates, product text, or any
// other proprietary content. The category and vendor tables below record only
// observable coverage counts and the review action Xenios has to take.
//
// Every one of the 120 rows carries Status "Review" and the source context
// sentence naming the discovery source. None of them carries verification
// evidence. So every row imports UNVERIFIED, with all six verification inputs
// null, and `mayPresentAsOffer` is false for all 120. That is enforced by test,
// not by convention.
//
// The workbook's own boundary sentence appears verbatim on every record:
// benefits, dosing, and personal recommendations are not published without
// approved evidence and an approved route. Nothing in this module carries a
// dose, an administration instruction, or a claim.

import {
  classifyNeuroRow,
  countNeuroStates,
  mayPresentAsOffer,
  resolveNeuroPresentation,
  UNVERIFIED,
  type NeuroOperatingClass,
  type NeuroPresentation,
  type NeuroRecord,
  type NeuroStateCounts,
} from "@shared/research/neuroscience/classification";

/** The scope sentence from row 2 of sheet "44 Neuroscience Map", verbatim. */
export const NEUROSCIENCE_SCOPE_STATEMENT =
  "Items are classified by operating lane. Listing does not mean recommendation, availability, legality, safety or approval.";

/** One row of the opportunity map, transcribed. */
export interface NeuroSourceRow {
  readonly id: string;
  readonly item: string;
  readonly sourceClass: string;
  readonly sourceRoute: string;
  readonly sourceLane: string;
  readonly requiredProfessionalReview: string;
  readonly discoverySource: string;
  readonly publicBoundary: string;
  /** The workbook's status cell. "Review" on all 120 rows: nothing is settled. */
  readonly sourceStatus: string;
}

export const NEURO_SOURCE_ROWS: readonly NeuroSourceRow[] = [
  {
    id: "NEU-0001",
    item: "Semax",
    sourceClass: "Peptide / nootropic",
    sourceRoute: "Qualified Research; potential future professional route",
    sourceLane: "Research / Investigational",
    requiredProfessionalReview: "Neurology / psychiatry / counsel as applicable",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0002",
    item: "Selank",
    sourceClass: "Peptide / nootropic",
    sourceRoute: "Qualified Research",
    sourceLane: "Research / Investigational",
    requiredProfessionalReview: "Neurology / psychiatry / counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0003",
    item: "DSIP / Emideltide",
    sourceClass: "Peptide / sleep",
    sourceRoute: "Qualified Research; official 2026 PCAC review",
    sourceLane: "Research / Held pending exact strategy",
    requiredProfessionalReview: "Sleep medicine / counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0004",
    item: "Dihexa",
    sourceClass: "Research compound",
    sourceRoute: "Qualified Research",
    sourceLane: "Research / Investigational",
    requiredProfessionalReview: "Neurology / counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0005",
    item: "Adamax",
    sourceClass: "Research compound",
    sourceRoute: "Qualified Research",
    sourceLane: "Research / Investigational",
    requiredProfessionalReview: "Neurology / counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0006",
    item: "P21",
    sourceClass: "Peptide research",
    sourceRoute: "Qualified Research",
    sourceLane: "Research / Investigational",
    requiredProfessionalReview: "Neurology / counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0007",
    item: "PE-22-28",
    sourceClass: "Peptide research",
    sourceRoute: "Qualified Research",
    sourceLane: "Research / Investigational",
    requiredProfessionalReview: "Neurology / counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0008",
    item: "Cerebrolysin",
    sourceClass: "Biologic mixture / prescription abroad",
    sourceRoute: "Professional and legal review",
    sourceLane: "Held / jurisdiction dependent",
    requiredProfessionalReview: "Neurology / pharmacy / counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0009",
    item: "N-Acetyl Semax Amidate",
    sourceClass: "Peptide research",
    sourceRoute: "Qualified Research",
    sourceLane: "Research / Investigational",
    requiredProfessionalReview: "Neurology / counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0010",
    item: "Pinealon",
    sourceClass: "Bioregulator",
    sourceRoute: "Qualified Research",
    sourceLane: "Research / Investigational",
    requiredProfessionalReview: "Neurology / counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0011",
    item: "Epitalon",
    sourceClass: "Peptide / longevity",
    sourceRoute: "Qualified Research; future compounding strategy watch",
    sourceLane: "Research / Investigational",
    requiredProfessionalReview: "Counsel / professional route",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0012",
    item: "SS-31",
    sourceClass: "Mitochondrial peptide",
    sourceRoute: "Qualified Research",
    sourceLane: "Research / Investigational",
    requiredProfessionalReview: "Research professional",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0013",
    item: "MOTS-c",
    sourceClass: "Mitochondrial peptide",
    sourceRoute: "Qualified Research; future compounding strategy watch",
    sourceLane: "Research / Investigational",
    requiredProfessionalReview: "Counsel / professional route",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0014",
    item: "NAD+",
    sourceClass: "Cofactor / product class",
    sourceRoute: "Supplement / Research / Care depending form",
    sourceLane: "Multi-rail",
    requiredProfessionalReview: "Product + clinical",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0015",
    item: "Glutathione",
    sourceClass: "Antioxidant / tripeptide",
    sourceRoute: "Supplement / Research / Care depending form",
    sourceLane: "Multi-rail",
    requiredProfessionalReview: "Product + clinical",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0016",
    item: "Creatine",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label / nutrition scope",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0017",
    item: "Omega-3",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label / clinical if personal",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0018",
    item: "Magnesium L-threonate",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label / clinical if personal",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0019",
    item: "L-theanine",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label / clinical if personal",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0020",
    item: "Citicoline",
    sourceClass: "Supplement / prescription by country",
    sourceRoute: "Authorized supplement where lawful",
    sourceLane: "Public / jurisdiction review",
    requiredProfessionalReview: "Product + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0021",
    item: "Alpha GPC",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0022",
    item: "Bacopa monnieri",
    sourceClass: "Supplement / herb",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0023",
    item: "Rhodiola rosea",
    sourceClass: "Supplement / herb",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0024",
    item: "Ashwagandha",
    sourceClass: "Supplement / herb",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0025",
    item: "Acetyl-L-carnitine",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0026",
    item: "Taurine",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0027",
    item: "Glycine",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0028",
    item: "Inositol",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0029",
    item: "Melatonin",
    sourceClass: "Supplement / hormone",
    sourceRoute: "Authorized supplement; state/market review",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label / clinical when personal",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0030",
    item: "Apigenin",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0031",
    item: "Lion's Mane",
    sourceClass: "Supplement / mushroom",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0032",
    item: "Saffron",
    sourceClass: "Supplement / botanical",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0033",
    item: "CoQ10",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0034",
    item: "PQQ",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0035",
    item: "NAC",
    sourceClass: "Supplement / drug-status nuance",
    sourceRoute: "Product and market review",
    sourceLane: "Public / review",
    requiredProfessionalReview: "Product + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0036",
    item: "Vitamin D",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0037",
    item: "B-complex",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0038",
    item: "Iron",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement; professional review for personal selection",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label / clinician",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0039",
    item: "Zinc",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0040",
    item: "Phosphatidylserine",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0041",
    item: "Huperzine A",
    sourceClass: "Supplement / research",
    sourceRoute: "Product review",
    sourceLane: "Public / review",
    requiredProfessionalReview: "Product + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0042",
    item: "SAMe",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0043",
    item: "Resveratrol",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0044",
    item: "Curcumin",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0045",
    item: "Quercetin",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0046",
    item: "L-tyrosine",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0047",
    item: "L-tryptophan",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0048",
    item: "GABA",
    sourceClass: "Supplement",
    sourceRoute: "Authorized supplement",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0049",
    item: "Cognitive baseline assessment",
    sourceClass: "Assessment",
    sourceRoute: "Professional assessment service",
    sourceLane: "Care / professional",
    requiredProfessionalReview: "Neuropsychology / licensed professional",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0050",
    item: "ADHD evaluation",
    sourceClass: "Clinical assessment",
    sourceRoute: "Licensed professional evaluation",
    sourceLane: "Care",
    requiredProfessionalReview: "Psychiatry / qualified clinician",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0051",
    item: "Sleep assessment",
    sourceClass: "Assessment",
    sourceRoute: "Professional or validated wellness assessment",
    sourceLane: "Care / wellness split",
    requiredProfessionalReview: "Sleep medicine / coach scope",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0052",
    item: "Depression/anxiety screening",
    sourceClass: "Clinical screening",
    sourceRoute: "Licensed workflow with escalation",
    sourceLane: "Care",
    requiredProfessionalReview: "Mental health professional",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0053",
    item: "Neuropsychological testing",
    sourceClass: "Clinical assessment",
    sourceRoute: "Professional referral",
    sourceLane: "Care",
    requiredProfessionalReview: "Neuropsychologist",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0054",
    item: "EEG",
    sourceClass: "Diagnostic",
    sourceRoute: "Clinician-ordered service",
    sourceLane: "Care",
    requiredProfessionalReview: "Neurology",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0055",
    item: "Brain MRI",
    sourceClass: "Diagnostic",
    sourceRoute: "Clinician-ordered service",
    sourceLane: "Care",
    requiredProfessionalReview: "Radiology / neurology",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0056",
    item: "Cognitive bloodwork panel",
    sourceClass: "Lab panel",
    sourceRoute: "Clinician-ordered and reviewed",
    sourceLane: "Care",
    requiredProfessionalReview: "Licensed professional",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0057",
    item: "Modafinil",
    sourceClass: "Prescription medication",
    sourceRoute: "Licensed professional and lawful pharmacy",
    sourceLane: "Prescription required",
    requiredProfessionalReview: "Sleep medicine / psychiatry",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0058",
    item: "Armodafinil",
    sourceClass: "Prescription medication",
    sourceRoute: "Licensed professional and lawful pharmacy",
    sourceLane: "Prescription required",
    requiredProfessionalReview: "Sleep medicine / psychiatry",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0059",
    item: "Pitolisant",
    sourceClass: "Prescription medication",
    sourceRoute: "Licensed professional and lawful pharmacy",
    sourceLane: "Prescription required",
    requiredProfessionalReview: "Sleep medicine",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0060",
    item: "Atomoxetine",
    sourceClass: "Prescription medication",
    sourceRoute: "Licensed professional and lawful pharmacy",
    sourceLane: "Prescription required",
    requiredProfessionalReview: "Psychiatry / primary care",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0061",
    item: "Methylphenidate",
    sourceClass: "Schedule II prescription",
    sourceRoute: "Licensed professional; controlled-telemedicine rules",
    sourceLane: "Prescription required",
    requiredProfessionalReview: "Psychiatry / DEA",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0062",
    item: "Amphetamine salts",
    sourceClass: "Schedule II prescription",
    sourceRoute: "Licensed professional; controlled-telemedicine rules",
    sourceLane: "Prescription required",
    requiredProfessionalReview: "Psychiatry / DEA",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0063",
    item: "Lisdexamfetamine",
    sourceClass: "Schedule II prescription",
    sourceRoute: "Licensed professional; controlled-telemedicine rules",
    sourceLane: "Prescription required",
    requiredProfessionalReview: "Psychiatry / DEA",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0064",
    item: "Guanfacine ER",
    sourceClass: "Prescription medication",
    sourceRoute: "Licensed professional",
    sourceLane: "Prescription required",
    requiredProfessionalReview: "Psychiatry / primary care",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0065",
    item: "Clonidine ER",
    sourceClass: "Prescription medication",
    sourceRoute: "Licensed professional",
    sourceLane: "Prescription required",
    requiredProfessionalReview: "Psychiatry / primary care",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0066",
    item: "Bupropion",
    sourceClass: "Prescription medication",
    sourceRoute: "Licensed professional",
    sourceLane: "Prescription required",
    requiredProfessionalReview: "Psychiatry / primary care",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0067",
    item: "SSRIs",
    sourceClass: "Prescription class",
    sourceRoute: "Licensed professional",
    sourceLane: "Prescription required",
    requiredProfessionalReview: "Psychiatry / primary care",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0068",
    item: "SNRIs",
    sourceClass: "Prescription class",
    sourceRoute: "Licensed professional",
    sourceLane: "Prescription required",
    requiredProfessionalReview: "Psychiatry / primary care",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0069",
    item: "Donepezil",
    sourceClass: "Prescription medication",
    sourceRoute: "Licensed professional",
    sourceLane: "Prescription required",
    requiredProfessionalReview: "Neurology / geriatrics",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0070",
    item: "Memantine",
    sourceClass: "Prescription medication",
    sourceRoute: "Licensed professional",
    sourceLane: "Prescription required",
    requiredProfessionalReview: "Neurology / geriatrics",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0071",
    item: "Suvorexant / dual orexin antagonist",
    sourceClass: "Prescription medication",
    sourceRoute: "Licensed professional; controlled status review",
    sourceLane: "Prescription required",
    requiredProfessionalReview: "Sleep medicine",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0072",
    item: "Piracetam",
    sourceClass: "Racetam",
    sourceRoute: "Jurisdiction/product status review",
    sourceLane: "Research / jurisdiction dependent",
    requiredProfessionalReview: "Counsel / clinical",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0073",
    item: "Aniracetam",
    sourceClass: "Racetam",
    sourceRoute: "Qualified Research / jurisdiction review",
    sourceLane: "Research",
    requiredProfessionalReview: "Counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0074",
    item: "Oxiracetam",
    sourceClass: "Racetam",
    sourceRoute: "Qualified Research / jurisdiction review",
    sourceLane: "Research",
    requiredProfessionalReview: "Counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0075",
    item: "Pramiracetam",
    sourceClass: "Racetam",
    sourceRoute: "Qualified Research / jurisdiction review",
    sourceLane: "Research",
    requiredProfessionalReview: "Counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0076",
    item: "Phenylpiracetam",
    sourceClass: "Racetam",
    sourceRoute: "Qualified Research; athlete review",
    sourceLane: "Research / WADA review",
    requiredProfessionalReview: "Counsel / sports compliance",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0077",
    item: "Noopept",
    sourceClass: "Nootropic research compound",
    sourceRoute: "Qualified Research / jurisdiction review",
    sourceLane: "Research",
    requiredProfessionalReview: "Counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0078",
    item: "Bromantane",
    sourceClass: "Research / prescription abroad",
    sourceRoute: "Qualified Research / jurisdiction review",
    sourceLane: "Research / athlete review",
    requiredProfessionalReview: "Counsel / sports compliance",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0079",
    item: "Fasoracetam",
    sourceClass: "Research compound",
    sourceRoute: "Qualified Research",
    sourceLane: "Research",
    requiredProfessionalReview: "Counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0080",
    item: "Sunifiram",
    sourceClass: "Research compound",
    sourceRoute: "Qualified Research",
    sourceLane: "Research",
    requiredProfessionalReview: "Counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0081",
    item: "Unifiram",
    sourceClass: "Research compound",
    sourceRoute: "Qualified Research",
    sourceLane: "Research",
    requiredProfessionalReview: "Counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0082",
    item: "Irdabisant",
    sourceClass: "Investigational H3 antagonist",
    sourceRoute: "Qualified Research",
    sourceLane: "Research / Investigational",
    requiredProfessionalReview: "Neurology / counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0083",
    item: "Fluorene myristate",
    sourceClass: "Poorly documented research compound",
    sourceRoute: "Do not pursue without identity/toxicology",
    sourceLane: "Held",
    requiredProfessionalReview: "Quality + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0084",
    item: "Sitagliptin",
    sourceClass: "Prescription antidiabetic",
    sourceRoute: "Care only if clinically relevant",
    sourceLane: "Prescription required",
    requiredProfessionalReview: "Licensed professional",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0085",
    item: "Larazotide",
    sourceClass: "Investigational peptide",
    sourceRoute: "Research / clinical-development watch",
    sourceLane: "Investigational",
    requiredProfessionalReview: "GI specialist / counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0086",
    item: "Lipo MIC Prime",
    sourceClass: "Injectable nutrient blend",
    sourceRoute: "Professional / pharmacy product review",
    sourceLane: "Care / held pending source",
    requiredProfessionalReview: "Licensed professional / pharmacy",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0087",
    item: "Mucuna pruriens",
    sourceClass: "Botanical with L-DOPA",
    sourceRoute: "Authorized supplement review and interaction language",
    sourceLane: "Public / professional review",
    requiredProfessionalReview: "Product + clinical",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0088",
    item: "Laminarin",
    sourceClass: "Supplement / polysaccharide",
    sourceRoute: "Education / supplement if sourced",
    sourceLane: "Public wellness",
    requiredProfessionalReview: "Label",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0089",
    item: "BPC-157 + TB-500 Research Blend",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0090",
    item: "BPC-157 + TB-500 + GHK-Cu Research Blend",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0091",
    item: "KLOW Research Blend",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0092",
    item: "Thymosin Alpha-1 + KPV + LL-37 Research Blend",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0093",
    item: "CJC-1295 + Ipamorelin Research Blend",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0094",
    item: "PT-141 Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0095",
    item: "Tesamorelin Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0096",
    item: "Gonadorelin Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0097",
    item: "NAD+ Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0098",
    item: "MOTS-C Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0099",
    item: "Epithalon Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0100",
    item: "SS-31 Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0101",
    item: "SLU-PP-332 Research Capsules",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0102",
    item: "Dihexa Research Capsules",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0103",
    item: "Semax + Selank + DSIP Research Blend",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0104",
    item: "BPC-157 Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0105",
    item: "TB-500 Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0106",
    item: "GHK-Cu Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0107",
    item: "KPV Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0108",
    item: "Semax Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0109",
    item: "Selank Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0110",
    item: "DSIP Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0111",
    item: "Thymosin Alpha-1 Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0112",
    item: "Ipamorelin Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0113",
    item: "5-Amino-1MQ Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0114",
    item: "Adamax Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0115",
    item: "AOD-9604 Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0116",
    item: "CJC-1295 with DAC Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0117",
    item: "Follistatin Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0118",
    item: "Glutathione Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0119",
    item: "HCG Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
  {
    id: "NEU-0120",
    item: "IGF-1 LR3 Research Material",
    sourceClass: "Peptide / Research material",
    sourceRoute: "Qualified Research; neuroscience relevance to be classified",
    sourceLane: "Research / review",
    requiredProfessionalReview: "Research professional + counsel",
    discoverySource: "ScientificSean / Xenios master / official product sources as applicable",
    publicBoundary: "Do not publish benefits, dosing, or personal recommendations without approved evidence and route",
    sourceStatus: "Review",
  },
];

// ---------------------------------------------------------------------------
// Discovery provenance
// ---------------------------------------------------------------------------

export interface DiscoveryCategoryRow {
  readonly id: string;
  readonly category: string;
  /**
   * Listings observed in that category on the discovery source. This is a
   * coverage signal about the outside world. It is NOT Xenios inventory, and it
   * is not a count of anything we can supply.
   */
  readonly observedListingCount: number;
  readonly classificationNote: string;
  readonly riskLevel: string;
  readonly action: string;
}

export const DISCOVERY_CATEGORIES: readonly DiscoveryCategoryRow[] = [
  {
    id: "SS-CAT-01",
    category: "Nootropics",
    observedListingCount: 401,
    classificationNote: "Education / supplement / Research / prescription split",
    riskLevel: "High",
    action: "Build neuroscience taxonomy; do not import benefits or dosing",
  },
  {
    id: "SS-CAT-02",
    category: "Hormonal",
    observedListingCount: 196,
    classificationNote: "Care / prescription / supplement / Research split",
    riskLevel: "High",
    action: "Professional routing required",
  },
  {
    id: "SS-CAT-03",
    category: "Performance",
    observedListingCount: 142,
    classificationNote: "Supplement / program / Research",
    riskLevel: "High",
    action: "Athlete eligibility and claims controls",
  },
  {
    id: "SS-CAT-04",
    category: "Peptides",
    observedListingCount: 163,
    classificationNote: "Qualified Research or Care depending exact item",
    riskLevel: "Critical",
    action: "Exact identity and route",
  },
  {
    id: "SS-CAT-05",
    category: "Longevity",
    observedListingCount: 185,
    classificationNote: "Education / supplement / Research / Care",
    riskLevel: "High",
    action: "Evidence and claim classification",
  },
  {
    id: "SS-CAT-06",
    category: "Skin",
    observedListingCount: 78,
    classificationNote: "Cosmetic / supplement / Research / Care",
    riskLevel: "Medium",
    action: "Separate cosmetic claims",
  },
  {
    id: "SS-CAT-07",
    category: "Blends",
    observedListingCount: 60,
    classificationNote: "Depends on components and source",
    riskLevel: "Critical",
    action: "Component identity/order/strength",
  },
  {
    id: "SS-CAT-08",
    category: "Sleep & Anxiety",
    observedListingCount: 152,
    classificationNote: "Education / supplement / Care / prescription / Research",
    riskLevel: "High",
    action: "Mental-health and prescription routing",
  },
  {
    id: "SS-CAT-09",
    category: "Antioxidants",
    observedListingCount: 117,
    classificationNote: "Supplement / education / Research",
    riskLevel: "Medium",
    action: "Label-accurate claims",
  },
  {
    id: "SS-CAT-10",
    category: "Fat Loss",
    observedListingCount: 70,
    classificationNote: "Program / Care / supplement / Research",
    riskLevel: "High",
    action: "Weight-loss claim and GLP controls",
  },
  {
    id: "SS-CAT-11",
    category: "Sexual Health",
    observedListingCount: 54,
    classificationNote: "Care / supplement / Research",
    riskLevel: "High",
    action: "Professional routing and claims",
  },
  {
    id: "SS-CAT-12",
    category: "Cholinergics",
    observedListingCount: 88,
    classificationNote: "Supplement / Research / prescription",
    riskLevel: "High",
    action: "Neuroscience classification",
  },
  {
    id: "SS-CAT-13",
    category: "Adaptogens",
    observedListingCount: 59,
    classificationNote: "Supplement / education",
    riskLevel: "Medium",
    action: "Label and evidence",
  },
  {
    id: "SS-CAT-14",
    category: "Hair",
    observedListingCount: 23,
    classificationNote: "Cosmetic / Care / supplement / Research",
    riskLevel: "Medium",
    action: "Claims and route",
  },
  {
    id: "SS-CAT-15",
    category: "Bioregulators",
    observedListingCount: 24,
    classificationNote: "Research / investigational",
    riskLevel: "High",
    action: "Supplier and evidence diligence",
  },
  {
    id: "SS-CAT-16",
    category: "SARMs",
    observedListingCount: 21,
    classificationNote: "Held / legal and clinical review",
    riskLevel: "Critical",
    action: "Do not activate automatically",
  },
  {
    id: "SS-CAT-17",
    category: "Racetams",
    observedListingCount: 21,
    classificationNote: "Research / prescription status review",
    riskLevel: "High",
    action: "Jurisdiction and evidence",
  },
  {
    id: "SS-CAT-18",
    category: "Eugeroics",
    observedListingCount: 18,
    classificationNote: "Prescription / Research / held",
    riskLevel: "High",
    action: "Psychiatry/sleep professional route",
  },
  {
    id: "SS-CAT-19",
    category: "Anabolic Steroids",
    observedListingCount: 15,
    classificationNote: "Care / prescription / held",
    riskLevel: "Critical",
    action: "Professional and controlled-substance rules",
  },
];

export interface DiscoveryVendorRow {
  readonly id: string;
  readonly vendor: string;
  readonly observedListingCount: number;
  /**
   * How the discovery source relates to the vendor. "Affiliate/vendor listing"
   * means the vendor appears on that site. It is not a Xenios relationship, not
   * an authorization, and not a diligence outcome.
   */
  readonly relationship: string;
  readonly action: string;
}

export const DISCOVERY_VENDORS: readonly DiscoveryVendorRow[] = [
  {
    id: "SS-V-01",
    vendor: "Research Use Only",
    observedListingCount: 100,
    relationship: "Affiliate/vendor listing",
    action: "Independent supplier diligence required",
  },
  {
    id: "SS-V-02",
    vendor: "Kimera Chems",
    observedListingCount: 164,
    relationship: "Affiliate/vendor listing",
    action: "Independent supplier diligence required",
  },
  {
    id: "SS-V-03",
    vendor: "Limitless Life Nootropics",
    observedListingCount: 105,
    relationship: "Affiliate/vendor listing",
    action: "Independent supplier diligence required",
  },
  {
    id: "SS-V-04",
    vendor: "Moglabs",
    observedListingCount: 53,
    relationship: "Affiliate/vendor listing",
    action: "Independent supplier diligence required",
  },
  {
    id: "SS-V-05",
    vendor: "Peptira",
    observedListingCount: 97,
    relationship: "Affiliate/vendor listing",
    action: "Independent supplier diligence required",
  },
  {
    id: "SS-V-06",
    vendor: "Exceed",
    observedListingCount: 62,
    relationship: "Affiliate/vendor listing",
    action: "Independent supplier diligence required",
  },
  {
    id: "SS-V-07",
    vendor: "Performeds",
    observedListingCount: 12,
    relationship: "Affiliate/vendor listing",
    action: "Independent supplier diligence required",
  },
  {
    id: "SS-V-08",
    vendor: "PCT.Zone",
    observedListingCount: 333,
    relationship: "Affiliate/vendor listing",
    action: "Independent supplier diligence required",
  },
  {
    id: "SS-V-09",
    vendor: "CBN provider",
    observedListingCount: 7,
    relationship: "Affiliate/vendor listing",
    action: "Verify exact entity/products",
  },
  {
    id: "SS-V-10",
    vendor: "Lion’s Mane provider",
    observedListingCount: 5,
    relationship: "Affiliate/vendor listing",
    action: "Verify exact entity/products",
  },
  {
    id: "SS-V-11",
    vendor: "Amazon",
    observedListingCount: 170,
    relationship: "Marketplace",
    action: "Not a quality or authorization signal",
  },
];

// ---------------------------------------------------------------------------
// Projection
// ---------------------------------------------------------------------------

/**
 * Turn a transcribed row into a classified record.
 *
 * Classification comes from the ordered rule set in the shared contract.
 * Verification does not come from the sheet at all: there is no verification
 * evidence in it, so every record gets `UNVERIFIED` and null commerce fields.
 * A price, a supplier code, or a lab document can only arrive later, from a
 * document somebody recorded.
 */
export function toNeuroRecord(row: NeuroSourceRow): NeuroRecord {
  const classification = classifyNeuroRow({
    sourceClass: row.sourceClass,
    sourceRoute: row.sourceRoute,
    sourceLane: row.sourceLane,
  });
  return {
    id: row.id,
    item: row.item,
    sourceClass: row.sourceClass,
    sourceRoute: row.sourceRoute,
    sourceLane: row.sourceLane,
    operatingClass: classification.operatingClass,
    classificationRuleId: classification.ruleId,
    discoverySource: row.discoverySource,
    requiredProfessionalReview: row.requiredProfessionalReview,
    publicBoundary: row.publicBoundary,
    verification: UNVERIFIED,
    approvedCustomerAmountCents: null,
    supplierSkuCode: null,
    internalVariantSku: null,
    coaEvidence: "NOT_ON_FILE",
    unavailable: false,
  };
}

/** The 120 imported neuroscience records, classified and unverified. */
export const NEUROSCIENCE_OPPORTUNITY_MAP: readonly NeuroRecord[] =
  NEURO_SOURCE_ROWS.map(toNeuroRecord);

export function findNeuroRecord(id: string): NeuroRecord | undefined {
  return NEUROSCIENCE_OPPORTUNITY_MAP.find((record) => record.id === id);
}

export function neuroRecordsByClass(
  operatingClass: NeuroOperatingClass,
  records: readonly NeuroRecord[] = NEUROSCIENCE_OPPORTUNITY_MAP,
): readonly NeuroRecord[] {
  return records.filter((record) => record.operatingClass === operatingClass);
}

// ---------------------------------------------------------------------------
// Routing
// ---------------------------------------------------------------------------

export interface RoutedNeuroRecord {
  readonly record: NeuroRecord;
  readonly presentation: NeuroPresentation;
}

/** Every record with the surface it routes to. The one place a surface should read. */
export function routeNeuroRecords(
  records: readonly NeuroRecord[] = NEUROSCIENCE_OPPORTUNITY_MAP,
): readonly RoutedNeuroRecord[] {
  return records.map((record) => ({ record, presentation: resolveNeuroPresentation(record) }));
}

/**
 * The records that may present as an offer on a Research surface right now.
 *
 * Empty today, and that is the correct answer, not a bug.
 */
export function offerableNeuroRecords(
  records: readonly NeuroRecord[] = NEUROSCIENCE_OPPORTUNITY_MAP,
): readonly NeuroRecord[] {
  return records.filter(mayPresentAsOffer);
}

// ---------------------------------------------------------------------------
// Reporting
// ---------------------------------------------------------------------------

export function neuroscienceCounts(): NeuroStateCounts {
  return countNeuroStates(NEUROSCIENCE_OPPORTUNITY_MAP);
}

/** How many rows each classification rule decided, so an odd rule shows up. */
export function classificationRuleHistogram(
  records: readonly NeuroRecord[] = NEUROSCIENCE_OPPORTUNITY_MAP,
): Readonly<Record<string, number>> {
  const counts: Record<string, number> = {};
  for (const record of records) {
    counts[record.classificationRuleId] = (counts[record.classificationRuleId] ?? 0) + 1;
  }
  return counts;
}
