// xenios education library: the imported exercise records.
//
// SERVER SIDE. This module holds the production tracker exactly as the source
// workbook states it, including the fields that are still empty. Surfaces read
// `EXERCISE_LIBRARY` through the shared publication gate, never around it.
//
// ---------------------------------------------------------------------------
// Where the data comes from
// ---------------------------------------------------------------------------
//
//   - `XENIOS_RESEARCH_COMPLETE_MASTER_2026-08-01_V3.xlsx`, sheet
//     "43 Education Exercise". 103 sheet rows: a title banner, a scope sentence,
//     a header row, and 100 exercise rows, EX-0001 to EX-0100.
//   - The same rows appear in `13_EDUCATION_EXERCISE_AND_LEARNING_LIBRARY_2026-08-01_v2.xlsx`,
//     sheet "Exercise Library". That workbook also carries sheet "Approval Matrix",
//     rows ED-AP-001 to ED-AP-010, transcribed below as `EDUCATION_APPROVAL_MATRIX`.
//
// Every field below is a transcription. Nothing was inferred from an exercise
// name, and no missing field was filled in.
//
// ---------------------------------------------------------------------------
// What the workbook actually says, and what that means here
// ---------------------------------------------------------------------------
//
// All 100 rows carry the same four placeholder values:
//
//   Reviewer   "Professional reviewer pending"  -> zero recorded reviews
//   Video      "Video needed"                   -> media is null
//   Transcript "Transcript needed"              -> transcript is null
//   Tags       "Tags needed"                    -> tags is empty
//
// and Status "Draft". A placeholder is not evidence. `isRealValue` in the shared
// contract rejects every one of these phrases, so none of them can be mistaken
// for a reviewer, an asset, or a transcript. The library is therefore complete in
// structure and empty in approvals, which is the truthful state.
//
// Afam Maduka is the named AUTHOR on all 100 rows, transcribed from the author
// column. He has not reviewed anything here, and no review by him or by anyone
// else is recorded in this build.
//
// The workbook assigns no per record audience, so `audience` is null on every
// record and every record carries the MISSING_AUDIENCE blocker. The library level
// scope sentence is transcribed as `LIBRARY_SCOPE_STATEMENT` rather than being
// converted into a per record audience value we were never given.

import {
  countEducationStates,
  evaluatePublication,
  type EducationDifficulty,
  type EducationEquipment,
  type EducationMovementPattern,
  type EducationRecord,
  type EducationSensitiveSubject,
  type EducationStateCounts,
  type PublicationBlocker,
} from "@shared/research/education/library";

/** The scope sentence from row 2 of sheet "43 Education Exercise", verbatim. */
export const LIBRARY_SCOPE_STATEMENT =
  "Exercise education is general fitness content. Pain, injury, surgery, neurological symptoms and medical clearance route to appropriate professionals.";

/** One row of the production tracker, transcribed. */
export interface ExerciseSourceRow {
  readonly id: string;
  readonly title: string;
  readonly sourceCategory: string;
  readonly movementPattern: EducationMovementPattern;
  readonly equipment: EducationEquipment;
  readonly difficulty: EducationDifficulty;
  readonly purpose: string;
  readonly escalationNote: string;
  readonly author: string;
  /** The workbook's reviewer cell, kept verbatim so the placeholder stays visible. */
  readonly sourceReviewerNote: string;
  readonly sourceScriptNote: string;
  readonly sourceVideoNote: string;
  readonly sourceTranscriptNote: string;
  readonly sourceTagsNote: string;
  readonly sourceStatus: string;
}

export const EXERCISE_SOURCE_ROWS: readonly ExerciseSourceRow[] = [
  {
    id: "EX-0001",
    title: "Bodyweight Squat",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "bodyweight",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0002",
    title: "Goblet Squat",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0003",
    title: "Front Squat",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0004",
    title: "Back Squat",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0005",
    title: "Split Squat",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0006",
    title: "Reverse Lunge",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0007",
    title: "Forward Lunge",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0008",
    title: "Lateral Lunge",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0009",
    title: "Step-Up",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0010",
    title: "Single-Leg Sit-to-Stand",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0011",
    title: "Romanian Deadlift",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0012",
    title: "Trap-Bar Deadlift",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0013",
    title: "Conventional Deadlift",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0014",
    title: "Kettlebell Deadlift",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0015",
    title: "Single-Leg RDL",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0016",
    title: "Hip Thrust",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0017",
    title: "Glute Bridge",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0018",
    title: "Cable Pull-Through",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0019",
    title: "Hamstring Curl",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0020",
    title: "Nordic Curl Regression",
    sourceCategory: "Lower Body Strength",
    movementPattern: "lower_body_strength",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0021",
    title: "Push-Up",
    sourceCategory: "Upper Push",
    movementPattern: "upper_push",
    equipment: "bodyweight",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0022",
    title: "Incline Push-Up",
    sourceCategory: "Upper Push",
    movementPattern: "upper_push",
    equipment: "bodyweight",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0023",
    title: "Dumbbell Bench Press",
    sourceCategory: "Upper Push",
    movementPattern: "upper_push",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0024",
    title: "Barbell Bench Press",
    sourceCategory: "Upper Push",
    movementPattern: "upper_push",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0025",
    title: "Half-Kneeling Landmine Press",
    sourceCategory: "Upper Push",
    movementPattern: "upper_push",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0026",
    title: "Dumbbell Overhead Press",
    sourceCategory: "Upper Push",
    movementPattern: "upper_push",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0027",
    title: "Cable Chest Press",
    sourceCategory: "Upper Push",
    movementPattern: "upper_push",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0028",
    title: "Dip Regression",
    sourceCategory: "Upper Push",
    movementPattern: "upper_push",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0029",
    title: "Pike Push-Up",
    sourceCategory: "Upper Push",
    movementPattern: "upper_push",
    equipment: "bodyweight",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0030",
    title: "Scapular Push-Up",
    sourceCategory: "Upper Push",
    movementPattern: "upper_push",
    equipment: "bodyweight",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0031",
    title: "Assisted Pull-Up",
    sourceCategory: "Upper Pull",
    movementPattern: "upper_pull",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0032",
    title: "Lat Pulldown",
    sourceCategory: "Upper Pull",
    movementPattern: "upper_pull",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0033",
    title: "One-Arm Dumbbell Row",
    sourceCategory: "Upper Pull",
    movementPattern: "upper_pull",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0034",
    title: "Seated Cable Row",
    sourceCategory: "Upper Pull",
    movementPattern: "upper_pull",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0035",
    title: "Chest-Supported Row",
    sourceCategory: "Upper Pull",
    movementPattern: "upper_pull",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0036",
    title: "Inverted Row",
    sourceCategory: "Upper Pull",
    movementPattern: "upper_pull",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0037",
    title: "Face Pull",
    sourceCategory: "Upper Pull",
    movementPattern: "upper_pull",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0038",
    title: "Band Pull-Apart",
    sourceCategory: "Upper Pull",
    movementPattern: "upper_pull",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0039",
    title: "Straight-Arm Pulldown",
    sourceCategory: "Upper Pull",
    movementPattern: "upper_pull",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0040",
    title: "Scapular Pull-Up",
    sourceCategory: "Upper Pull",
    movementPattern: "upper_pull",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0041",
    title: "Farmer Carry",
    sourceCategory: "Core / Carry",
    movementPattern: "core_and_carry",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0042",
    title: "Suitcase Carry",
    sourceCategory: "Core / Carry",
    movementPattern: "core_and_carry",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0043",
    title: "Front-Rack Carry",
    sourceCategory: "Core / Carry",
    movementPattern: "core_and_carry",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0044",
    title: "Overhead Carry",
    sourceCategory: "Core / Carry",
    movementPattern: "core_and_carry",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0045",
    title: "Dead Bug",
    sourceCategory: "Core / Carry",
    movementPattern: "core_and_carry",
    equipment: "bodyweight",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0046",
    title: "Bird Dog",
    sourceCategory: "Core / Carry",
    movementPattern: "core_and_carry",
    equipment: "bodyweight",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0047",
    title: "Pallof Press",
    sourceCategory: "Core / Carry",
    movementPattern: "core_and_carry",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0048",
    title: "Side Plank",
    sourceCategory: "Core / Carry",
    movementPattern: "core_and_carry",
    equipment: "bodyweight",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0049",
    title: "Front Plank",
    sourceCategory: "Core / Carry",
    movementPattern: "core_and_carry",
    equipment: "bodyweight",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0050",
    title: "Bear Crawl",
    sourceCategory: "Core / Carry",
    movementPattern: "core_and_carry",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0051",
    title: "Calf Raise",
    sourceCategory: "Mobility / Resilience",
    movementPattern: "mobility",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0052",
    title: "Tibialis Raise",
    sourceCategory: "Mobility / Resilience",
    movementPattern: "mobility",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0053",
    title: "Copenhagen Plank Regression",
    sourceCategory: "Mobility / Resilience",
    movementPattern: "mobility",
    equipment: "bodyweight",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0054",
    title: "Adductor Rockback",
    sourceCategory: "Mobility / Resilience",
    movementPattern: "mobility",
    equipment: "bodyweight",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0055",
    title: "90/90 Hip Switch",
    sourceCategory: "Mobility / Resilience",
    movementPattern: "mobility",
    equipment: "bodyweight",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0056",
    title: "Hip Flexor Mobilization",
    sourceCategory: "Mobility / Resilience",
    movementPattern: "mobility",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0057",
    title: "Ankle Dorsiflexion Drill",
    sourceCategory: "Mobility / Resilience",
    movementPattern: "mobility",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0058",
    title: "Thoracic Rotation",
    sourceCategory: "Mobility / Resilience",
    movementPattern: "mobility",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0059",
    title: "Wall Slide",
    sourceCategory: "Mobility / Resilience",
    movementPattern: "mobility",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0060",
    title: "Shoulder External Rotation",
    sourceCategory: "Mobility / Resilience",
    movementPattern: "mobility",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0061",
    title: "Jump Rope",
    sourceCategory: "Power / Athletic",
    movementPattern: "power",
    equipment: "varies_by_movement",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0062",
    title: "Pogo Jump",
    sourceCategory: "Power / Athletic",
    movementPattern: "power",
    equipment: "bodyweight",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0063",
    title: "Box Jump Landing",
    sourceCategory: "Power / Athletic",
    movementPattern: "power",
    equipment: "varies_by_movement",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0064",
    title: "Broad Jump Landing",
    sourceCategory: "Power / Athletic",
    movementPattern: "power",
    equipment: "varies_by_movement",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0065",
    title: "Lateral Bound Landing",
    sourceCategory: "Power / Athletic",
    movementPattern: "power",
    equipment: "varies_by_movement",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0066",
    title: "Med-Ball Chest Pass",
    sourceCategory: "Power / Athletic",
    movementPattern: "power",
    equipment: "varies_by_movement",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0067",
    title: "Med-Ball Rotational Throw",
    sourceCategory: "Power / Athletic",
    movementPattern: "power",
    equipment: "varies_by_movement",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0068",
    title: "Sled Push",
    sourceCategory: "Power / Athletic",
    movementPattern: "power",
    equipment: "varies_by_movement",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0069",
    title: "Sled Drag",
    sourceCategory: "Power / Athletic",
    movementPattern: "power",
    equipment: "varies_by_movement",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0070",
    title: "Bike Sprint",
    sourceCategory: "Power / Athletic",
    movementPattern: "power",
    equipment: "varies_by_movement",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0071",
    title: "Treadmill Walk",
    sourceCategory: "Conditioning",
    movementPattern: "conditioning",
    equipment: "varies_by_movement",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0072",
    title: "Incline Walk",
    sourceCategory: "Conditioning",
    movementPattern: "conditioning",
    equipment: "varies_by_movement",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0073",
    title: "Row Ergometer",
    sourceCategory: "Conditioning",
    movementPattern: "conditioning",
    equipment: "varies_by_movement",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0074",
    title: "Elliptical",
    sourceCategory: "Conditioning",
    movementPattern: "conditioning",
    equipment: "varies_by_movement",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0075",
    title: "Stationary Bike",
    sourceCategory: "Conditioning",
    movementPattern: "conditioning",
    equipment: "varies_by_movement",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0076",
    title: "Zone 2 Cardio",
    sourceCategory: "Conditioning",
    movementPattern: "conditioning",
    equipment: "varies_by_movement",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0077",
    title: "Tempo Run",
    sourceCategory: "Conditioning",
    movementPattern: "conditioning",
    equipment: "varies_by_movement",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0078",
    title: "Shuttle Run",
    sourceCategory: "Conditioning",
    movementPattern: "conditioning",
    equipment: "varies_by_movement",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0079",
    title: "Battle Rope",
    sourceCategory: "Conditioning",
    movementPattern: "conditioning",
    equipment: "varies_by_movement",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0080",
    title: "Kettlebell Swing",
    sourceCategory: "Conditioning",
    movementPattern: "conditioning",
    equipment: "varies_by_movement",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0081",
    title: "Biceps Curl",
    sourceCategory: "Accessory",
    movementPattern: "accessory",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0082",
    title: "Hammer Curl",
    sourceCategory: "Accessory",
    movementPattern: "accessory",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0083",
    title: "Triceps Pressdown",
    sourceCategory: "Accessory",
    movementPattern: "accessory",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0084",
    title: "Overhead Triceps Extension",
    sourceCategory: "Accessory",
    movementPattern: "accessory",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0085",
    title: "Lateral Raise",
    sourceCategory: "Accessory",
    movementPattern: "accessory",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0086",
    title: "Rear-Delt Fly",
    sourceCategory: "Accessory",
    movementPattern: "accessory",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0087",
    title: "Cable Wood Chop",
    sourceCategory: "Accessory",
    movementPattern: "accessory",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0088",
    title: "Reverse Crunch",
    sourceCategory: "Accessory",
    movementPattern: "accessory",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0089",
    title: "Hanging Knee Raise",
    sourceCategory: "Accessory",
    movementPattern: "accessory",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0090",
    title: "Cable Crunch",
    sourceCategory: "Accessory",
    movementPattern: "accessory",
    equipment: "dumbbell_cable_or_gym",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0091",
    title: "Breathing Reset",
    sourceCategory: "Recovery / Mobility",
    movementPattern: "recovery",
    equipment: "bodyweight",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0092",
    title: "Box Breathing",
    sourceCategory: "Recovery / Mobility",
    movementPattern: "recovery",
    equipment: "bodyweight",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0093",
    title: "Crocodile Breathing",
    sourceCategory: "Recovery / Mobility",
    movementPattern: "recovery",
    equipment: "bodyweight",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0094",
    title: "Cat-Cow",
    sourceCategory: "Recovery / Mobility",
    movementPattern: "recovery",
    equipment: "bodyweight",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0095",
    title: "Child Pose Reach",
    sourceCategory: "Recovery / Mobility",
    movementPattern: "recovery",
    equipment: "bodyweight",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0096",
    title: "World Greatest Stretch",
    sourceCategory: "Recovery / Mobility",
    movementPattern: "recovery",
    equipment: "bodyweight",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0097",
    title: "Couch Stretch",
    sourceCategory: "Recovery / Mobility",
    movementPattern: "recovery",
    equipment: "bodyweight",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0098",
    title: "Doorway Pec Stretch",
    sourceCategory: "Recovery / Mobility",
    movementPattern: "recovery",
    equipment: "bodyweight",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0099",
    title: "Neck Rotation Mobility",
    sourceCategory: "Recovery / Mobility",
    movementPattern: "recovery",
    equipment: "bodyweight",
    difficulty: "beginner",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
  {
    id: "EX-0100",
    title: "Wrist Mobility Flow",
    sourceCategory: "Recovery / Mobility",
    movementPattern: "recovery",
    equipment: "bodyweight",
    difficulty: "intermediate",
    purpose: "Education and general fitness",
    escalationNote: "Not a rehabilitation prescription. Stop for pain, dizziness, neurologic symptoms, chest pain, or unexpected shortness of breath and route appropriately.",
    author: "Afam Maduka",
    sourceReviewerNote: "Professional reviewer pending",
    sourceScriptNote: "Script draft",
    sourceVideoNote: "Video needed",
    sourceTranscriptNote: "Transcript needed",
    sourceTagsNote: "Tags needed",
    sourceStatus: "Draft",
  },
];

// ---------------------------------------------------------------------------
// The approval matrix, transcribed
// ---------------------------------------------------------------------------

export interface EducationApprovalMatrixRow {
  readonly id: string;
  readonly contentType: string;
  readonly reviewer: string;
  readonly criteria: string;
}

/**
 * Sheet "Approval Matrix" of the education workbook, rows ED-AP-001 to
 * ED-AP-010, verbatim. The shared contract's review requirements are derived
 * from these ten rows and cite them by id, so the mapping can be checked
 * against the source without opening the workbook.
 */
export const EDUCATION_APPROVAL_MATRIX: readonly EducationApprovalMatrixRow[] = [
  {
    id: "ED-AP-001",
    contentType: "General exercise demonstration",
    reviewer: "Afam + qualified fitness reviewer",
    criteria: "Technique, modifications, common errors, equipment, audience",
  },
  {
    id: "ED-AP-002",
    contentType: "Beginner program lesson",
    reviewer: "Fitness reviewer",
    criteria: "Progression, volume language, alternatives, no guarantees",
  },
  {
    id: "ED-AP-003",
    contentType: "Nutrition education",
    reviewer: "Qualified nutrition reviewer / scope owner",
    criteria: "General education only; no disease treatment",
  },
  {
    id: "ED-AP-004",
    contentType: "Sleep / recovery lesson",
    reviewer: "Scope reviewer",
    criteria: "No diagnosis or treatment",
  },
  {
    id: "ED-AP-005",
    contentType: "Pain or injury content",
    reviewer: "Licensed professional reviewer",
    criteria: "Escalation and no self-diagnosis",
  },
  {
    id: "ED-AP-006",
    contentType: "Post-operative content",
    reviewer: "Responsible clinician / rehab professional",
    criteria: "Medical clearance and patient-specific restrictions",
  },
  {
    id: "ED-AP-007",
    contentType: "Neurological condition content",
    reviewer: "Neurology/rehab professional",
    criteria: "Clinical pathway and safety",
  },
  {
    id: "ED-AP-008",
    contentType: "Pregnancy / postpartum content",
    reviewer: "Qualified professional",
    criteria: "Stage and individual clearance",
  },
  {
    id: "ED-AP-009",
    contentType: "Youth content",
    reviewer: "Qualified youth professional + guardian/privacy review",
    criteria: "Age-appropriate scope",
  },
  {
    id: "ED-AP-010",
    contentType: "Exercise tied to product or Care offer",
    reviewer: "Claims + clinical/legal reviewer",
    criteria: "No implied treatment or outcome",
  },
];

// ---------------------------------------------------------------------------
// Sensitive subject detection
// ---------------------------------------------------------------------------

/**
 * Keyword rules that raise the review bar.
 *
 * IMPORTANT SCOPE NOTE. This scanner reads only the SUBJECT fields of a record:
 * the title, the source category, and the purpose. It deliberately never reads
 * the escalation note. Every row's escalation note names pain, dizziness, and
 * neurologic symptoms, because that is what an escalation note is for. Scanning
 * it would flag all 100 rows as neurological content and make the signal
 * meaningless.
 *
 * The rules cover exactly the five subjects the build directive names: injury,
 * surgery, pain, neurological limitation, rehabilitation. `youth`,
 * `pregnancy_postpartum`, and `product_or_care_linked` are NOT derived from
 * text. They describe who a lesson is for and what it is attached to, which is
 * an editorial decision, not something a keyword can settle. Deriving them from
 * a title also misreads ordinary movement names: "Child Pose Reach" is a yoga
 * posture, not youth content. A scanner that flagged it would teach reviewers
 * to ignore the flag.
 */
const SENSITIVE_SUBJECT_RULES: readonly {
  subject: EducationSensitiveSubject;
  pattern: RegExp;
}[] = [
  { subject: "injury", pattern: /\b(?:injur\w*|sprain\w*|strain\w*|tear|torn|acl|rotator cuff)\b/i },
  { subject: "surgery", pattern: /\b(?:surg\w*|post[- ]?op\w*|operative|arthroplasty|replacement)\b/i },
  { subject: "pain", pattern: /\b(?:pain|painful|ache|aching|sciatica)\b/i },
  {
    subject: "neurological_limitation",
    pattern: /\b(?:neurolog\w*|neuropath\w*|stroke|parkinson\w*|multiple sclerosis|spinal cord)\b/i,
  },
  {
    subject: "rehabilitation",
    pattern: /\b(?:rehab\w*|physical therapy|physio\w*|return[- ]to[- ]play|reconditioning)\b/i,
  },
];

/**
 * The subjects this scanner is able to derive. The remaining sensitive subjects
 * are set editorially. Exported so a test can pin the split.
 */
export const TEXT_DERIVED_SENSITIVE_SUBJECTS: readonly EducationSensitiveSubject[] =
  SENSITIVE_SUBJECT_RULES.map((rule) => rule.subject);

/**
 * Derive the sensitive subjects a record carries from its subject text.
 *
 * This is a floor, not a ceiling. An editor may add any sensitive subject to a
 * record; the scanner exists so that obvious injury, surgery, pain,
 * neurological, and rehabilitation content cannot slip through unflagged.
 */
export function deriveSensitiveSubjects(
  ...subjectFields: readonly string[]
): readonly EducationSensitiveSubject[] {
  const found: EducationSensitiveSubject[] = [];
  for (const rule of SENSITIVE_SUBJECT_RULES) {
    if (subjectFields.some((field) => rule.pattern.test(field ?? ""))) {
      if (!found.includes(rule.subject)) found.push(rule.subject);
    }
  }
  return found;
}

// ---------------------------------------------------------------------------
// Projection
// ---------------------------------------------------------------------------

/** Values the workbook uses to mean "not done yet". Never carried into a record. */
const PLACEHOLDER_NOTES = new Set([
  "professional reviewer pending",
  "script draft",
  "video needed",
  "transcript needed",
  "tags needed",
]);

function isPlaceholderNote(value: string): boolean {
  return PLACEHOLDER_NOTES.has(value.trim().toLowerCase());
}

/**
 * Turn a transcribed row into a library record.
 *
 * Every placeholder becomes a null or an empty list. Nothing is upgraded.
 */
export function toEducationRecord(row: ExerciseSourceRow): EducationRecord {
  return {
    id: row.id,
    title: row.title,
    contentType: "general_exercise_demonstration",
    // The workbook assigns no per record audience. It stays null, and the gate
    // reports it as a blocker, rather than being invented from the scope banner.
    audience: null,
    movementPattern: row.movementPattern,
    equipment: row.equipment,
    difficulty: row.difficulty,
    sensitiveSubjects: deriveSensitiveSubjects(row.title, row.sourceCategory, row.purpose),
    escalationNote: row.escalationNote,
    author: row.author,
    // "Professional reviewer pending" is a placeholder, not a reviewer.
    reviews: [],
    transcript: isPlaceholderNote(row.sourceTranscriptNote) ? null : row.sourceTranscriptNote,
    media: null,
    scriptBody: isPlaceholderNote(row.sourceScriptNote) ? null : row.sourceScriptNote,
    approvalState: row.sourceStatus.trim().toLowerCase() === "draft" ? "DRAFT" : "IN_REVIEW",
    reviewDate: null,
    version: 1,
    tags: isPlaceholderNote(row.sourceTagsNote) ? [] : [row.sourceTagsNote],
  };
}

/** The 100 imported exercise records, as the library holds them today. */
export const EXERCISE_LIBRARY: readonly EducationRecord[] =
  EXERCISE_SOURCE_ROWS.map(toEducationRecord);

export function findEducationRecord(id: string): EducationRecord | undefined {
  return EXERCISE_LIBRARY.find((record) => record.id === id);
}

/**
 * The records a surface may actually show.
 *
 * There is no "show the drafts anyway" option. A record reaches a learner only
 * through the shared publication gate.
 */
export function publishedEducationRecords(
  records: readonly EducationRecord[] = EXERCISE_LIBRARY,
): readonly EducationRecord[] {
  return records.filter((record) => evaluatePublication(record).publishable);
}

// ---------------------------------------------------------------------------
// Reporting
// ---------------------------------------------------------------------------

export function exerciseLibraryCounts(): EducationStateCounts {
  return countEducationStates(EXERCISE_LIBRARY);
}

/** How often each blocker code appears across the library, for an operations queue. */
export function blockerHistogram(
  records: readonly EducationRecord[] = EXERCISE_LIBRARY,
): Readonly<Record<string, number>> {
  const counts: Record<string, number> = {};
  for (const record of records) {
    const seen = new Set<string>();
    for (const blocker of evaluatePublication(record).blockers as readonly PublicationBlocker[]) {
      if (seen.has(blocker.code)) continue;
      seen.add(blocker.code);
      counts[blocker.code] = (counts[blocker.code] ?? 0) + 1;
    }
  }
  return counts;
}
