-- ===========================================================================
-- RETRACTED. DO NOT RUN THIS FILE.
--
-- This file previously contained a post-state verification suite written by
-- the agreement verification lane. Its own footer disclosed that the table
-- names were "asserted, not verified", written from the durable-persistence
-- design rather than read from the applied schema.
--
-- They have now been verified against the migrations at 7955f22, and the file
-- was substantially wrong. Retracted rather than patched, because a partly
-- corrected verification file is more dangerous during a launch than no file:
-- an operator reading a green section would be reading a query that did not
-- ask what it appeared to ask.
--
-- WHAT WAS WRONG
--
--   Six table names do not exist anywhere in the schema:
--     research_early_access_orders                -> placements
--     research_early_access_payment_verifications -> verifications
--     research_early_access_tracking_events       -> tracking
--     research_early_access_founder_releases      -> releases
--     research_early_access_supplier_send_events  -> dispatch_events
--     research_early_access_refunds               -> no such table exists
--
--   Three column names do not exist:
--     research_product_variants.purchasable   (no such column)
--     research_product_variants.price_cents   (price is research_product_prices.amount_cents)
--     research_product_variants.audience      (audience is on research_product_prices,
--                                              and its vocabulary is retail / member /
--                                              professional / wholesale / compare_at,
--                                              never 'PRIVATE_EARLY_ACCESS')
--
--   research_products and the remaining names were correct.
--
-- WHY THE ERROR DID NOT REACH AN OPERATOR
--
--   The footer required a to_regclass existence probe to be run FIRST, and it
--   listed exactly the names above, so anyone following the file in order
--   would have seen exists = false and stopped before trusting a zero. The
--   guard worked. The column errors it would NOT have caught, which is the
--   reason for retraction rather than a smaller correction.
--
-- USE THESE INSTEAD. Both are verified.
--
--   docs/early-access-release/evidence/AGREEMENT_POST_STATE.sql
--     The agreement and money proof. 13 statements, every one a select, each
--     emitting its own PASS / FAIL / INFO / COMPARE verdict rather than
--     leaving the operator to count rows. All ten table names in its
--     wrong-price proof were checked against create table statements in the
--     migrations and all ten exist. It reads evidence KEYS, never values, so
--     the query cannot itself print a secret.
--
--   docs/early-access-release/evidence/PRODUCT_CONTROL_POST_STATE.sql
--     The catalogue post-state, against the real schema: 22 approved and
--     active variants, 18 at commerce_approval approved and availability
--     in_stock, Cagrilintide (PEX-028) held, founder releases and 22 supplier
--     confirmations.
--
-- ONE THING WORTH CARRYING ACROSS
--
--   AGREEMENT_POST_STATE.sql check 11 is a total count, marked COMPARE. It
--   only means something if it is run BEFORE the smoke as well as after. Run
--   it first and keep the output. Run only after, and a non-zero count proves
--   nothing either way.
-- ===========================================================================
