/**
 * The production binding state: the reviewed committed artifact.
 *
 * A binding joins a catalog offering variant to an exact Product Control
 * identity, and it is the FIRST link in the only path from a catalog row to a
 * displayed price (binding, then Product Control, then the authoritative
 * resolver, then one approved in-window row). The artifact this reader loads
 * was generated by scripts/research/build-master-offering-bindings.ts from
 * three cross-checked sources (the committed member-safe dataset, the private
 * workbook intake, and a count-verified production read-back), lands in the
 * repository through a reviewable diff, and carries identity only: no amount,
 * no audience, no purchase authority.
 *
 * FAIL CLOSED, NEVER PARTIALLY. A missing, unreadable, or malformed artifact
 * loads as ZERO bindings: every row then truthfully renders "Price on
 * request" and the catalog stays up. A single malformed entry rejects the
 * whole file rather than serving a partial join, because "some prices" from a
 * corrupt artifact is indistinguishable from a wrong catalog.
 *
 * RESOLUTION ORDER mirrors the dataset reader's committed-artifact
 * convention: an explicit operator override wins, then the committed repo
 * artifact found from the working directory with a bounded parent walk, then
 * nothing.
 */

import fs from "node:fs";
import path from "node:path";
import type { MasterOfferingCommerceIdentityBinding } from "./model";
import type { MasterOfferingCommerceBindingReader } from "./product-control-adapter";

export const MASTER_OFFERING_BINDINGS_ENV_VAR = "XENIOS_MASTER_OFFERING_BINDINGS";

/** The committed artifact, repo relative. The bindings build regenerates it. */
export const MASTER_OFFERING_COMMITTED_BINDINGS_PATH = path.posix.join(
  "server",
  "research",
  "master-offerings",
  "data",
  "master-offering-bindings.generated.json",
);

const MAX_PARENT_WALK = 3;
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

interface BindingArtifactEntry {
  offeringId: string;
  offeringVariantId: string;
  productControlSku: string;
  productId: string;
  variantId: string;
}

function bindingCandidatePaths(env: NodeJS.ProcessEnv, cwd: string): readonly string[] {
  const configured = env[MASTER_OFFERING_BINDINGS_ENV_VAR];
  if (typeof configured === "string" && configured.trim() !== "") {
    // Deliberately the ONLY candidate when set. An operator who names a path
    // and gets it wrong must see zero bindings against the path they chose,
    // never a silent fall through to the committed artifact.
    return [path.resolve(cwd, configured.trim())];
  }
  const candidates: string[] = [];
  let directory = cwd;
  for (let step = 0; step <= MAX_PARENT_WALK; step += 1) {
    candidates.push(path.resolve(directory, MASTER_OFFERING_COMMITTED_BINDINGS_PATH));
    const parent = path.dirname(directory);
    if (parent === directory) break;
    directory = parent;
  }
  return candidates;
}

function validEntry(value: unknown): value is BindingArtifactEntry {
  if (value === null || typeof value !== "object") return false;
  const entry = value as Record<string, unknown>;
  return (
    typeof entry.offeringId === "string" &&
    entry.offeringId.startsWith("mo_") &&
    typeof entry.offeringVariantId === "string" &&
    entry.offeringVariantId.startsWith("mov_") &&
    typeof entry.productControlSku === "string" &&
    entry.productControlSku.trim() !== "" &&
    typeof entry.productId === "string" &&
    UUID_PATTERN.test(entry.productId) &&
    typeof entry.variantId === "string" &&
    UUID_PATTERN.test(entry.variantId)
  );
}

/**
 * Load and index the artifact, or explain why not. Exported for the test that
 * proves the committed artifact itself loads; production goes through the
 * reader below.
 */
export function loadBindingIndex(input?: {
  env?: NodeJS.ProcessEnv;
  cwd?: string;
}): { index: Map<string, MasterOfferingCommerceIdentityBinding>; problem: string | null } {
  const env = input?.env ?? process.env;
  const cwd = input?.cwd ?? process.cwd();

  let raw: string | null = null;
  let chosen: string | null = null;
  for (const candidate of bindingCandidatePaths(env, cwd)) {
    try {
      raw = fs.readFileSync(candidate, "utf8");
      chosen = candidate;
      break;
    } catch {
      // Try the next candidate; a final miss is reported below.
    }
  }
  if (raw === null || chosen === null) {
    return { index: new Map(), problem: "no binding artifact found" };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return { index: new Map(), problem: `binding artifact at ${chosen} is not JSON` };
  }
  const artifact = parsed as {
    schemaVersion?: unknown;
    boundCount?: unknown;
    bindings?: unknown;
  };
  if (artifact.schemaVersion !== 1 || !Array.isArray(artifact.bindings)) {
    return {
      index: new Map(),
      problem: `binding artifact at ${chosen} has an unknown shape`,
    };
  }

  const index = new Map<string, MasterOfferingCommerceIdentityBinding>();
  const seenVariantUuids = new Set<string>();
  for (const entry of artifact.bindings) {
    if (!validEntry(entry)) {
      return { index: new Map(), problem: `binding artifact at ${chosen} carries a malformed entry` };
    }
    const key = `${entry.offeringId}|${entry.offeringVariantId}`;
    if (index.has(key) || seenVariantUuids.has(entry.variantId)) {
      return { index: new Map(), problem: `binding artifact at ${chosen} carries a duplicate` };
    }
    seenVariantUuids.add(entry.variantId);
    index.set(key, {
      offeringVariantId: entry.offeringVariantId,
      productId: entry.productId,
      variantId: entry.variantId,
    });
  }
  if (typeof artifact.boundCount === "number" && artifact.boundCount !== index.size) {
    return {
      index: new Map(),
      problem: `binding artifact at ${chosen} declares ${String(artifact.boundCount)} bindings but carries ${index.size}`,
    };
  }
  return { index, problem: null };
}

/**
 * The production reader. The artifact is read once per process, on first use
 * rather than at import so tests and tools that never touch bindings never
 * pay for or depend on the file. A load problem is logged once and the reader
 * then answers null for everything, which the price authority renders as
 * "Price on request".
 */
export function createProductionBindingReader(input?: {
  env?: NodeJS.ProcessEnv;
  cwd?: string;
  log?: (message: string) => void;
}): MasterOfferingCommerceBindingReader {
  let loaded: Map<string, MasterOfferingCommerceIdentityBinding> | null = null;
  return {
    readBinding({ offeringId, offeringVariantId }) {
      if (loaded === null) {
        const { index, problem } = loadBindingIndex(input);
        loaded = index;
        if (problem !== null) {
          (input?.log ?? console.error)(
            `master offerings bindings unavailable, all prices render on request: ${problem}`,
          );
        }
      }
      return loaded.get(`${offeringId}|${offeringVariantId}`) ?? null;
    },
  };
}

/** The instance the composition root wires in. */
export const masterOfferingProductionBindings: MasterOfferingCommerceBindingReader =
  createProductionBindingReader();

/**
 * The pre-artifact state, kept for tests that need a truthful "no bindings"
 * reader. Production no longer wires this in.
 */
export const masterOfferingNoProductionBindings: MasterOfferingCommerceBindingReader = {
  readBinding: () => null,
};
