import { describe, expect, it } from "vitest";
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { EarlyAccessCatalogRow } from "../catalog/early-access-catalog";
import {
  FIRST_RELEASE_CLASSIFICATIONS,
  earlyAccessDerivedBlockers,
  firstReleaseRecommendation,
  firstReleaseShortlist,
  renderFirstReleaseCandidates,
  reviewEarlyAccessCatalog,
  reviewEarlyAccessRow,
} from "./first-release-review";
import {
  CANONICAL_REVIEW_INSTANT,
  projectCanonicalFirstReleaseCatalog,
} from "./first-release-canonical-source";

const DOC_PATH = resolve(
  __dirname,
  "../../../../docs/early-access/FIRST_RELEASE_CANDIDATES.md",
);

const PROVENANCE = [
  "Generated by `server/research/early-access/release/first-release-review.test.ts` from `first-release-canonical-source.ts`, which projects the founder-locked peptide catalog (`shared/research/catalog/peptide-catalog.ts`) through the SAME adapter, declared-facts reader, eligibility gate, and classifier that production uses.",
  "",
  "Two things are stated rather than assumed:",
  "",
  "1. **Inventory.** This repository carries no `research_inventory_lots` rows, so the review runs against an inventory reader that reports no allocatable lots. That is the exact answer production returns for a SKU with no allocatable lots, so every unit reports `FULFILLMENT_UNAVAILABLE`. Re-run this review against production before acting on it.",
  "2. **Product Control status.** Each founder-locked presentation is read as a variant Product Control carries and has approved, because the question here is what we know about these units, not whether the import has run. Everything else Product Control alone establishes is left at the value that blocks: draft status, members-only visibility, unapproved commerce, no price rows, no media.",
  "",
  "No amount is read from the peptide catalog. It holds wholesale costs, draft computations, a superseded published price, and a competitor's shelf price, and a price column here would be one of those. Prices come from Product Control price rows or from a founder release, and from nowhere else.",
];

function row(overrides: Partial<EarlyAccessCatalogRow> = {}): EarlyAccessCatalogRow {
  return {
    productId: "prod-review-0001",
    slug: "review-unit",
    displayName: "Review Unit",
    canonicalName: "Review Unit",
    variantId: "var-review-0001",
    sku: "REVIEW-0001",
    strength: "10 mg",
    presentation: "Single-use vial",
    priceCents: 24_900,
    currency: "USD",
    audience: "member",
    availability: "available",
    offerState: "APPROVAL_REQUIRED_PURCHASE",
    description: "A research catalog item held for internal review.",
    imageState: "none",
    quantityLimit: null,
    supplierReady: true,
    fulfillmentOwner: "mitch",
    disputeStatus: { identity: "cleared", strength: "cleared" },
    purchasable: false,
    blockers: [],
    ...overrides,
  };
}

describe("classifying one unit", () => {
  it("calls a unit approvable when every blocker on it is one a release may bridge", () => {
    const candidate = reviewEarlyAccessRow(
      row({ blockers: ["QUANTITY_LIMIT_MISSING", "PRICE_NOT_APPROVED"] }),
    );
    expect(candidate.classification).toBe("APPROVABLE_FOR_EARLY_ACCESS");
    expect(candidate.nonwaivableBlockers).toEqual([]);
    expect(candidate.waivableBlockers).toEqual([
      "QUANTITY_LIMIT_MISSING",
      "PRICE_NOT_APPROVED",
    ]);
  });

  it("calls a unit with no blockers at all approvable", () => {
    expect(reviewEarlyAccessRow(row({ purchasable: true })).classification).toBe(
      "APPROVABLE_FOR_EARLY_ACCESS",
    );
  });

  it("reports identity before anything a release could bridge", () => {
    const candidate = reviewEarlyAccessRow(
      row({
        blockers: [
          "IDENTITY_DISPUTE_UNRESOLVED",
          "PRICE_NOT_APPROVED",
          "QUANTITY_LIMIT_MISSING",
        ],
      }),
    );
    expect(candidate.classification).toBe("NOT_APPROVABLE_IDENTITY");
    expect(candidate.nonwaivableBlockers).toEqual(["IDENTITY_DISPUTE_UNRESOLVED"]);
  });

  it("reports supplier and fulfilment separately, in that order", () => {
    expect(
      reviewEarlyAccessRow(
        row({ blockers: ["SUPPLIER_NOT_ASSIGNED", "FULFILLMENT_UNAVAILABLE"] }),
      ).classification,
    ).toBe("NOT_APPROVABLE_SUPPLIER");
    expect(
      reviewEarlyAccessRow(row({ blockers: ["FULFILLMENT_UNAVAILABLE"] })).classification,
    ).toBe("NOT_APPROVABLE_FULFILLMENT");
  });

  it("reports the audience gap under price, because it is the only pricing decision it leaves open", () => {
    expect(
      reviewEarlyAccessRow(row({ blockers: ["AUDIENCE_NOT_PERMITTED"] })).classification,
    ).toBe("NOT_APPROVABLE_PRICE");
  });

  it("gives every unit exactly one classification", () => {
    for (const candidate of [
      reviewEarlyAccessRow(row({ purchasable: true })),
      reviewEarlyAccessRow(row({ blockers: ["FULFILLMENT_UNAVAILABLE"] })),
      reviewEarlyAccessRow(row({ blockers: ["IDENTITY_NOT_CONFIRMED"] })),
    ]) {
      expect(FIRST_RELEASE_CLASSIFICATIONS).toContain(candidate.classification);
    }
  });

  it("carries the exact facts a founder needs to act", () => {
    const candidate = reviewEarlyAccessRow(row({ quantityLimit: 3 }));
    expect(candidate.sku).toBe("REVIEW-0001");
    expect(candidate.strength).toBe("10 mg");
    expect(candidate.presentation).toBe("Single-use vial");
    expect(candidate.priceCents).toBe(24_900);
    expect(candidate.supplier).toBe("mitch");
    expect(candidate.fulfillmentMethod).toBe("Manual, shipped by the supplier partner");
    expect(candidate.inventoryState).toBe("available");
    expect(candidate.quantityLimit).toBe(3);
    expect(candidate.productVersion).toMatch(/^[a-f0-9]{64}$/);
    expect(candidate.recommendedAction.length).toBeGreaterThan(0);
  });
});

describe("the blockers the eligibility vocabulary does not emit", () => {
  // R360-BPC157_TB500-15MG_15MG-VIAL is one of the recorded strength disputes,
  // and its two records state different total masses, so it is a contest about
  // the blend's composition.
  const contestedBlend = row({
    sku: "R360-BPC157_TB500-15MG_15MG-VIAL",
    canonicalName: "BPC-157 / TB-500",
    slug: "bpc-157-tb-500-15-15",
    strength: "15 mg / 15 mg",
  });

  it("derives a formula contest from the founder-locked record", () => {
    expect(earlyAccessDerivedBlockers(contestedBlend)).toContain("FORMULA_UNKNOWN");
    expect(reviewEarlyAccessRow(contestedBlend).classification).toBe(
      "NOT_APPROVABLE_FORMULA",
    );
  });

  it("derives a regulatory hold from the founder-locked record", () => {
    // Retatrutide is recorded in the regulatory-hold tier. The join is the SKU,
    // so a row that names one is held no matter what else its record says.
    const held = row({
      sku: "R360-RETATRUTIDE-10MG-VIAL",
      canonicalName: "Retatrutide",
      slug: "retatrutide",
      blockers: [],
      purchasable: true,
    });
    expect(earlyAccessDerivedBlockers(held)).toContain("REGULATORY_HOLD");
    const candidate = reviewEarlyAccessRow(held);
    // A unit Product Control would otherwise call purchasable is still refused,
    // which is the whole reason this blocker is derived rather than declared.
    expect(candidate.classification).toBe("NOT_APPROVABLE_REGULATORY");
    expect(candidate.nonwaivableBlockers).toContain("REGULATORY_HOLD");
    expect(candidate.regulatoryHoldReason).not.toBeNull();
  });

  it("derives nothing for a unit the founder-locked record does not carry", () => {
    expect(earlyAccessDerivedBlockers(row())).toEqual([]);
  });
});

describe("the reviewed first-release list", () => {
  it("classifies every unit and the counts add up", async () => {
    const review = reviewEarlyAccessCatalog(await projectCanonicalFirstReleaseCatalog());
    const total = FIRST_RELEASE_CLASSIFICATIONS.reduce(
      (sum, classification) => sum + review.counts[classification],
      0,
    );
    expect(total).toBe(review.candidates.length);
    expect(review.candidates.length).toBeGreaterThan(0);
  });

  it("never calls a strength-disputed unit approvable", async () => {
    const review = reviewEarlyAccessCatalog(await projectCanonicalFirstReleaseCatalog());
    const disputed = review.candidates.filter(
      (candidate) =>
        candidate.classification === "NOT_APPROVABLE_STRENGTH" ||
        candidate.classification === "NOT_APPROVABLE_FORMULA",
    );
    // The twelve recorded disputes split nine strength, three formula. None of
    // them may ever be approvable, and none may be waivable.
    expect(review.counts.NOT_APPROVABLE_STRENGTH).toBe(9);
    expect(review.counts.NOT_APPROVABLE_FORMULA).toBe(3);
    for (const candidate of disputed) {
      expect(candidate.classification).not.toBe("APPROVABLE_FOR_EARLY_ACCESS");
      expect(candidate.nonwaivableBlockers.length).toBeGreaterThan(0);
    }
  });

  it("holds every unit while no allocatable lot is on file", async () => {
    const review = reviewEarlyAccessCatalog(await projectCanonicalFirstReleaseCatalog());
    expect(review.counts.APPROVABLE_FOR_EARLY_ACCESS).toBe(0);
    for (const candidate of review.candidates) {
      expect(candidate.inventoryState).toBe("unavailable");
    }
  });

  it("names a shortlist that only inventory is holding", async () => {
    const review = reviewEarlyAccessCatalog(await projectCanonicalFirstReleaseCatalog());
    const shortlist = firstReleaseShortlist(review);
    expect(shortlist.length).toBeGreaterThan(0);
    for (const candidate of shortlist) {
      expect(candidate.nonwaivableBlockers).toEqual(["FULFILLMENT_UNAVAILABLE"]);
    }
  });

  it("recommends only the founder-established presentations, and only a few", async () => {
    const review = reviewEarlyAccessCatalog(await projectCanonicalFirstReleaseCatalog());
    const recommended = firstReleaseRecommendation(review);
    // Fifteen products have a founder-established presentation; twelve of them
    // carry a recorded strength dispute, so three remain.
    expect(recommended).toHaveLength(3);
    for (const candidate of recommended) {
      expect(candidate.authoritativePresentation).toBe(true);
      expect(candidate.classification).toBe("NOT_APPROVABLE_FULFILLMENT");
    }
  });
});

describe("the committed document", () => {
  it("still equals what the classifier produces", async () => {
    const review = reviewEarlyAccessCatalog(
      await projectCanonicalFirstReleaseCatalog(new Date(CANONICAL_REVIEW_INSTANT)),
    );
    const rendered = renderFirstReleaseCandidates({ review, provenance: PROVENANCE });
    if (process.env.UPDATE_FIRST_RELEASE_DOC === "1") {
      mkdirSync(dirname(DOC_PATH), { recursive: true });
      writeFileSync(DOC_PATH, rendered, "utf8");
    }
    // A reviewed list that has drifted from the code is worse than no list,
    // because somebody will act on it.
    expect(readFileSync(DOC_PATH, "utf8").replace(/\r\n/g, "\n")).toBe(rendered);
  });
});
