-- ==========================================================================
-- XENIOS RESEARCH - FULL PRODUCTION MIGRATION BUNDLE (pending migrations 9-26)
-- ==========================================================================
-- Generated by concatenating the pending, reviewed migration files in the
-- order defined in docs/research-launch/FULL_PRODUCTION_MIGRATION_MANIFEST.md.
--
-- Migrations 1-8 are ALREADY RUN in production (see supabase/MIGRATIONS.md).
-- This bundle applies only the pending set. Every file is idempotent
-- (create table if not exists), enables row level security, and adds NO public
-- policy: access is service-role only by design (see the RLS resolution note in
-- supabase/production/research-production-rollback-notes.md). Safe to re-run.
--
-- Apply in the Supabase SQL Editor (production project) AFTER review.
-- Do NOT edit a constraint to relax it; the append-only ledger triggers and the
-- unique idempotency constraints are load-bearing safety controls.
-- ==========================================================================


-- --------------------------------------------------------------------------
-- MIGRATION 9: research-member-billing.sql  (member billing state)
-- --------------------------------------------------------------------------

-- xenios research member billing state (ACCOUNT-EMAIL-SYSTEMS-001).
-- Run once in the Supabase SQL Editor. Safe to re-run. NOT YET RUN: the code
-- ships tolerant of this migration being absent (a missing billing_state
-- column reads as 'not_started' / verified-legacy for already-active members).
--
-- 1. Widens research_members.status with the dunning/cancellation states the
--    membership lifecycle needs (past_due, cancelled). No existing rows change.
-- 2. Adds billing_state, tracked SEPARATELY from membership status: a single
--    generic "active" cannot represent dunning, refunds, or disputes.

alter table public.research_members
  drop constraint if exists research_members_status_check;
alter table public.research_members
  add constraint research_members_status_check
  check (status in ('pending_activation','active','past_due','paused','cancelled','closed'));

alter table public.research_members
  add column if not exists billing_state text not null default 'not_started'
  check (billing_state in ('not_started','activation_pending','subscription_pending',
                           'active','past_due','cancelled','refunded','disputed'));

-- Members activated through the admin-verified interim flow (both payment
-- references attested) are billing-verified by definition of that flow.
update public.research_members set billing_state = 'active'
  where status = 'active' and billing_state = 'not_started';

-- --------------------------------------------------------------------------
-- MIGRATION 10: research-agreements.sql  (agreement acceptances)
-- --------------------------------------------------------------------------

-- xenios research agreement acceptances (member platform, Website 2 lane).
-- Run once in the Supabase SQL Editor. Safe to re-run.
-- Append-only like research_consent_events: rows are never updated; the
-- latest row per (subject, agreement key) wins. Definitions (keys, versions,
-- titles, draft status) live in code (server/research/agreements.ts); this
-- table records only who decided what, when, against which version and
-- content hash. IP and user agent are stored as sha256 hashes only.
-- RLS on, no policies (service-role access only).

create extension if not exists "pgcrypto";

create table if not exists public.research_agreement_acceptances (
  id                 uuid primary key default gen_random_uuid(),
  subject_type       text not null check (subject_type in ('applicant','member')),
  subject_id         uuid not null,
  agreement_key      text not null,
  agreement_version  text not null,
  content_hash       text not null,
  decision           text not null check (decision in ('accepted','declined')),
  ip_hash            text,
  user_agent_hash    text,
  created_at         timestamptz not null default now()
);

create index if not exists research_agreement_acceptances_subject_idx
  on public.research_agreement_acceptances (subject_type, subject_id, agreement_key, created_at desc);

alter table public.research_agreement_acceptances enable row level security;

-- --------------------------------------------------------------------------
-- MIGRATION 11: research-member-profile.sql  (member profile sections)
-- --------------------------------------------------------------------------

-- xenios research member profile sections (Website 2 lane, member platform
-- G2). Run once in the Supabase SQL Editor. Safe to re-run.
-- One row per (member, section). Section payloads are structured jsonb,
-- validated server-side against the section's zod schema at the recorded
-- schema_version (server/research/profile.ts owns the registry). Sensitive
-- sections are split at the API layer, not here: the service role reads all
-- rows and the server decides which endpoint may serve which section.
-- RLS on, no policies (service-role access only).

create extension if not exists "pgcrypto";

create table if not exists public.research_member_profile_sections (
  id             uuid primary key default gen_random_uuid(),
  member_id      uuid not null,
  section_key    text not null check (section_key in (
                   'basic_information','goals','body_and_routine','fitness',
                   'nutrition','sleep','energy','stress','current_products',
                   'allergies_and_restrictions','basic_safety_context','budget',
                   'routine_complexity','format_preferences',
                   'communication_preferences','media_settings','privacy_choices')),
  schema_version int not null default 1,
  data           jsonb not null default '{}'::jsonb,
  updated_at     timestamptz not null default now(),
  unique (member_id, section_key)
);
create index if not exists research_member_profile_sections_member_idx
  on public.research_member_profile_sections (member_id);

alter table public.research_member_profile_sections enable row level security;

-- --------------------------------------------------------------------------
-- MIGRATION 12: research-assessment.sql  (assessment responses)
-- --------------------------------------------------------------------------

-- xenios research member platform: assessment responses (G3).
-- Run once in the Supabase SQL Editor. Safe to re-run.
-- RLS on, no public policies: only the server's service-role client reads or
-- writes here. Answers are health-adjacent and are keyed by questionId inside
-- one jsonb object; they never appear in logs or notification payloads.

create extension if not exists "pgcrypto";

-- One response per member per definition per mode. The initial assessment is
-- created in_progress on first open (or by the reminder sweep, with a null
-- started_at) and locked by submission; reminders_sent tracks the 0h/24h/48h/
-- 72h milestone emails after activation.
create table if not exists public.research_assessment_responses (
  id                 uuid primary key default gen_random_uuid(),
  member_id          uuid not null,
  definition_id      text not null,
  definition_version int  not null,
  mode               text not null check (mode in ('initial','monthly_check_in')),
  status             text not null default 'in_progress' check (status in ('in_progress','submitted')),
  answers            jsonb not null default '{}'::jsonb,
  started_at         timestamptz,
  last_saved_at      timestamptz,
  submitted_at       timestamptz,
  reminders_sent     int not null default 0,
  created_at         timestamptz default now(),
  unique (member_id, definition_id, mode)
);

-- The reminder sweep scans by definition, mode, and status.
create index if not exists research_assessment_sweep_idx
  on public.research_assessment_responses (definition_id, mode, status);

alter table public.research_assessment_responses enable row level security;

-- --------------------------------------------------------------------------
-- MIGRATION 13: research-blueprint.sql  (blueprints)
-- --------------------------------------------------------------------------

-- xenios research member platform: Whole-Life Blueprint versions (G4).
-- Run once in the Supabase SQL Editor. Safe to re-run.
-- RLS on, no public policies: only the server's service-role client reads or
-- writes here. `content` carries the engine output (the BlueprintView payload
-- minus state and version) as one jsonb object; it is health-derived and is
-- never logged and never placed in notification payloads. `review_comment` is
-- Samuel's internal note and is never returned to members.

create extension if not exists "pgcrypto";

-- One row per member per blueprint version. Rows exist from the preliminary
-- state onward (the earlier states are derived from the assessment). The
-- state machine lives in shared/research/member-platform.ts
-- (BLUEPRINT_TRANSITIONS); transitions are server-owned and optimistic
-- (guarded updates on the current state).
create table if not exists public.research_blueprints (
  id                     uuid primary key default gen_random_uuid(),
  member_id              uuid not null,
  version                int  not null default 1,
  state                  text not null check (state in (
                           'not_started',
                           'assessment_due',
                           'assessment_submitted',
                           'preliminary',
                           'samuel_review',
                           'more_information_needed',
                           'published',
                           'updated'
                         )),
  content                jsonb not null,
  assessment_response_id uuid,
  reviewed_by            text,
  review_comment         text,
  member_visible_message text,
  published_at           timestamptz,
  superseded_by_version  int,
  member_acknowledged_at timestamptz,
  created_at             timestamptz default now(),
  updated_at             timestamptz default now(),
  unique (member_id, version)
);

-- The admin review queue scans by state; member reads scan newest-first.
create index if not exists research_blueprints_state_idx
  on public.research_blueprints (state);
create index if not exists research_blueprints_member_version_idx
  on public.research_blueprints (member_id, version desc);

alter table public.research_blueprints enable row level security;

-- --------------------------------------------------------------------------
-- MIGRATION 14: research-plans.sql  (Xenios 30/90 + plan changes)
-- --------------------------------------------------------------------------

-- xenios research member platform: Xenios 30 / Xenios 90 plans + the one
-- included early plan change per month (Website 2 lane, Wave 2).
-- Run once in the Supabase SQL Editor. Safe to re-run.
-- RLS on, no public policies: only the server's service-role client reads or
-- writes here. Plan content is member-specific coaching material; members see
-- it only through the server routes, and only once published.

create extension if not exists "pgcrypto";

-- Monthly Xenios 30 plans. Publication is versioned per member per month:
-- publishing a newer version marks the earlier published one superseded, so
-- at most one published version per month is current. The content jsonb is
-- the Xenios30Plan payload minus the column-owned fields (planId, state,
-- version, monthLabel, reviewedBy, publishedAt, memberAcknowledgedAt).
-- Recommendation entries inside content reference product slugs and
-- dispositions only, never composition or dosing claims.
create table if not exists public.research_xenios30_plans (
  id                     uuid primary key default gen_random_uuid(),
  member_id              uuid not null,
  month_label            text not null check (month_label ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  version                int  not null default 1,
  state                  text not null default 'draft'
                         check (state in ('draft','samuel_review','published','superseded','archived')),
  content                jsonb not null default '{}'::jsonb,
  reviewed_by            text,
  published_at           timestamptz,
  member_acknowledged_at timestamptz,
  created_at             timestamptz default now(),
  updated_at             timestamptz default now(),
  unique (member_id, month_label, version)
);

-- Member reads filter by member, then pick by state.
create index if not exists research_xenios30_member_state_idx
  on public.research_xenios30_plans (member_id, state);

-- Ninety-day arcs. One published version per member is current; publishing a
-- newer version supersedes the earlier one. The content jsonb is the
-- Xenios90Plan payload minus the column-owned fields (planId, state, version,
-- currentPhase, publishedAt).
create table if not exists public.research_xenios90_plans (
  id            uuid primary key default gen_random_uuid(),
  member_id     uuid not null,
  version       int  not null default 1,
  state         text not null default 'draft'
                check (state in ('draft','samuel_review','published','superseded','archived')),
  current_phase text not null check (current_phase in ('foundation','progression','consolidation')),
  content       jsonb not null default '{}'::jsonb,
  published_at  timestamptz,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now(),
  unique (member_id, version)
);

create index if not exists research_xenios90_member_state_idx
  on public.research_xenios90_plans (member_id, state);

-- The one included early plan change per calendar month. The unique
-- constraint IS the business rule: a second request in the same month cannot
-- exist, no matter how the request arrives, so the limit is structural rather
-- than best-effort application logic.
create table if not exists public.research_plan_change_requests (
  id          uuid primary key default gen_random_uuid(),
  member_id   uuid not null,
  month_label text not null check (month_label ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  reason      text not null,
  created_at  timestamptz default now(),
  unique (member_id, month_label)
);

alter table public.research_xenios30_plans enable row level security;
alter table public.research_xenios90_plans enable row level security;
alter table public.research_plan_change_requests enable row level security;

-- --------------------------------------------------------------------------
-- MIGRATION 15: research-documents.sql  (plan documents)
-- --------------------------------------------------------------------------

-- xenios research member platform: plan documents (Wave 3, contract 9).
-- Run once in the Supabase SQL Editor. Safe to re-run.
-- RLS on, no public policies: only the server's service-role client reads or
-- writes here. `storage_path` is server-only and is NEVER serialized to a
-- member; the member reaches bytes through a short-lived signed grant that also
-- requires their session. `checksum_sha256` is taken over the finished document
-- bytes, so it identifies the artifact and not the request that made it.

create extension if not exists "pgcrypto";

-- One row per member per document type per version. Exactly one row per
-- (member, type) is `current`; publishing a new version archives the prior one
-- and the new row points back at it through supersedes_document_id, so the
-- chain of what replaced what stays readable.
create table if not exists public.research_plan_documents (
  id                     uuid primary key default gen_random_uuid(),
  member_id              uuid not null,
  type                   text not null check (type in (
                           'blueprint_pdf',
                           'fitness_plan_pdf',
                           'nutrition_plan_pdf',
                           'xenios90_roadmap_pdf',
                           'other'
                         )),
  title                  text not null,
  version                int  not null default 1,
  template_version       text not null,
  checksum_sha256        text not null,
  storage_path           text not null,
  status                 text not null default 'current' check (status in ('current', 'archived')),
  supersedes_document_id uuid,
  reviewed_by            text,
  published_at           timestamptz not null,
  acknowledged_at        timestamptz,
  created_at             timestamptz default now(),
  unique (member_id, type, version)
);

-- The member Document Center reads by member and status; version lookups and
-- the "prior current document of this type" read go through the second index.
create index if not exists research_plan_documents_member_status_idx
  on public.research_plan_documents (member_id, status);
create index if not exists research_plan_documents_member_type_version_idx
  on public.research_plan_documents (member_id, type, version desc);

alter table public.research_plan_documents enable row level security;

-- --------------------------------------------------------------------------
-- MIGRATION 16: research-tracker.sql  (tracker observations)
-- --------------------------------------------------------------------------

-- xenios research member platform: tracker observations (G5).
-- Run once in the Supabase SQL Editor. Safe to re-run.
-- RLS on, no public policies: only the server's service-role client reads or
-- writes here. Observations are health-adjacent member content; they are never
-- logged and never placed in notification payloads.
--
-- THERE IS NO COMPOSITE HEALTH SCORE COLUMN, HERE OR ANYWHERE. The six domains
-- are stored and reported side by side. Nothing in this schema combines them
-- into a single number to grow.

create extension if not exists "pgcrypto";

-- One row per observation. `original_value` keeps exactly what the member
-- wrote; `normalized_value` is the number the charts read, and it is null when
-- the entry was words rather than a number (confidence then drops to 'low').
-- The member's words are never discarded and never guessed at.
--
-- `metric_key` allows the full contract vocabulary including data_completeness
-- so the column and shared/research/member-platform.ts stay in step, but the
-- API refuses a member-submitted data_completeness row: that metric is COMPUTED
-- from coverage of the other five domains at read time and is never stored.
--
-- `source` covers the media pipeline's writers (voice_note, photo, video) and
-- the server's own computed writes (system) as well as the member's manual
-- entries; the tracker write route only ever produces 'manual'.
create table if not exists public.research_tracker_observations (
  id               uuid primary key default gen_random_uuid(),
  member_id        uuid not null,
  metric_key       text not null check (metric_key in (
                     'plan_adherence',
                     'body_and_appearance',
                     'sleep_and_recovery',
                     'energy_stress_vitality',
                     'performance_and_function',
                     'data_completeness'
                   )),
  source           text not null check (source in (
                     'manual',
                     'voice_note',
                     'photo',
                     'video',
                     'system'
                   )),
  recorded_at      timestamptz not null,
  timezone         text not null,
  unit             text,
  original_value   text not null,
  normalized_value numeric,
  confidence       text check (confidence in ('low', 'medium', 'high')) default 'high',
  notes            text,
  plan_id          uuid,
  created_at       timestamptz not null default now()
);

-- The progress view reads one member's window, per metric domain, newest first.
create index if not exists research_tracker_observations_member_metric_idx
  on public.research_tracker_observations (member_id, metric_key, recorded_at desc);

-- The whole-window read (every domain at once) and the completeness count.
create index if not exists research_tracker_observations_member_recorded_idx
  on public.research_tracker_observations (member_id, recorded_at desc);

alter table public.research_tracker_observations enable row level security;

-- --------------------------------------------------------------------------
-- MIGRATION 17: research-media.sql  (private media + access log)
-- --------------------------------------------------------------------------

-- xenios research member platform: private media (progress photos, voice
-- notes, exercise videos) plus the access audit and the standing retention
-- election (Website 2 lane, Wave 4).
-- Run once in the Supabase SQL Editor. Safe to re-run.
-- RLS on, no public policies: only the server's service-role client reads or
-- writes here. Members reach their media only through the server routes, and
-- only through short-lived signed URLs minted per request.
--
-- HARD RULES this schema exists to keep honest:
-- - No facial recognition. `has_face_blurred_derivative` records that a blurred
--   IMAGE was produced. There is no column for a face template, embedding, or
--   descriptor anywhere, because none is ever computed or stored.
-- - No public URLs. Storage paths live in these columns and are NEVER returned
--   to a browser; the API returns signed URLs only.
-- - No advertising or analytics egress. Nothing here is exported to a
--   marketing or measurement destination.
-- - A failed processing job NEVER deletes the only safe copy. Raw deletion is
--   gated on processing_state = 'processed' plus the delete election.

create extension if not exists "pgcrypto";

-- One row per uploaded object. The row is created at intent time (state
-- 'uploaded') so an abandoned upload is still accounted for and sweepable.
-- retention_election is copied onto the row at intent from the member's
-- standing election, so the rule that applied to THIS upload is auditable even
-- after the member changes their standing preference later.
create table if not exists public.research_private_media (
  id                            uuid primary key default gen_random_uuid(),
  member_id                     uuid not null,
  kind                          text not null check (kind in (
                                  'progress_photo',
                                  'voice_note',
                                  'exercise_video'
                                )),
  processing_state              text not null default 'uploaded' check (processing_state in (
                                  'uploaded',
                                  'scanning',
                                  'processing',
                                  'processed',
                                  'processing_failed',
                                  'deleted'
                                )),
  retention_election            text not null check (retention_election in (
                                  'retain_raw',
                                  'delete_raw_after_processing'
                                )),
  raw_storage_path              text,
  derivative_storage_path       text,
  transcript_text               text,
  face_blur_requested           boolean not null default false,
  -- Set when a malware scan reports the object unclean. Access to every
  -- variant is refused for a quarantined row even if a storage delete was
  -- refused and the pointer is still present for a retry sweep.
  quarantined                   boolean not null default false,
  has_face_blurred_derivative   boolean default false,
  duration_seconds              int,
  captured_at                   timestamptz,
  uploaded_at                   timestamptz not null default now(),
  raw_deleted_at                timestamptz,
  created_at                    timestamptz default now()
);

-- The member's own list, newest first.
create index if not exists research_private_media_member_uploaded_idx
  on public.research_private_media (member_id, uploaded_at desc);

-- The access audit: one row per granted signed URL. Written BEFORE the URL is
-- minted, so there is no access without an audit record.
create table if not exists public.research_media_access_log (
  id          uuid primary key default gen_random_uuid(),
  media_id    uuid not null,
  member_id   uuid not null,
  variant     text not null check (variant in ('raw', 'face_blurred', 'transcript')),
  accessed_at timestamptz not null default now()
);

create index if not exists research_media_access_log_member_idx
  on public.research_media_access_log (member_id, accessed_at desc);
create index if not exists research_media_access_log_media_idx
  on public.research_media_access_log (media_id, accessed_at desc);

-- The member's STANDING retention election. Separate from the per-row copy so
-- the preference survives with no media rows (a member may choose before their
-- first upload) and so changing it never rewrites the historical record of what
-- applied to an earlier upload.
create table if not exists public.research_media_retention_elections (
  member_id          uuid primary key,
  retention_election text not null check (retention_election in (
                       'retain_raw',
                       'delete_raw_after_processing'
                     )),
  created_at         timestamptz default now(),
  updated_at         timestamptz default now()
);

alter table public.research_private_media enable row level security;
alter table public.research_media_access_log enable row level security;
alter table public.research_media_retention_elections enable row level security;

-- --------------------------------------------------------------------------
-- MIGRATION 18: research-questions.sql  (questions + Telegram links)
-- --------------------------------------------------------------------------

-- xenios research member platform: member questions and the Telegram link
-- (Website 2 lane, Wave 5).
-- Run once in the Supabase SQL Editor. Safe to re-run.
-- RLS on, no public policies: only the server's service-role client reads or
-- writes here. Members reach their own questions only through the server
-- routes, which scope every read and write by the session's member id.
--
-- HARD RULES this schema exists to keep honest:
-- - No queue position, anywhere. There is no column for a rank, a place in
--   line, or a count of anyone else's work, because a member is never shown
--   how many people are ahead of them and the server has nothing to serialize
--   even if a payload tried.
-- - sla_target_at is a TARGET, not a promise. It exists so Samuel's queue can
--   sort by what is aging, not so the member is told an answer is guaranteed
--   by a clock.
-- - A closed question is not reopened. A member who wants to continue files a
--   follow-up, linked by follow_up_of_question_id, so the record of what was
--   asked and answered stays intact.
-- - The raw link token is NEVER stored. Only its SHA-256 hash lands here, so a
--   database copy cannot be replayed to link a chat to a member's account.
-- - Telegram is never the system of record. chat_ref and display_name are
--   routing and display details; the questions, answers, and everything else
--   live in the tables above and in the member's account.

create extension if not exists "pgcrypto";

-- One row per question a member asked, whatever door it came through.
-- answered_by holds a DISPLAY NAME only ("Samuel"), never an admin email
-- address, because this row is serialized to the member who asked.
create table if not exists public.research_member_questions (
  id                      uuid primary key default gen_random_uuid(),
  member_id               uuid not null,
  -- Not null with a default: the frozen contract types category as required,
  -- so a row without one would serialize a shape the UI cannot receive.
  category                text not null default 'other' check (category in (
                            'plan',
                            'product',
                            'account',
                            'shipping',
                            'privacy',
                            'other'
                          )),
  -- The member overview counts open questions off this column, so it is not
  -- nullable and it defaults to the state a brand new question is really in.
  status                  text not null default 'pending' check (status in (
                            'pending',
                            'being_reviewed',
                            'more_information_needed',
                            'answer_ready',
                            'completed'
                          )),
  source                  text not null default 'web' check (source in (
                            'web',
                            'telegram_text',
                            'telegram_voice'
                          )),
  body_text               text,
  -- A voice question carries a reference to its transcript in the private
  -- media table rather than the audio or the text itself.
  transcript_media_id     uuid,
  answer_text             text,
  answered_at             timestamptz,
  answered_by             text,
  rating                  int check (rating between 1 and 5),
  -- Set when this question continues a COMPLETED one. Closed questions get
  -- linked follow-ups rather than being reopened.
  follow_up_of_question_id uuid,
  sla_target_at           timestamptz,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

-- The member's own list, newest first.
create index if not exists research_member_questions_member_created_idx
  on public.research_member_questions (member_id, created_at desc);

-- Samuel's queue: what is open, ordered by what is aging fastest.
create index if not exists research_member_questions_status_sla_idx
  on public.research_member_questions (status, sla_target_at);

-- The one-time Telegram link. A row is minted when the member asks to link,
-- and is spent exactly once when the bot presents the matching token.
--
-- link_token_hash is the SHA-256 of the token. The raw token is shown to the
-- member once, in the response that mints it, and is never written down here
-- or anywhere else. The unique constraint is what makes a duplicate token
-- impossible to insert; used_at is what makes a replay impossible to spend.
create table if not exists public.research_telegram_links (
  id              uuid primary key default gen_random_uuid(),
  member_id       uuid not null,
  link_token_hash text not null unique,
  chat_ref        text,
  display_name    text,
  linked_at       timestamptz,
  revoked_at      timestamptz,
  expires_at      timestamptz not null,
  used_at         timestamptz,
  created_at      timestamptz default now()
);

create index if not exists research_telegram_links_member_idx
  on public.research_telegram_links (member_id);

-- One active link per chat, enforced by the database rather than by a query
-- that hopes for a single row. Without this, a chat could resolve to two
-- members and a message could be attributed to the wrong one.
create unique index if not exists research_telegram_links_active_chat_idx
  on public.research_telegram_links (chat_ref)
  where used_at is not null and revoked_at is null and chat_ref is not null;

alter table public.research_member_questions enable row level security;
alter table public.research_telegram_links enable row level security;

-- --------------------------------------------------------------------------
-- MIGRATION 19: research-sla-events.sql  (SLA escalation ledger)
-- --------------------------------------------------------------------------

-- xenios research member platform: the SLA event ledger (Website 2 lane,
-- Wave 5).
-- Run once in the Supabase SQL Editor. Safe to re-run.
-- RLS on, no policies: only the server's service-role client reads or writes
-- here. Nothing in this table is member-facing.
--
-- WHAT THIS TABLE IS: the claim ledger for SLA notifications sent to Infinity.
-- One row means "this subject's at-risk (or breach) notification has been
-- claimed by a sweep". The unique constraint IS the idempotency: a subject
-- emits at_risk once and breached once, ever, no matter how many sweeps run,
-- how many workers run them, or how late they run.
--
-- WHAT THIS TABLE IS NOT: it is not a copy of member data. There is no column
-- for a name, an email, a health answer, a question body, or a token, because
-- none of those may cross the Infinity boundary (see infinity-provider.ts).
-- subject_ref is an opaque internal reference and subject_id is the uuid the
-- unique constraint is built on.
--
-- delivered = false means the claim exists but the provider refused (disabled,
-- unconfigured, or a transport error). A later sweep RETRIES the delivery
-- against the same claim; the claim is never deleted, so a flapping provider
-- can never produce a duplicate notification.

create extension if not exists "pgcrypto";

create table if not exists public.research_sla_events (
  id           uuid primary key default gen_random_uuid(),
  kind         text not null check (kind in (
                 'assessment_deadline',
                 'blueprint_review',
                 'monthly_plan_review',
                 'question_response'
               )),
  -- Opaque routing reference (member id, blueprint id, plan id, question id).
  subject_ref  text not null,
  -- NOT NULL is load bearing: Postgres treats NULLs as distinct in a unique
  -- constraint, so a nullable column here would silently allow unlimited
  -- duplicate claims and defeat the idempotency this table exists to provide.
  subject_id   uuid not null,
  deadline_at  timestamptz not null,
  phase        text not null check (phase in ('at_risk', 'breached')),
  emitted_at   timestamptz not null default now(),
  -- False until the provider confirms the emit. A retry sweep flips it true;
  -- it never causes a second claim.
  delivered    boolean not null default false,
  unique (kind, subject_id, phase)
);

-- The retry sweep's read: undelivered claims, oldest first.
create index if not exists research_sla_events_undelivered_idx
  on public.research_sla_events (delivered, emitted_at);

-- The admin sla_risk queue's read: what fired for this kind and when.
create index if not exists research_sla_events_kind_emitted_idx
  on public.research_sla_events (kind, emitted_at desc);

alter table public.research_sla_events enable row level security;

-- --------------------------------------------------------------------------
-- MIGRATION 20: research-catalog.sql  (products + provenanced facts)
-- --------------------------------------------------------------------------

-- xenios research catalog (Website 3, G6). DRAFT, NOT RUN as of 2026-07-21.
-- Run once in the Supabase SQL Editor. Safe to re-run. RLS enabled, no public
-- policies; server-only access, matching every other research table.
--
-- Persists: shared/research/catalog.ts (CatalogProduct, ProvenancedFact, lanes,
-- availability, LaneDecisionState, SupplementCandidate) and
-- server/research/catalog/legacy-adapter.ts.
--
-- THE CENTRAL RULE OF THIS FILE: a supplier fact never stands alone. Each carries
-- its own confirmation state and source, because 32 facts across the 15 SKUs are
-- unconfirmed and 13 are disputed. Unconfirmed data must be structurally
-- distinguishable from confirmed data at rest, not only in application code.

create extension if not exists "pgcrypto";

create table if not exists public.research_products (
  id                     uuid primary key default gen_random_uuid(),
  sku                    text not null unique,
  slug                   text not null unique,
  display_name           text not null,

  lane                   text not null
                           check (lane in ('supplement','research_material','quantum',
                                           'future_clinical','non_product_program')),
  -- A held-open lane is a pending founder decision. It blocks purchase on its own so
  -- the placeholder cannot ship as a quiet default.
  lane_decision          text not null default 'decided'
                           check (lane_decision in ('decided','needs_samuel_decision')),

  availability           text not null default 'documentation_review'
                           check (availability in ('in_stock','low_stock','out_of_stock','waitlist',
                                                   'documentation_review','commerce_review',
                                                   'temporarily_unavailable','coming_soon')),
  commerce_approval      text not null default 'blocked_pending_written_approval'
                           check (commerce_approval in ('approved','blocked_pending_written_approval',
                                                        'blocked_by_lane','blocked_by_documentation')),
  fulfillment_owner      text not null default 'not_assigned'
                           check (fulfillment_owner in ('mitch','xenios','not_assigned')),

  guide_state            text not null default 'guide_in_development'
                           check (guide_state in ('guide_published','guide_updated','guide_in_review',
                                                  'guide_in_development','guide_coming_soon')),
  quality_document_state text not null default 'missing'
                           check (quality_document_state in ('approved','pending','missing','expired')),
  storage_data_state     text not null default 'missing'
                           check (storage_data_state in ('approved','pending','missing','expired')),
  shipping_profile_state text not null default 'missing'
                           check (shipping_profile_state in ('approved','pending','missing','expired')),

  subscription_eligible  boolean not null default false,
  -- Alternate spellings kept searchable. epitalon and epithalon both appear in the
  -- literature and no canonical scientific label has been chosen.
  name_aliases           text[] not null default '{}',
  last_reviewed          date,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);
create index if not exists research_products_lane_idx on public.research_products (lane);
create index if not exists research_products_availability_idx on public.research_products (availability);

-- One row per supplier fact, so confirmation state cannot be separated from the value.
create table if not exists public.research_product_facts (
  id             uuid primary key default gen_random_uuid(),
  product_id     uuid not null references public.research_products (id) on delete cascade,
  fact_key       text not null
                   check (fact_key in ('composition','strength','format','price_cents',
                                       'shelf_life','storage','coa','purity','sterility')),
  -- Text for every fact, including price, so an unconfirmed value is never coerced
  -- into a number a surface might render as money.
  fact_value     text,
  confirmation   text not null default 'not_confirmed'
                   check (confirmation in ('confirmed','supplier_reported',
                                           'unverified_legacy','not_confirmed')),
  source_kind    text not null default 'none'
                   check (source_kind in ('supplier_document','coa','legacy_catalog_file',
                                          'founder_statement','none')),
  source_ref     text,
  -- Set when two sources disagree. A conflict blocks member display outright,
  -- independently of confirmation state. KLOW composition is the live example.
  conflict_note  text,
  recorded_at    timestamptz not null default now(),

  -- A confirmed fact must have a value and a real source. This is the constraint that
  -- makes "confirmed" mean something at rest rather than only in the service layer.
  constraint research_product_facts_confirmed_needs_proof
    check (confirmation <> 'confirmed'
           or (fact_value is not null and source_kind in ('supplier_document','coa'))),
  constraint research_product_facts_unique_per_product unique (product_id, fact_key)
);
create index if not exists research_product_facts_product_idx on public.research_product_facts (product_id);
create index if not exists research_product_facts_unconfirmed_idx
  on public.research_product_facts (confirmation) where confirmation <> 'confirmed';

create table if not exists public.research_product_goals (
  product_id uuid not null references public.research_products (id) on delete cascade,
  goal_key   text not null
               check (goal_key in ('get_leaner','build_muscle','recover_faster','sleep_better',
                                   'think_sharper','feel_more_energized','age_better','look_better',
                                   'gut_and_immune_health','intimacy_and_vitality','everyday_health')),
  primary key (product_id, goal_key)
);

create table if not exists public.research_product_guide_links (
  product_id uuid not null references public.research_products (id) on delete cascade,
  guide_slug text not null,
  primary key (product_id, guide_slug)
);

create table if not exists public.research_product_prohibited_claims (
  id         uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.research_products (id) on delete cascade,
  claim_text text not null,
  reason     text not null
);
create index if not exists research_product_prohibited_claims_product_idx
  on public.research_product_prohibited_claims (product_id);

create table if not exists public.research_product_open_questions (
  id           uuid primary key default gen_random_uuid(),
  product_id   uuid not null references public.research_products (id) on delete cascade,
  question     text not null,
  resolved_at  timestamptz,
  resolved_by  text,
  created_at   timestamptz not null default now()
);
create index if not exists research_product_open_questions_open_idx
  on public.research_product_open_questions (product_id) where resolved_at is null;

-- Supplement candidates. Nothing here is sellable: xenios holds no written reseller
-- authorization from any brand, so the default is NOT AUTHORIZED on every row.
create table if not exists public.research_supplement_candidates (
  id                     uuid primary key default gen_random_uuid(),
  brand                  text not null,
  exact_name             text not null,
  official_url           text,
  category               text not null,
  foundation_role        text not null default 'specialty'
                           check (foundation_role in ('core','conditional','specialty')),
  athlete_testing_relevant boolean not null default false,
  reseller_authorization text not null default 'not_authorized'
                           check (reseller_authorization in ('not_authorized','requested',
                                                             'authorized_in_writing')),
  commercial_state       text not null default 'candidate'
                           check (commercial_state in ('candidate','authorization_pending',
                                                       'approved','rejected','unavailable')),
  inventory_model        text not null default 'not_confirmed'
                           check (inventory_model in ('not_confirmed','stocked','drop_ship')),
  subscription_eligible  boolean not null default false,
  duplicate_nutrient_flags text[] not null default '{}',
  interaction_review_flags text[] not null default '{}',
  last_verified          date,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),

  -- Approval requires written authorization. Enforced here so no code path can mark a
  -- candidate sellable without it.
  constraint research_supplement_candidates_approved_needs_authorization
    check (commercial_state <> 'approved' or reseller_authorization = 'authorized_in_writing'),
  constraint research_supplement_candidates_unique_name unique (brand, exact_name)
);
create index if not exists research_supplement_candidates_state_idx
  on public.research_supplement_candidates (commercial_state);

alter table public.research_products                    enable row level security;
alter table public.research_product_facts               enable row level security;
alter table public.research_product_goals               enable row level security;
alter table public.research_product_guide_links         enable row level security;
alter table public.research_product_prohibited_claims   enable row level security;
alter table public.research_product_open_questions      enable row level security;
alter table public.research_supplement_candidates       enable row level security;

-- --------------------------------------------------------------------------
-- MIGRATION 21: research-inventory-lots.sql  (lots, quality docs, FEFO)
-- --------------------------------------------------------------------------

-- xenios research inventory, lots, and quality (Website 3, G7).
-- DRAFT, NOT RUN as of 2026-07-21. Run once in the Supabase SQL Editor. Safe to
-- re-run. RLS enabled, no public policies; server-only access.
--
-- Persists: server/research/inventory/lots.ts (InventoryLot, LotDisposition,
-- QualityDocuments, FEFO allocation, recall traceability).
--
-- THE RULE THIS SCHEMA ENCODES: a lot must EARN the right to ship. Unknown data is
-- never acceptable data. Shelf life is never invented, so an unknown expiry is null
-- and null blocks allocation rather than defaulting to fine.

create extension if not exists "pgcrypto";

create table if not exists public.research_inventory_lots (
  id                  uuid primary key default gen_random_uuid(),
  lot_id              text not null unique,
  sku                 text not null,
  owner               text not null check (owner in ('mitch','xenios')),

  disposition         text not null default 'quarantined'
                        check (disposition in ('available','allocated','picked','packed','shipped',
                                               'quarantined','quality_hold','temperature_hold',
                                               'damaged','expired','recalled','destroyed')),
  quantity_available  integer not null default 0 check (quantity_available >= 0),

  -- Nullable on purpose. Null means unknown, and unknown blocks allocation.
  manufactured_date   date,
  expiry_date         date,
  retest_date         date,
  shelf_life_source   text not null default 'not_confirmed'
                        check (shelf_life_source in ('supplier_document','coa','not_confirmed')),

  excursion           text not null default 'none'
                        check (excursion in ('none','pending_review','cleared','rejected')),
  recalled            boolean not null default false,
  recalled_at         timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  constraint research_lots_recalled_has_date
    check (recalled = false or recalled_at is not null)
);
create index if not exists research_lots_sku_idx on public.research_inventory_lots (sku);
-- FEFO reads earliest expiry first among allocatable lots, so this is the hot index.
create index if not exists research_lots_fefo_idx
  on public.research_inventory_lots (sku, expiry_date)
  where disposition = 'available' and recalled = false and expiry_date is not null;

-- Quality documents are per LOT, not per product. A COA covering a different lot proves
-- nothing about this one.
create table if not exists public.research_lot_quality_documents (
  id                   uuid primary key default gen_random_uuid(),
  lot_id               uuid not null references public.research_inventory_lots (id) on delete cascade,
  coa_on_file          boolean not null default false,
  identity_confirmed   boolean not null default false,
  purity_confirmed     boolean not null default false,
  -- Tri-state: null means not applicable to this format, false means required and
  -- absent. Collapsing them into a boolean would let "not applicable" read as "missing"
  -- or, far worse, let "missing" read as "fine".
  sterility_confirmed  boolean,
  endotoxin_confirmed  boolean,
  document_ref         text,
  recorded_at          timestamptz not null default now(),
  constraint research_lot_quality_documents_unique unique (lot_id)
);

create table if not exists public.research_lot_excursion_events (
  id          uuid primary key default gen_random_uuid(),
  lot_id      uuid not null references public.research_inventory_lots (id) on delete cascade,
  detected_at timestamptz not null default now(),
  detail      text not null,
  reviewed_by text,
  outcome     text check (outcome in ('cleared','rejected')),
  reviewed_at timestamptz
);
create index if not exists research_lot_excursion_open_idx
  on public.research_lot_excursion_events (lot_id) where reviewed_at is null;

create table if not exists public.research_lot_allocations (
  id             uuid primary key default gen_random_uuid(),
  lot_id         uuid not null references public.research_inventory_lots (id),
  order_id       uuid not null,
  quantity       integer not null check (quantity > 0),
  allocated_at   timestamptz not null default now(),
  released_at    timestamptz
);
create index if not exists research_lot_allocations_order_idx on public.research_lot_allocations (order_id);
create index if not exists research_lot_allocations_lot_idx on public.research_lot_allocations (lot_id);

-- Recall traceability runs FROM THE LOT, because a recall is lot-scoped. Recalling an
-- entire SKU would be both wrong and alarming.
create table if not exists public.research_lot_shipments (
  id          uuid primary key default gen_random_uuid(),
  lot_id      uuid not null references public.research_inventory_lots (id),
  order_id    uuid not null,
  member_id   uuid not null,
  shipped_at  timestamptz not null default now()
);
create index if not exists research_lot_shipments_lot_idx on public.research_lot_shipments (lot_id);
create index if not exists research_lot_shipments_order_idx on public.research_lot_shipments (order_id);

alter table public.research_inventory_lots           enable row level security;
alter table public.research_lot_quality_documents    enable row level security;
alter table public.research_lot_excursion_events     enable row level security;
alter table public.research_lot_allocations          enable row level security;
alter table public.research_lot_shipments            enable row level security;

-- --------------------------------------------------------------------------
-- MIGRATION 22: research-orders.sql  (carts, orders, refunds)
-- --------------------------------------------------------------------------

-- xenios research orders and carts (Website 3, G7). DRAFT, NOT RUN as of 2026-07-21.
-- Run once in the Supabase SQL Editor. Safe to re-run. RLS enabled, no public
-- policies; server-only access.
--
-- Persists: server/research/commerce/{cart,checkout,orders,refunds}.ts and the order
-- state machine in shared/research/commerce.ts.
--
-- TWO RULES THIS SCHEMA ENFORCES RATHER THAN TRUSTS:
--   1. Money is integer cents. No float, no numeric with scale, no money type.
--   2. Every idempotency key is UNIQUE at the database level. Idempotency enforced
--      only in application code is not idempotency under concurrency: two requests
--      can both pass an in-process check and both create an order.

create extension if not exists "pgcrypto";

create table if not exists public.research_carts (
  id         uuid primary key default gen_random_uuid(),
  member_id  uuid not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.research_cart_lines (
  id                          uuid primary key default gen_random_uuid(),
  cart_id                     uuid not null references public.research_carts (id) on delete cascade,
  sku                         text not null,
  quantity                    integer not null check (quantity > 0 and quantity <= 1000),
  purchase_mode               text not null default 'one_time'
                                check (purchase_mode in ('one_time','subscription')),
  subscription_frequency_days integer
                                check (subscription_frequency_days in (30,60,90)),
  added_at                    timestamptz not null default now(),

  -- A subscription line must name a frequency, and a one-time line must not.
  constraint research_cart_lines_subscription_needs_frequency
    check ((purchase_mode = 'subscription') = (subscription_frequency_days is not null)),
  constraint research_cart_lines_unique_sku unique (cart_id, sku)
);
create index if not exists research_cart_lines_cart_idx on public.research_cart_lines (cart_id);

create table if not exists public.research_orders (
  id                      uuid primary key default gen_random_uuid(),
  member_id               uuid not null,
  state                   text not null default 'draft'
                            check (state in ('draft','checkout_pending','payment_authorized',
                                             'manual_review','approved','payment_captured',
                                             'processing','partially_fulfilled','fulfilled',
                                             'delivered','exception','cancelled','refunded','replaced')),
  subtotal_cents          bigint not null check (subtotal_cents >= 0),
  shipping_cents          bigint not null default 0 check (shipping_cents >= 0),
  store_credit_applied_cents bigint not null default 0 check (store_credit_applied_cents >= 0),
  total_cents             bigint not null check (total_cents >= 0),

  -- The amount the provider actually authorized, as the provider reported it. A capture
  -- may never exceed this, so a total recomputed upward after the hold cannot take more
  -- than the member agreed to.
  authorized_amount_cents bigint check (authorized_amount_cents >= 0),
  captured_amount_cents   bigint check (captured_amount_cents >= 0),
  refunded_cents          bigint not null default 0 check (refunded_cents >= 0),

  payment_reference       text,
  -- Client-supplied, so a retried submit cannot create a second order. UNIQUE per member.
  checkout_idempotency_key text,
  last_idempotency_key    text,

  review_triggers         text[] not null default '{}',
  placed_at               timestamptz,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),

  -- A paid state requires provider evidence. Code cannot mark itself paid, and neither
  -- can a manual UPDATE that forgets to set the reference.
  constraint research_orders_paid_needs_provider_reference
    check (state not in ('payment_authorized','payment_captured','refunded')
           or payment_reference is not null),
  constraint research_orders_capture_within_authorization
    check (captured_amount_cents is null
           or authorized_amount_cents is null
           or captured_amount_cents <= authorized_amount_cents),
  constraint research_orders_refund_within_capture
    check (captured_amount_cents is null or refunded_cents <= captured_amount_cents),
  constraint research_orders_idempotency_unique unique (member_id, checkout_idempotency_key)
);
create index if not exists research_orders_member_idx on public.research_orders (member_id);
create index if not exists research_orders_state_idx on public.research_orders (state);
create index if not exists research_orders_review_idx
  on public.research_orders (created_at) where state = 'manual_review';

create table if not exists public.research_order_lines (
  id               uuid primary key default gen_random_uuid(),
  order_id         uuid not null references public.research_orders (id) on delete cascade,
  sku              text not null,
  display_name     text not null,
  quantity         integer not null check (quantity > 0),
  unit_price_cents bigint not null check (unit_price_cents >= 0),
  line_total_cents bigint not null check (line_total_cents >= 0),
  fulfillment_owner text not null check (fulfillment_owner in ('mitch','xenios'))
);
create index if not exists research_order_lines_order_idx on public.research_order_lines (order_id);

-- Append-only state history. Every advance records who caused it and what proved it.
create table if not exists public.research_order_state_events (
  id                  uuid primary key default gen_random_uuid(),
  order_id            uuid not null references public.research_orders (id) on delete cascade,
  from_state          text not null,
  to_state            text not null,
  actor_type          text not null check (actor_type in ('member','admin','system','provider_webhook')),
  actor_id            text,
  provider_reference  text,
  idempotency_key     text,
  occurred_at         timestamptz not null default now()
);
create index if not exists research_order_state_events_order_idx
  on public.research_order_state_events (order_id, occurred_at);

-- Webhook replay protection. UNIQUE is the whole point: a replayed provider event
-- cannot be applied twice even if two instances race to handle it.
create table if not exists public.research_provider_webhook_events (
  id            uuid primary key default gen_random_uuid(),
  provider_name text not null,
  event_id      text not null,
  event_type    text not null,
  received_at   timestamptz not null default now(),
  constraint research_provider_webhook_events_unique unique (provider_name, event_id)
);

create table if not exists public.research_claims (
  id             uuid primary key default gen_random_uuid(),
  order_id       uuid not null references public.research_orders (id),
  member_id      uuid not null,
  sku            text not null,
  lot_id         text,
  -- Founder policy: there are no ordinary returns. Only these five reasons exist.
  reason         text not null
                   check (reason in ('damaged','lost','incorrect','missing','temperature_concern')),
  state          text not null default 'submitted'
                   check (state in ('submitted','under_review','information_requested',
                                    'approved','declined','resolved')),
  resolution     text check (resolution in ('replacement','refund','partial_refund','none')),
  -- Opaque references only. No image bytes and no private media URLs cross this boundary.
  evidence_refs  text[] not null default '{}',
  reviewed_by    text,
  submitted_at   timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists research_claims_member_idx on public.research_claims (member_id);
create index if not exists research_claims_open_idx
  on public.research_claims (submitted_at) where state not in ('resolved','declined');

-- Refund idempotency, durable on purpose. It lived in a per-process map, which stops
-- being idempotency the moment the service restarts or a second instance handles the
-- retry: the map is empty, the key looks new, and real money moves twice.
create table if not exists public.research_refund_keys (
  scope             text primary key,
  refund_reference  text not null,
  recorded_at       timestamptz not null default now()
);

alter table public.research_orders                   enable row level security;
alter table public.research_order_lines              enable row level security;
alter table public.research_order_state_events       enable row level security;
alter table public.research_carts                    enable row level security;
alter table public.research_cart_lines               enable row level security;
alter table public.research_provider_webhook_events  enable row level security;
alter table public.research_claims                   enable row level security;
alter table public.research_refund_keys              enable row level security;

-- --------------------------------------------------------------------------
-- MIGRATION 23: research-subscriptions.sql  (product subscriptions)
-- --------------------------------------------------------------------------

-- xenios research product subscriptions (Website 3, G7).
-- DRAFT, NOT RUN as of 2026-07-21. Run once in the Supabase SQL Editor. Safe to
-- re-run. RLS enabled, no public policies; server-only access.
--
-- Persists: the subscription state machine in shared/research/commerce.ts.
--
-- Note on discounts: subscription discount percentages remain admin-configurable and
-- are deliberately NOT modelled as a published permanent tier here, because unit
-- economics are not complete. A rate lives on the plan row and can change.

create extension if not exists "pgcrypto";

create table if not exists public.research_product_subscriptions (
  id                 uuid primary key default gen_random_uuid(),
  member_id          uuid not null,
  sku                text not null,
  state              text not null default 'pending'
                       check (state in ('pending','active','paused','skip_scheduled',
                                        'rescheduled','payment_issue','cancelled')),
  frequency_days     integer not null check (frequency_days in (30,60,90)),
  quantity           integer not null check (quantity > 0 and quantity <= 1000),

  discount_basis_points integer not null default 0
                          check (discount_basis_points >= 0 and discount_basis_points <= 10000),

  next_charge_at     timestamptz,
  next_shipment_at   timestamptz,
  payment_reference  text,

  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  cancelled_at       timestamptz,

  -- An active subscription needs a schedule. A cancelled one must not keep one, so a
  -- cancelled row cannot quietly continue charging.
  constraint research_subscriptions_active_has_schedule
    check (state <> 'active' or next_charge_at is not null),
  constraint research_subscriptions_cancelled_has_no_schedule
    check (state <> 'cancelled' or (next_charge_at is null and next_shipment_at is null)),
  constraint research_subscriptions_cancelled_has_date
    check (state <> 'cancelled' or cancelled_at is not null)
);
create index if not exists research_subscriptions_member_idx
  on public.research_product_subscriptions (member_id);
create index if not exists research_subscriptions_due_idx
  on public.research_product_subscriptions (next_charge_at) where state = 'active';

-- Append-only action history, so a pause, skip, or reschedule is auditable rather than
-- being an overwrite of the schedule columns.
create table if not exists public.research_subscription_events (
  id              uuid primary key default gen_random_uuid(),
  subscription_id uuid not null references public.research_product_subscriptions (id) on delete cascade,
  action          text not null
                    check (action in ('activate','pause','resume','skip','reschedule',
                                      'report_payment_issue','resolve_payment_issue','cancel')),
  from_state      text not null,
  to_state        text not null,
  actor_type      text not null check (actor_type in ('member','admin','system','provider_webhook')),
  actor_id        text,
  effective_at    timestamptz,
  occurred_at     timestamptz not null default now()
);
create index if not exists research_subscription_events_sub_idx
  on public.research_subscription_events (subscription_id, occurred_at);

alter table public.research_product_subscriptions enable row level security;
alter table public.research_subscription_events   enable row level security;

-- --------------------------------------------------------------------------
-- MIGRATION 24: research-fulfillment.sql  (split fulfillment, shipping)
-- --------------------------------------------------------------------------

-- xenios research fulfillment and shipping (Website 3, G7).
-- DRAFT, NOT RUN as of 2026-07-21. Run once in the Supabase SQL Editor. Safe to
-- re-run. RLS enabled, no public policies; server-only access.
--
-- Persists: server/research/providers/{fulfillment,shipping}.ts and the split
-- fulfillment grouping in server/research/inventory/lots.ts.
--
-- THE PRIVACY CONSTRAINT, STATED SO A LATER MIGRATION DOES NOT QUIETLY BREAK IT:
--
-- A fulfillment partner needs to put a box on a truck. It does NOT need to know that
-- the recipient has a health goal, an assessment, a Blueprint, a tracker history, a
-- referral relationship, or any other order they have ever placed.
--
-- Therefore NO column on research_fulfillment_orders may carry member health data,
-- assessment answers, blueprint content, tracker observations, referral codes, or
-- order history. The outbound payload is built from a fixed allowlist in application
-- code, and this table exists to persist exactly that allowlist and nothing wider.
-- Adding such a column here is a privacy regression, not a convenience.

create extension if not exists "pgcrypto";

create table if not exists public.research_fulfillment_orders (
  id                    uuid primary key default gen_random_uuid(),
  order_id              uuid not null,
  owner                 text not null check (owner in ('mitch','xenios')),
  state                 text not null default 'pending'
                          check (state in ('pending','submitted','accepted','rejected','on_hold',
                                           'shipped','delivered','exception','cancelled')),
  hold_reason           text,

  -- Minimum shipping identity only.
  recipient_name        text not null,
  address_line1         text not null,
  address_line2         text,
  address_city          text not null,
  address_state         char(2) not null,
  address_postal_code   text not null,
  address_country       char(2) not null default 'US',
  -- Present ONLY when the chosen carrier service genuinely requires it, so a partner
  -- does not receive a phone number merely because xenios holds one.
  recipient_phone       text,

  shipping_service      text not null,
  handling_profile      text not null default 'not_confirmed'
                          check (handling_profile in ('ambient','cold_chain','not_confirmed')),

  partner_reference     text,
  transport_mode        text not null default 'manual_export'
                          check (transport_mode in ('manual_export','signed_csv','sftp','api')),
  submitted_at          timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),

  -- Shipping without a confirmed storage decision is a safety failure, not a default.
  constraint research_fulfillment_shipped_needs_handling
    check (state not in ('shipped','delivered') or handling_profile <> 'not_confirmed'),
  constraint research_fulfillment_unique_owner_per_order unique (order_id, owner)
);
create index if not exists research_fulfillment_order_idx on public.research_fulfillment_orders (order_id);
create index if not exists research_fulfillment_open_idx
  on public.research_fulfillment_orders (created_at)
  where state in ('pending','submitted','on_hold','exception');

create table if not exists public.research_fulfillment_lines (
  id                    uuid primary key default gen_random_uuid(),
  fulfillment_order_id  uuid not null references public.research_fulfillment_orders (id) on delete cascade,
  sku                   text not null,
  quantity              integer not null check (quantity > 0),
  lot_id                text
);
create index if not exists research_fulfillment_lines_order_idx
  on public.research_fulfillment_lines (fulfillment_order_id);

create table if not exists public.research_shipments (
  id                    uuid primary key default gen_random_uuid(),
  fulfillment_order_id  uuid not null references public.research_fulfillment_orders (id) on delete cascade,
  carrier               text,
  tracking_number       text,
  service               text,
  shipped_at            timestamptz,
  estimated_delivery    date,
  delivered_at          timestamptz,
  exception_detail      text,
  created_at            timestamptz not null default now()
);
create index if not exists research_shipments_tracking_idx
  on public.research_shipments (tracking_number) where tracking_number is not null;

-- Quote provenance is persisted, because a configured fallback rate must never be
-- presented to a member as if a carrier returned it.
create table if not exists public.research_shipping_quotes (
  id                     uuid primary key default gen_random_uuid(),
  order_id               uuid not null,
  kind                   text not null check (kind in ('configured_fallback','live_carrier_quote')),
  service                text not null check (service in ('standard','expedited_2day','next_day',
                                                          'same_day','temperature_controlled')),
  amount_cents           bigint not null check (amount_cents >= 0),
  -- Null whenever no carrier confirmed a window. A delivery date is never invented.
  earliest_delivery_days integer,
  latest_delivery_days   integer,
  disclosure             text not null,
  quoted_at              timestamptz not null default now(),

  constraint research_shipping_quotes_fallback_has_no_promise
    check (kind <> 'configured_fallback'
           or (earliest_delivery_days is null and latest_delivery_days is null))
);
create index if not exists research_shipping_quotes_order_idx on public.research_shipping_quotes (order_id);

create table if not exists public.research_shipping_profiles (
  id                    uuid primary key default gen_random_uuid(),
  sku                   text not null unique,
  requires_cold_chain   boolean not null default false,
  validated             boolean not null default false,
  validation_document   text,
  notes                 text,
  updated_at            timestamptz not null default now(),

  -- A temperature-controlled claim requires a validated service and a document.
  constraint research_shipping_profiles_cold_chain_needs_validation
    check (requires_cold_chain = false or (validated = true and validation_document is not null))
);

alter table public.research_fulfillment_orders  enable row level security;
alter table public.research_fulfillment_lines   enable row level security;
alter table public.research_shipments           enable row level security;
alter table public.research_shipping_quotes     enable row level security;
alter table public.research_shipping_profiles   enable row level security;

-- --------------------------------------------------------------------------
-- MIGRATION 25: research-partners.sql  (partners, training, attribution)
-- --------------------------------------------------------------------------

-- xenios research partners, attribution, and organizations (Website 3, G8).
-- DRAFT, NOT RUN as of 2026-07-21. Run once in the Supabase SQL Editor. Safe to
-- re-run. RLS enabled, no public policies; server-only access.
--
-- Persists: server/research/partners/{partners,attribution,organizations}.ts and the
-- partner contract in shared/research/distribution.ts.
--
-- TWO FOUNDER RULES, ENCODED HERE SO A LATER MIGRATION CANNOT ADD THEM BACK CASUALLY:
--
--   1. NO RECURSIVE DOWNLINE. There is deliberately NO parent_partner_id, sponsor_id,
--      upline_id, tier, or level column anywhere in this file. A multi-level
--      compensation structure must be impossible to express, not merely discouraged.
--   2. NO COMPENSATION FOR RECRUITING. There is no recruitment event type and no signup
--      bonus table. Commission derives only from eligible net revenue on an attributed
--      order, which lives in research-commission-ledger.sql.

create extension if not exists "pgcrypto";

create table if not exists public.research_partners (
  id                     uuid primary key default gen_random_uuid(),
  -- The member who owns this partner account. Routes resolve the partner FROM the
  -- authenticated member, never from a client-supplied partner id.
  member_id              uuid not null unique,
  role                   text not null
                           check (role in ('member_referral','affiliate','research_rep',
                                           'senior_research_rep','organization_partner',
                                           'private_community_partner','professional_partner',
                                           'future_wholesale','future_institutional')),
  state                  text not null default 'application'
                           check (state in ('application','identity_verification_pending',
                                            'tax_status_pending','payout_status_pending',
                                            'agreement_pending','training_pending',
                                            'certification_pending','active','quality_review',
                                            'suspended','terminated')),
  legal_name             text not null,
  contact_email          text not null,
  -- Written for Samuel, never serialized to the partner. The route layer builds a
  -- partner-facing DTO by explicit construction and this column is not in it.
  internal_notes         text,

  identity_verified      boolean not null default false,
  tax_status             text not null default 'not_started'
                           check (tax_status in ('not_started','submitted','verified','rejected')),
  payout_status          text not null default 'not_started'
                           check (payout_status in ('not_started','submitted','verified','rejected')),

  certified_at           timestamptz,
  certified_by_admin_id  text,
  activated_at           timestamptz,
  activated_by_admin_id  text,
  applied_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),

  -- Activation is a named human decision, so it cannot exist without the admin who made it.
  constraint research_partners_activation_names_an_admin
    check (activated_at is null or activated_by_admin_id is not null),
  constraint research_partners_certification_names_an_admin
    check (certified_at is null or certified_by_admin_id is not null),
  -- An active partner must have cleared every gate.
  constraint research_partners_active_is_fully_gated
    check (state <> 'active'
           or (identity_verified = true
               and tax_status = 'verified'
               and payout_status = 'verified'
               and certified_at is not null
               and activated_at is not null))
);
create index if not exists research_partners_state_idx on public.research_partners (state);

create table if not exists public.research_partner_agreements (
  id                 uuid primary key default gen_random_uuid(),
  partner_id         uuid not null references public.research_partners (id) on delete cascade,
  agreement_key      text not null,
  agreement_version  text not null,
  content_hash       text not null,
  decision           text not null default 'accepted' check (decision in ('accepted','declined')),
  decided_at         timestamptz not null default now(),
  constraint research_partner_agreements_unique unique (partner_id, agreement_key, agreement_version)
);

-- Append-only. A superseded module version is RETAINED, not deleted, because deleting
-- it destroys the evidence of what the partner took and when.
create table if not exists public.research_partner_training (
  id             uuid primary key default gen_random_uuid(),
  partner_id     uuid not null references public.research_partners (id) on delete cascade,
  module_key     text not null
                   check (module_key in ('xenios_membership','privacy_and_sensitive_data',
                                         'product_lanes','ftc_disclosures','claims_restrictions',
                                         'no_diagnosis_or_dosing','lead_handling',
                                         'telegram_boundaries','product_concerns','fraud',
                                         'brand_and_content','organizations','events','security')),
  module_version text not null,
  completed_at   timestamptz not null default now(),
  constraint research_partner_training_unique unique (partner_id, module_key, module_version)
);
create index if not exists research_partner_training_partner_idx
  on public.research_partner_training (partner_id);

create table if not exists public.research_partner_lifecycle_events (
  id          uuid primary key default gen_random_uuid(),
  partner_id  uuid not null references public.research_partners (id) on delete cascade,
  from_state  text not null,
  to_state    text not null,
  -- May contain a suspension or termination reason. Founder-facing only.
  detail      text,
  actor_id    text not null,
  occurred_at timestamptz not null default now()
);
create index if not exists research_partner_lifecycle_partner_idx
  on public.research_partner_lifecycle_events (partner_id, occurred_at);

-- ---------------------------------------------------------------------------
-- Attribution
-- ---------------------------------------------------------------------------

create table if not exists public.research_partner_links (
  id          uuid primary key default gen_random_uuid(),
  partner_id  uuid not null references public.research_partners (id) on delete cascade,
  code        text not null unique,
  channel     text not null check (channel in ('signed_link','code','qr','campaign',
                                               'organization','event','manual')),
  campaign    text,
  organization_id uuid,
  event_id    uuid,
  created_at  timestamptz not null default now(),
  revoked_at  timestamptz
);
create index if not exists research_partner_links_partner_idx on public.research_partner_links (partner_id);

-- The subject key is an opaque, non-reversible identifier for a visitor. A partner
-- learns that a conversion happened, never who it was, so no applicant email, name, or
-- rejection reason may be stored on these rows.
create table if not exists public.research_attribution_touches (
  id           uuid primary key default gen_random_uuid(),
  subject_key  text not null,
  partner_id   uuid not null references public.research_partners (id),
  channel      text not null check (channel in ('signed_link','code','qr','campaign',
                                                'organization','event','manual')),
  set_by_admin_id text,
  occurred_at  timestamptz not null default now(),
  -- Manual attribution overrides the automatic result, so it must name the admin.
  constraint research_attribution_manual_names_an_admin
    check (channel <> 'manual' or set_by_admin_id is not null)
);
create index if not exists research_attribution_subject_idx
  on public.research_attribution_touches (subject_key, occurred_at);

-- One conversion has one winner. UNIQUE on order_id is what makes that true under
-- concurrency rather than only in application code.
create table if not exists public.research_attribution_conversions (
  id            uuid primary key default gen_random_uuid(),
  order_id      uuid not null unique,
  partner_id    uuid not null references public.research_partners (id),
  subject_key   text not null,
  model         text not null default 'last_touch' check (model in ('first_touch','last_touch')),
  converted_at  timestamptz not null default now()
);
create index if not exists research_attribution_conversions_partner_idx
  on public.research_attribution_conversions (partner_id);

-- ---------------------------------------------------------------------------
-- Organizations and events
-- ---------------------------------------------------------------------------

create table if not exists public.research_organizations (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  owner_partner_id uuid not null references public.research_partners (id),
  state        text not null default 'active' check (state in ('active','suspended','terminated')),
  created_at   timestamptz not null default now()
);

create table if not exists public.research_organization_representatives (
  organization_id uuid not null references public.research_organizations (id) on delete cascade,
  partner_id      uuid not null references public.research_partners (id) on delete cascade,
  added_at        timestamptz not null default now(),
  primary key (organization_id, partner_id)
);

create table if not exists public.research_organization_events (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.research_organizations (id) on delete cascade,
  name            text not null,
  campaign        text,
  starts_at       timestamptz,
  created_at      timestamptz not null default now()
);
create index if not exists research_org_events_org_idx on public.research_organization_events (organization_id);

-- RSVPs carry an opaque subject key only. A pasted member name must never land here.
create table if not exists public.research_organization_rsvps (
  id           uuid primary key default gen_random_uuid(),
  event_id     uuid not null references public.research_organization_events (id) on delete cascade,
  subject_key  text not null,
  rsvped_at    timestamptz not null default now(),
  -- An opaque key contains no whitespace, which is the cheapest structural guard
  -- against a pasted human name reaching an organization record.
  constraint research_rsvp_subject_key_is_opaque check (subject_key !~ '\s'),
  constraint research_rsvp_unique unique (event_id, subject_key)
);

create table if not exists public.research_content_assets (
  id                 uuid primary key default gen_random_uuid(),
  partner_id         uuid not null references public.research_partners (id) on delete cascade,
  version            integer not null default 1 check (version > 0),
  title              text not null,
  body               text not null,
  state              text not null default 'submitted'
                       check (state in ('submitted','preapproved','rejected','expired','withdrawn')),
  approved_claims    text[] not null default '{}',
  prohibited_claims  text[] not null default '{}',
  disclosure         text,
  approved_by_admin_id text,
  expires_at         timestamptz,
  created_at         timestamptz not null default now(),

  -- An approved asset must name its approver, carry a disclosure, and expire. A
  -- testimonial cannot make a claim xenios could not make directly, and an approval
  -- that never expires is an approval nobody revisits.
  constraint research_content_preapproved_is_complete
    check (state <> 'preapproved'
           or (approved_by_admin_id is not null and disclosure is not null and expires_at is not null)),
  constraint research_content_unique_version unique (partner_id, title, version)
);
create index if not exists research_content_assets_partner_idx on public.research_content_assets (partner_id);

create table if not exists public.research_content_violations (
  id            uuid primary key default gen_random_uuid(),
  partner_id    uuid not null references public.research_partners (id) on delete cascade,
  asset_id      uuid references public.research_content_assets (id),
  kind          text not null,
  detail        text not null,
  outcome       text not null default 'recorded'
                  check (outcome in ('recorded','correction_required','suspended')),
  recorded_by_admin_id text not null,
  recorded_at   timestamptz not null default now()
);
create index if not exists research_content_violations_partner_idx
  on public.research_content_violations (partner_id, recorded_at);

alter table public.research_partners                     enable row level security;
alter table public.research_partner_agreements           enable row level security;
alter table public.research_partner_training             enable row level security;
alter table public.research_partner_lifecycle_events     enable row level security;
alter table public.research_partner_links                enable row level security;
alter table public.research_attribution_touches          enable row level security;
alter table public.research_attribution_conversions      enable row level security;
alter table public.research_organizations                enable row level security;
alter table public.research_organization_representatives enable row level security;
alter table public.research_organization_events          enable row level security;
alter table public.research_organization_rsvps           enable row level security;
alter table public.research_content_assets               enable row level security;
alter table public.research_content_violations           enable row level security;

-- --------------------------------------------------------------------------
-- MIGRATION 26: research-commission-ledger.sql  (commission + credit ledgers)
-- --------------------------------------------------------------------------

-- xenios research commission and store-credit ledgers (Website 3, G8).
-- DRAFT, NOT RUN as of 2026-07-21. Run once in the Supabase SQL Editor. Safe to
-- re-run. RLS enabled, no public policies; server-only access.
--
-- Persists: server/research/partners/commissions.ts, server/research/providers/payout.ts,
-- and the ledger states in shared/research/distribution.ts.
--
-- THE DEFINING PROPERTY: these ledgers are APPEND-ONLY, enforced by trigger rather
-- than by convention. A correction is a NEW row referencing the original. Balances are
-- derived by summing rows, never stored as a mutable running total, so there is no
-- number an UPDATE could quietly change.

create extension if not exists "pgcrypto";

create table if not exists public.research_commission_ledger (
  id                  uuid primary key default gen_random_uuid(),
  partner_id          uuid not null,
  order_id            uuid not null,
  state               text not null default 'pending'
                        check (state in ('pending','held','approved','payable','paid',
                                         'reversed','disputed','forfeited')),

  -- Integer cents throughout. Rounding is DOWN in application code, so a fraction of a
  -- cent is never invented in the partner's favour.
  eligible_net_cents  bigint not null check (eligible_net_cents >= 0),
  basis_points        integer not null check (basis_points >= 0 and basis_points <= 10000),
  amount_cents        bigint not null check (amount_cents >= 0),

  -- A reversal is a new row pointing at what it reverses, never an edit.
  reverses_ledger_id  uuid references public.research_commission_ledger (id),
  -- The refund or chargeback reference that caused a reversal, so a replayed refund
  -- webhook cannot reverse the same commission twice.
  source_reference    text,

  -- Proof that money actually settled. A row cannot claim paid without it.
  payout_batch_id     uuid,
  payout_reference    text,

  actor_type          text not null default 'system'
                        check (actor_type in ('admin','system')),
  actor_id            text,
  created_at          timestamptz not null default now(),

  constraint research_commission_paid_needs_proof
    check (state <> 'paid' or (payout_reference is not null and payout_batch_id is not null)),
  constraint research_commission_reversal_needs_target
    check (reverses_ledger_id is null or state = 'reversed')
);
create index if not exists research_commission_partner_idx
  on public.research_commission_ledger (partner_id, created_at);
create index if not exists research_commission_order_idx
  on public.research_commission_ledger (order_id);
-- One live accrual per order. A re-attribution must reverse the losing chain before a
-- new partner can accrue, so this partial index refuses a second live accrual outright.
create unique index if not exists research_commission_one_live_accrual_per_order
  on public.research_commission_ledger (order_id)
  where state in ('pending','held','approved','payable','paid');

create table if not exists public.research_store_credit_ledger (
  id           uuid primary key default gen_random_uuid(),
  member_id    uuid not null,
  amount_cents bigint not null,
  state        text not null default 'pending'
                 check (state in ('pending','held','approved','reversed','fraud_flagged')),
  reason       text not null
                 check (reason in ('referral_new_member','referral_referrer',
                                   'service_recovery','manual_adjustment')),
  -- A 14 day hold before referral credit approves, per the founder decision.
  available_at timestamptz,
  reverses_id  uuid references public.research_store_credit_ledger (id),
  actor_type   text not null default 'system' check (actor_type in ('admin','system')),
  actor_id     text,
  created_at   timestamptz not null default now()
);
create index if not exists research_store_credit_member_idx
  on public.research_store_credit_ledger (member_id, created_at);
-- Spendable balance counts approved rows only, so this index serves the hot query.
create index if not exists research_store_credit_spendable_idx
  on public.research_store_credit_ledger (member_id) where state = 'approved';

-- ---------------------------------------------------------------------------
-- Append-only enforcement
-- ---------------------------------------------------------------------------
--
-- A financial ledger that can be edited is not a ledger. Blocking UPDATE and DELETE at
-- the database means an application bug, a migration, or a hand-run statement cannot
-- rewrite history. Corrections must be new rows, which is what makes the trail auditable.

create or replace function public.research_ledger_is_append_only()
returns trigger
language plpgsql
as $$
begin
  raise exception
    'ledger % is append only. Record a new row that references the original instead of % on row %.',
    tg_table_name, tg_op, old.id;
end;
$$;

drop trigger if exists research_commission_ledger_no_update on public.research_commission_ledger;
create trigger research_commission_ledger_no_update
  before update or delete on public.research_commission_ledger
  for each row execute function public.research_ledger_is_append_only();

drop trigger if exists research_store_credit_ledger_no_update on public.research_store_credit_ledger;
create trigger research_store_credit_ledger_no_update
  before update or delete on public.research_store_credit_ledger
  for each row execute function public.research_ledger_is_append_only();

-- ---------------------------------------------------------------------------
-- Payouts
-- ---------------------------------------------------------------------------
--
-- No live payout exists. The provider defaults to disabled and the real adapter is a
-- shell, so these tables hold batches that were built and never sent.

create table if not exists public.research_payout_batches (
  id                uuid primary key default gen_random_uuid(),
  partner_id        uuid not null,
  total_cents       bigint not null check (total_cents >= 0),
  state             text not null default 'built'
                      check (state in ('built','submitted','settled','failed','cancelled')),
  provider_name     text not null default 'disabled',
  provider_reference text,
  -- Entries excluded from the batch and why, so an operator can see what was held back.
  excluded_reasons  text[] not null default '{}',
  built_at          timestamptz not null default now(),
  settled_at        timestamptz,

  constraint research_payout_settled_needs_reference
    check (state <> 'settled' or provider_reference is not null)
);
create index if not exists research_payout_batches_partner_idx
  on public.research_payout_batches (partner_id, built_at);

create table if not exists public.research_payout_attempts (
  id            uuid primary key default gen_random_uuid(),
  batch_id      uuid not null references public.research_payout_batches (id),
  attempt_no    integer not null check (attempt_no > 0),
  outcome       text not null check (outcome in ('disabled','misconfigured','rejected',
                                                 'retryable','permanent_failure','settled')),
  provider_code text,
  attempted_at  timestamptz not null default now(),
  constraint research_payout_attempts_unique unique (batch_id, attempt_no)
);

alter table public.research_commission_ledger   enable row level security;
alter table public.research_store_credit_ledger enable row level security;
alter table public.research_payout_batches      enable row level security;
alter table public.research_payout_attempts     enable row level security;
