export const ROUTES = [
  { path: "/", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Corporate landing page." },
  { path: "/health", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Canonical Care + Research gateway." },
  { path: "/research", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Compatibility route for the gateway." },
  { path: "/research/access-hub", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Routes customers to the correct access path." },
  { path: "/research/order", audience: "Customer", auth: "Public", checkout: "Offer authority", status: "Implemented", note: "Order-entry hub; does not bypass catalog authority." },
  { path: "/research/early-access", audience: "Customer", auth: "Public", checkout: "Server-gated manual/assisted", status: "Implemented", note: "Separate legacy/private manual-payment and assisted lanes require their own server authorities; native direct checkout remains dark." },
  { path: "/research/early-access/order-request", audience: "Customer", auth: "Public", checkout: "Assisted only", status: "Implemented", note: "Request flow; no native payment activation." },
  { path: "/research/apply", audience: "Customer", auth: "Public", checkout: "None", status: "Blocked", note: "Membership application remains legal-pending and is not launch-ready." },
  { path: "/research/sign-in", audience: "Customer", auth: "Public entry", checkout: "None", status: "Implemented", note: "Member authentication entry." },
  { path: "/research/reset-password", audience: "Customer", auth: "Public entry", checkout: "None", status: "Implemented", note: "Password recovery entry; API availability depends on full-server configuration." },
  { path: "/research/catalog", audience: "Customer", auth: "Public", checkout: "None", status: "Blocked", note: "Public catalog route is intentionally unmounted; use authority-backed member or assisted paths." },
  { path: "/research/about", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Research program context." },
  { path: "/research/how-it-works", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Research access and operating model." },
  { path: "/research/faq", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Frequently asked questions." },
  { path: "/research/quality", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Quality standards and evidence posture." },
  { path: "/research/testing", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Testing and verification information." },
  { path: "/research/documents", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Public research documents index." },
  { path: "/research/policies", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Public policy index." },
  { path: "/research/support", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Research support hub." },
  { path: "/research/account", audience: "Member", auth: "Required", checkout: "None", status: "Protected", note: "Canonical account overview." },
  { path: "/research/member/catalog", audience: "Member", auth: "Required", checkout: "Offer authority", status: "Protected", note: "Member catalog; native checkout remains authority-gated." },
  { path: "/research/member/checkout", audience: "Member", auth: "Required", checkout: "DARK", status: "Protected", note: "No direct-buy offerings in current reconciliation." },
  { path: "/research/contact", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Research support contact." },
  { path: "/research/privacy", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Research privacy terms." },
  { path: "/research/terms", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Research terms." },
  { path: "/care", audience: "Customer", auth: "Public", checkout: "Care rail", status: "Implemented", note: "Care landing page." },
  { path: "/care/schedule", audience: "Customer", auth: "Public", checkout: "Care rail", status: "Implemented", note: "Starts a Care access request; no native product checkout." },
  { path: "/care/how-it-works", audience: "Customer", auth: "Public", checkout: "Care rail", status: "Implemented", note: "Care workflow explanation." },
  { path: "/care/portal", audience: "Patient", auth: "External/required", checkout: "Care rail", status: "Implemented", note: "Patient portal handoff." },
  { path: "/contact", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Corporate contact." },
  { path: "/privacy", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Corporate privacy page." },
  { path: "/terms", audience: "Customer", auth: "Public", checkout: "None", status: "Implemented", note: "Corporate terms." },
  { path: "/admin/research", audience: "Internal", auth: "Admin required", checkout: "Operational", status: "Protected", note: "Internal operations; not a customer route." },
];

export const LAUNCH_CHECKLIST = [
  { id: "git-clean", label: "Release commit identified", source: "git" },
  { id: "customer-smoke", label: "Customer smoke passed", source: "action" },
  { id: "typecheck", label: "Typecheck passed", source: "action" },
  { id: "build", label: "Production build passed", source: "action" },
  { id: "checkout-dark", label: "Native checkout remains dark", source: "catalog" },
  { id: "package", label: "Sanitized exact-source package generated", source: "action" },
  { id: "deploy", label: "Production deployment", source: "disabled", note: "Disabled: requires Samuel's explicit approval, exact SHA, prechecks, rollback and smoke." },
];
